import type { CurriculumModule, Lesson } from '@/lib/types'

export const moduleInfo: Omit<CurriculumModule, 'lessons'> = {
  id: 'ap1-costs',
  title: 'AP Micro — Production and Cost',
  description: 'Master the quantitative cost analysis tested heavily on the AP Micro FRQ section.',
  tier: 'AP' as const,
  track: 'AP' as const,
  unit: 1,
  estimatedHours: 3,
  color: '#f59e0b',
  icon: 'Target',
}

export const lessons: Lesson[] = [
  {
    id: 'ap1-l1',
    moduleId: 'ap1-costs',
    title: 'Calculating All Cost Curves from a Table',
    description: 'Given a production table, derive TC, TFC, TVC, ATC, AVC, AFC, and MC.',
    order: 1,
    estimatedMinutes: 40,
    tags: ['cost-curves', 'AP-micro', 'FRQ'],
    flashcards: [
      {
        id: 'fc-ap1-l1-1',
        front: 'How do you calculate Marginal Cost from a production table?',
        back: 'MC = ΔTC / ΔQ. Because fixed costs never change, ΔTC = ΔTVC, so MC can also be computed as ΔTVC / ΔQ.',
        tags: ['cost-curves', 'AP-micro'],
      },
      {
        id: 'fc-ap1-l1-2',
        front: 'What is the relationship between ATC, AVC, and AFC?',
        back: 'ATC = AVC + AFC. As output rises, AFC falls continuously, so ATC and AVC converge but never intersect because AFC is always positive.',
        tags: ['cost-curves', 'AP-micro'],
      },
      {
        id: 'fc-ap1-l1-3',
        front: 'When does ATC reach its minimum point?',
        back: 'ATC is at its minimum when MC = ATC. If MC < ATC the average is still falling; if MC > ATC the average is rising — the MC curve must pass through the ATC trough from below.',
        tags: ['cost-curves', 'AP-micro'],
      },
      {
        id: 'fc-ap1-l1-4',
        front: 'If MC is below ATC, what is happening to ATC, and why?',
        back: 'ATC is falling. The marginal-average rule: when the cost of one more unit is below the running average, it pulls the average down. Mathematically, d(ATC)/dQ < 0 when MC < ATC. ATC only rises when MC > ATC and equals its minimum when MC = ATC.',
        tags: ['cost-curves', 'AP-micro'],
      },
      {
        id: 'fc-ap1-l1-5',
        front: 'What is the relationship between TVC and MC?',
        back: 'MC = ΔTVC / ΔQ, so TVC is the cumulative sum of all marginal costs from zero output to Q. Graphically, TVC is the area under the MC curve up to output Q. Since TFC never changes, ΔTC = ΔTVC — fixed cost drops out of the MC calculation entirely.',
        tags: ['cost-curves', 'AP-micro'],
      },
      {
        id: 'fc-ap1-l1-6',
        front: 'A firm produces 8 units with TFC = $96, AVC = $12. What is ATC?',
        back: 'AFC = TFC/Q = $96/8 = $12. ATC = AVC + AFC = $12 + $12 = $24. TVC = AVC × Q = $12 × 8 = $96. TC = TFC + TVC = $96 + $96 = $192. Check: TC/Q = $192/8 = $24. ✓',
        tags: ['cost-curves', 'calculation'],
      },
      {
        id: 'fc-ap1-l1-7',
        front: 'Why does AFC continuously decline and never reach zero?',
        back: 'AFC = TFC / Q. TFC is a fixed positive number (e.g., $120). As Q increases, TFC/Q approaches zero but never reaches it — a positive number divided by any finite quantity is still positive. AFC is a rectangular hyperbola asymptotic to both axes.',
        tags: ['cost-curves', 'AFC'],
      },
    ],
    quiz: [
      {
        id: 'q-ap1-l1-1',
        type: 'mcq',
        question: 'A firm produces 5 units with TC = $200 and 6 units with TC = $234. What is the marginal cost of the 6th unit?',
        options: ['$23', '$34', '$39', '$47'],
        correctAnswer: 1,
        explanation: 'MC = ΔTC / ΔQ = ($234 − $200) / (6 − 5) = $34. Because only the cost change between the two output levels matters, fixed costs are irrelevant to this calculation.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-2',
        type: 'mcq',
        question: 'A firm has TFC = $120 and AVC at 8 units = $9. Which of the following correctly states ATC at 8 units?',
        options: ['$9.00', '$10.50', '$24.00', '$24.75'],
        correctAnswer: 2,
        explanation: 'AFC = TFC / Q = $120 / 8 = $15. ATC = AVC + AFC = $9 + $15 = $24. The most common error is forgetting to include AFC entirely (giving $9.00) or using the wrong quantity in the AFC calculation.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-3',
        type: 'mcq',
        question: "A firm's TC at 4 units = $160 and TC at 5 units = $190. ATC at 5 units is:",
        options: ['$30', '$38', '$32', '$40'],
        correctAnswer: 1,
        explanation: 'ATC = TC/Q = $190/5 = $38. MC of the 5th unit = $190−$160 = $30. Because MC ($30) < ATC ($38), ATC is still falling at this output — a useful check that the numbers are consistent.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-4',
        type: 'mcq',
        question: 'TVC at 3 units = $60; TVC at 4 units = $84. Which correctly states MC of the 4th unit?',
        options: ['$21', '$24', '$144', '$36'],
        correctAnswer: 1,
        explanation: 'MC = ΔTVC/ΔQ = ($84−$60)/(4−3) = $24/1 = $24. Fixed costs are irrelevant because they do not change between units. Option A ($21) is TVC at 4 units divided by Q (AVC, not MC). Option C confuses TC with MC.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-5',
        type: 'mcq',
        question: 'A firm has TFC = $200. At 10 units, AVC = $15. What is ATC at 10 units?',
        options: ['$15', '$20', '$35', '$30'],
        correctAnswer: 2,
        explanation: 'AFC = TFC/Q = $200/10 = $20. ATC = AVC + AFC = $15 + $20 = $35. The most common error is ignoring AFC and answering $15 — that is just AVC.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-6',
        type: 'mcq',
        question: 'As output increases from 1 to 100 units, which cost measure must continuously decline?',
        options: ['MC', 'AVC', 'ATC', 'AFC'],
        correctAnswer: 3,
        explanation: 'AFC = TFC/Q. Because TFC is constant and positive, dividing by ever-larger Q means AFC falls continuously — it is a declining rectangular hyperbola. MC, AVC, and ATC are all U-shaped.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-7',
        type: 'mcq',
        question: 'At output level Q*, MC = $18 and ATC = $18. Which of the following is true?',
        options: [
          'ATC is falling because MC just reached ATC',
          'ATC is at its minimum because MC = ATC',
          'The firm is earning zero economic profit because MC = ATC',
          'AVC = $18 at this output level',
        ],
        correctAnswer: 1,
        explanation: 'When MC = ATC, ATC is at its minimum — the marginal-average rule tells us ATC neither rises nor falls at this exact point. This is the trough of the U-shaped ATC curve. Zero profit requires P = ATC, not MC = ATC.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-8',
        type: 'mcq',
        question: "A firm's data: Q=5, TFC=$50, TVC=$100, TC=$150. Which calculation contains an error?",
        options: ['ATC = $30', 'AVC = $20', 'AFC = $10', 'MC = $150'],
        correctAnswer: 3,
        explanation: 'MC is ΔTC/ΔQ — you need data from two output levels to compute it, not just one level\'s TC. MC ≠ TC/Q (that is ATC = $30, which is correct). AVC = $100/5 = $20 ✓; AFC = $50/5 = $10 ✓.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-9',
        type: 'mcq',
        question: 'Which of the following correctly explains why ATC and AVC converge as output increases but never intersect?',
        options: [
          'Both ATC and AVC approach MC as output rises, so they must converge',
          'ATC = AVC + AFC, and AFC is always positive — ATC always exceeds AVC by exactly AFC, which approaches but never reaches zero',
          'Fixed costs eventually become zero at large output levels',
          'AVC increases faster than ATC at high output, causing convergence',
        ],
        correctAnswer: 1,
        explanation: 'ATC − AVC = AFC = TFC/Q. TFC is always positive, so the gap is always positive, just getting smaller as Q rises. They converge because AFC shrinks, but they never cross because TFC/Q can never equal zero.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l1-10',
        type: 'mcq',
        question: "A bakery's data shows: Q=10, TC=$300; Q=11, TC=$317; Q=12, TC=$336. Which output level has the highest marginal cost?",
        options: ['Q=10', 'Q=11', 'Q=12', 'All have equal marginal cost'],
        correctAnswer: 2,
        explanation: 'MC of 11th unit = $317−$300 = $17. MC of 12th unit = $336−$317 = $19. MC is rising between these output levels, and Q=12 has the highest MC ($19) of the three. This rising MC pattern is consistent with diminishing marginal returns.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
    content: {
      isStub: false,
      conceptualExplanation: `Cost curves are built entirely from a production table. Starting from total fixed cost (TFC) — which never changes with output — and total variable cost (TVC) — which rises as more labour and materials are used — you derive total cost (TC = TFC + TVC). From these three columns every other cost measure follows mechanically. Marginal cost (MC) is the extra cost of one more unit: MC = ΔTC / ΔQ. Because fixed costs do not change, ΔTC equals ΔTVC, so MC can also be calculated from the variable cost column alone. Average costs are simply the per-unit versions: ATC = TC / Q, AVC = TVC / Q, AFC = TFC / Q.

The key insight is that MC intersects both AVC and ATC at their minimum points. This is a mathematical necessity, not a coincidence: when the cost of producing one more unit is below the current average, the average must be falling; when MC exceeds the average, the average must be rising. Students who master this relationship can reconstruct any cost diagram from first principles and avoid the common error of drawing U-shaped curves that do not satisfy this intersection rule. On AP free-response questions, always show your arithmetic clearly — partial credit is awarded for correct intermediate steps even if the final answer contains an arithmetic slip.`,
      prerequisiteRecap: `This module builds directly on the Intermediate-level treatment of production and costs. You should be comfortable with the law of diminishing marginal returns — the idea that adding variable inputs to a fixed input eventually yields smaller and smaller additions to output — because that physical relationship is exactly what drives the U-shape of the MC, AVC, and ATC curves you will now calculate numerically.`,
      realWorldHook: `In 2023, a Chick-fil-A franchise operator revealed that a single location generates about $8.7 million in annual revenue with roughly $5.2 million in variable costs (food, labour, packaging) and $1.4 million in fixed costs (rent, equipment leases). Calculating TC, ATC, AVC, and MC from those numbers is exactly the skill AP graders test in every free-response section. Franchise operators who misidentify marginal cost miscalculate whether adding a late-night shift will be profitable.`,
      vocabulary: [
        {
          term: 'Total Fixed Cost (TFC)',
          definition: 'Costs that do not change with the level of output; paid regardless of whether the firm produces. Examples: rent, insurance, equipment lease payments.',
          example: 'A restaurant pays $3,000/month in rent whether it serves 0 or 1,000 covers. TFC = $3,000 at every output level.',
        },
        {
          term: 'Marginal Cost (MC)',
          definition: 'The additional cost of producing one more unit of output. MC = ΔTC / ΔQ = ΔTVC / ΔQ. Reflects only the variable input costs added for that unit.',
          example: 'If TC at 9 units = $180 and TC at 10 units = $205, MC of the 10th unit = $205 − $180 = $25.',
        },
        {
          term: 'Average Total Cost (ATC)',
          definition: 'Total cost per unit of output. ATC = TC / Q = AVC + AFC. The U-shape arises because falling AFC initially dominates, then rising AVC takes over.',
          example: 'TC at 5 units = $100 → ATC = $100/5 = $20. If TC at 6 units = $114, ATC = $114/6 = $19 — falling because MC ($14) < ATC ($20).',
        },
      ],
      examinerTip: `AP FRQ graders award partial credit for every correct intermediate calculation. Always show your arithmetic in columns: write out TC = TFC + TVC, then MC = ΔTC/ΔQ row by row. If you make a single arithmetic error, you can still earn most points for correct methodology. Never leave the MC column blank — even an estimate is better than nothing. On the multiple-choice section, when given AVC and TFC, calculate ATC = AVC + AFC and trap yourself from the common distractor of "just AVC."`,
      thinkAboutIt: {
        question: `A firm's fixed costs are $500 per week. Business is terrible and it's only selling 10 units at $30 each, while AVC = $40. Your accountant says you're losing money on every unit AND your total costs are $900. Should you shut down?`,
        answer: `Yes — you should shut down, and here's the precise logic. Revenue per unit ($30) is below AVC ($40), meaning each unit you sell loses you $10 in variable costs alone, on top of the $500 fixed cost you're paying regardless. If you produce, your total loss = $500 fixed + 10×($40−$30) = $500 + $100 = $600. If you shut down, your loss is exactly $500 (just fixed costs). Shutting down saves you $100. The moment P < AVC, every unit produced makes things worse. This is why the AVC minimum is called the shutdown point — it's the exact threshold where the arithmetic flips.`,
      },
    },
    lessonAssignment: {
      prompt: `You are given the following production data for a competitive firm. Complete the cost table and answer the questions below.\n\n| Q | TFC | TVC | TC | MC | ATC | AVC | AFC |\n|---|-----|-----|----|----|-----|-----|-----|\n| 0 | $80 | $0  |    |    |     |     |     |\n| 1 | $80 | $30 |    |    |     |     |     |\n| 2 | $80 | $50 |    |    |     |     |     |\n| 3 | $80 | $80 |    |    |     |     |     |\n| 4 | $80 | $120|    |    |     |     |     |\n| 5 | $80 | $175|    |    |     |     |     |\n\n(a) Fill in all blank cells, showing your arithmetic.\n(b) At what output does MC reach its minimum? What does this imply about marginal returns?\n(c) The market price is $45. Identify the profit-maximising output and calculate total profit or loss.\n(d) At market price = $45, should this firm operate or shut down in the short run? Justify using the correct cost benchmark.`,
      rubric: `Award points for:\n- Complete and correct TC column (TFC + TVC): 1 pt\n- Complete and correct MC column (ΔTC/ΔQ): 2 pts (1 pt if one arithmetic error)\n- Complete and correct ATC, AVC, AFC columns: 2 pts\n- (b) Correct minimum MC output (Q=2, MC=$20) with marginal returns explanation: 2 pts\n- (c) Correct profit-maximising output (Q=4, where P=$45 > MC; at Q=5, MC=$55 > P) with profit calculation: P×Q − TC = $45×4 − $200 = −$20 (loss): 2 pts\n- (d) Correct shutdown analysis: P=$45 > AVC=$30 at Q=4, so operate to minimise loss: 1 pt`,
      exampleTopics: [
        'Complete the TC column first (TFC + TVC), then derive all other columns from it',
        'MC = change in TC from one row to the next — remember MC at Q=1 is TC(1)−TC(0)',
        'For part (c): find where P = MC or the last unit where MR ≥ MC (P = MR for competitive firms)',
        'For part (d): compare P to AVC (not ATC) — if P ≥ AVC, produce; if P < AVC, shut down',
      ],
    },
  },
  {
    id: 'ap1-l2',
    moduleId: 'ap1-costs',
    title: 'Graphing Cost Curves Precisely',
    description: 'Draw all seven cost curves correctly, mark key intersections.',
    order: 2,
    estimatedMinutes: 30,
    tags: ['cost-curves', 'graphs'],
    flashcards: [
      {
        id: 'fc-ap1-l2-1',
        front: 'What shape does the Marginal Cost curve take, and why?',
        back: 'MC is U-shaped. It falls initially because of increasing marginal returns (specialisation), then rises as diminishing marginal returns set in — each additional unit of the variable input adds less to output.',
        tags: ['cost-curves', 'graphs'],
      },
      {
        id: 'fc-ap1-l2-2',
        front: 'Where does MC intersect AVC and ATC on a cost diagram?',
        back: 'MC passes through the minimum of both AVC and ATC. It crosses AVC at a lower output level than ATC because AFC still pulls ATC down even after AVC has begun rising.',
        tags: ['cost-curves', 'graphs'],
      },
      {
        id: 'fc-ap1-l2-3',
        front: 'What is the shape of the AFC curve, and does it ever reach zero?',
        back: 'AFC is a downward-sloping rectangular hyperbola. Because total fixed cost is always positive, AFC approaches but never reaches zero — no matter how large output becomes.',
        tags: ['cost-curves', 'graphs'],
      },
      {
        id: 'fc-ap1-l2-4',
        front: 'On a cost diagram, which curve reaches its minimum at a lower output level — AVC or ATC?',
        back: 'AVC reaches its minimum at a lower output level than ATC. Between the two minima, AVC is rising but ATC is still falling because AFC is declining faster than AVC is rising. Once AVC rises more than AFC falls, ATC also starts rising — at its own (higher) minimum.',
        tags: ['cost-curves', 'graphs'],
      },
      {
        id: 'fc-ap1-l2-5',
        front: 'What is the vertical distance between the ATC curve and the AVC curve at any output level?',
        back: 'The vertical gap between ATC and AVC equals AFC at that output level (AFC = TFC/Q). Because TFC > 0, ATC always lies above AVC. As Q increases, AFC falls and the gap narrows, but ATC and AVC never intersect.',
        tags: ['cost-curves', 'graphs'],
      },
      {
        id: 'fc-ap1-l2-6',
        front: 'Why must the MC curve be steeper than the AVC curve when both are rising?',
        back: 'By the marginal-average rule, AVC rises only when MC > AVC. For AVC to keep rising, MC must continually pull it upward — each new unit adds more cost than the current average. This requires MC to lie above and be rising faster than AVC when AVC is in its rising phase.',
        tags: ['cost-curves', 'graphs'],
      },
      {
        id: 'fc-ap1-l2-7',
        front: 'Sketch (describe) the correct vertical ordering of cost curves at a high output level where the firm is on the rising portions of all U-shaped curves.',
        back: 'From top to bottom: ATC (highest — includes all costs), then AVC (below ATC by the amount AFC), then MC (intersected AVC and ATC at their minima and is now above both and rising steeply). AFC is below all of these, approaching the x-axis. Correct ordering: MC > ATC > AVC > AFC at high output.',
        tags: ['cost-curves', 'graphs'],
      },
    ],
    quiz: [
      {
        id: 'q-ap1-l2-1',
        type: 'mcq',
        question: 'On a correctly drawn cost diagram, the AVC curve reaches its minimum at a lower output level than ATC because:',
        options: [
          'AVC declines faster than ATC at low output levels',
          'AFC is still falling and pulling ATC down even after AVC begins to rise',
          'MC intersects ATC before it intersects AVC',
          'Fixed costs increase the slope of the ATC curve at every output level',
        ],
        correctAnswer: 1,
        explanation: 'After AVC reaches its minimum and starts rising, ATC continues to fall as long as the decline in AFC outweighs the rise in AVC. Once the rising AVC dominates, ATC also starts rising — at a higher output than AVC\'s trough. MC intersects each curve at its own minimum.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-2',
        type: 'mcq',
        question: 'A student draws a cost diagram in which the MC curve intersects ATC to the left of ATC\'s minimum point. This diagram is:',
        options: [
          'Correct — MC can intersect ATC at any point on the downward-sloping section',
          'Incorrect — MC must intersect ATC exactly at ATC\'s minimum point from below',
          'Correct only if the firm has very high fixed costs',
          'Incorrect — MC must lie entirely above ATC',
        ],
        correctAnswer: 1,
        explanation: 'By the marginal-average rule, MC = ATC at ATC\'s minimum. If MC intersects ATC before the minimum, ATC would be rising at that point, which contradicts MC < ATC implying falling ATC. The intersection must occur at the trough, not to its left.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-3',
        type: 'mcq',
        question: 'On a correctly drawn cost diagram, the ATC minimum occurs at a higher output level than the AVC minimum. The most precise reason is:',
        options: [
          'ATC includes fixed costs so it is always greater than AVC',
          'Between the two minima, AVC is rising but AFC is still declining by more, keeping ATC falling until AFC\'s decline can no longer offset AVC\'s rise',
          'MC intersects ATC before it intersects AVC',
          'Fixed costs cause ATC to shift upward relative to AVC',
        ],
        correctAnswer: 1,
        explanation: 'The gap between minima exists because ATC = AVC + AFC. After AVC starts rising, ATC still falls as long as the decline in AFC outweighs the rise in AVC. The ATC minimum occurs where these two forces exactly balance — always to the right of the AVC minimum.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-4',
        type: 'mcq',
        question: 'A student\'s cost diagram shows ATC and AVC crossing at a high output level. This error means the student:',
        options: [
          'Correctly shows economies of scale taking effect at high output',
          'Has incorrectly allowed AFC to become negative, which is impossible since TFC > 0',
          'Has shown that the firm\'s fixed costs decrease at high output levels',
          'Has correctly depicted a firm experiencing increasing returns to scale',
        ],
        correctAnswer: 1,
        explanation: 'ATC − AVC = AFC = TFC/Q. Since TFC is always positive, AFC > 0 at every finite output. ATC must always exceed AVC. If they cross, the diagram implies AFC < 0 at that point — a logical impossibility.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-5',
        type: 'mcq',
        question: 'At output Q = 20, a firm\'s data shows MC = $15 and AVC = $18. Which of the following correctly describes the AVC curve at this point?',
        options: [
          'AVC is at its minimum because MC is below it',
          'AVC is rising because MC > AVC',
          'AVC is falling because MC < AVC, so the marginal cost is pulling the average down',
          'AVC is at its minimum because MC equals AVC',
        ],
        correctAnswer: 2,
        explanation: 'By the marginal-average rule: when MC < AVC, AVC is falling. Here MC ($15) < AVC ($18), so AVC is declining. This places Q=20 on the downward-sloping (left) side of the AVC curve.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-6',
        type: 'mcq',
        question: 'In a correctly drawn cost diagram, MC intersects AVC at AVC\'s minimum. At outputs just above this intersection, which of the following must be true?',
        options: [
          'AVC begins to fall as MC rises above it',
          'AVC begins to rise, because MC now exceeds AVC and pulls the average upward',
          'ATC also reaches its minimum at this same output',
          'MC falls below AVC again as output continues to increase',
        ],
        correctAnswer: 1,
        explanation: 'When MC rises above AVC (after their intersection at AVC\'s minimum), each additional unit costs more than the current average variable cost, pulling AVC upward. ATC\'s minimum occurs at a higher output because AFC is still declining and offsetting the AVC rise.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-7',
        type: 'mcq',
        question: 'A firm\'s cost diagram shows the MC curve rising steeply and passing through the ATC curve from below. What must be true about ATC at this intersection?',
        options: [
          'ATC is at its minimum, and will begin rising for higher output levels',
          'ATC is rising, and this intersection is the profit-maximising output',
          'ATC is at its maximum, and will begin falling for higher output levels',
          'ATC is still falling, and the intersection confirms diminishing returns',
        ],
        correctAnswer: 0,
        explanation: 'MC = ATC at ATC\'s minimum, by the marginal-average rule. At outputs above this intersection, MC > ATC and ATC rises. The intersection is not the profit-maximising output — that is where P = MC.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-8',
        type: 'mcq',
        question: 'Which of the following is an accurate description of the AFC curve?',
        options: [
          'U-shaped, reaching a minimum at the output where MC intersects AFC',
          'Continuously declining from left to right, approaching the horizontal axis but never reaching it',
          'Horizontal at the level of total fixed cost, shifting only when fixed costs change',
          'Declining then rising, with a minimum that coincides with the AVC minimum',
        ],
        correctAnswer: 1,
        explanation: 'AFC = TFC/Q. Because TFC is a positive constant, AFC traces a rectangular hyperbola — always declining, always positive, asymptotically approaching zero as Q increases. It has no minimum (it never stops declining) and never intersects the x-axis.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-9',
        type: 'mcq',
        question: 'A firm is operating at a point where MC > ATC. An AP student correctly concludes that the firm should:',
        options: [
          'Increase output to lower ATC back to its minimum',
          'Reduce output until ATC falls back to its minimum, where MC = ATC',
          'Continue at the current output if the market price exceeds ATC',
          'Shut down because producing beyond ATC\'s minimum is always unprofitable',
        ],
        correctAnswer: 1,
        explanation: 'When MC > ATC, ATC is rising — the firm is producing beyond the productive efficiency point. To reach minimum ATC (productive efficiency), the firm should reduce output. However, the profit-maximising decision depends on comparing P to MC, not on minimising ATC. The firm does NOT automatically shut down.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l2-10',
        type: 'mcq',
        question: 'Which pair of statements about cost curves is fully consistent with a correctly drawn AP Micro cost diagram?',
        options: [
          'MC intersects AVC to the right of AVC\'s minimum; ATC lies below AVC at all output levels',
          'MC passes through AVC\'s minimum; ATC always lies above AVC; AFC continuously declines',
          'AVC and ATC intersect at high output levels; MC equals ATC only at the origin',
          'AFC is U-shaped; AVC declines faster than ATC at all output levels',
        ],
        correctAnswer: 1,
        explanation: 'The three rules: MC passes through AVC minimum (and ATC minimum at a higher Q); ATC = AVC + AFC with AFC > 0 always, so ATC > AVC always; AFC = TFC/Q continuously declines. All three statements in option B are simultaneously true and mutually consistent.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
    content: {
      isStub: false,
      conceptualExplanation: `Translating cost data into accurate diagrams requires understanding the geometry of the curves before putting pencil to paper. The MC curve is drawn U-shaped because marginal returns first increase (each additional worker adds more to output than the last, reducing per-unit cost) and then diminish, causing MC to rise. Because AFC declines continuously but AVC is U-shaped, ATC — which equals their sum — is also U-shaped but reaches its minimum at a higher output level than AVC. This gap between the minima is precisely AFC at that output, which is always positive.

For the AP exam, diagram precision earns full marks. Label every curve, mark the minimum points of AVC and ATC, and ensure MC passes through both minima from below. A common error is drawing MC that cuts ATC at a point to the left of ATC's trough — this is geometrically impossible. Another trap is allowing AVC and ATC to converge and cross; they never do because AFC > 0 for all positive output. Practice reproducing the full seven-curve diagram from memory, then verify each intersection satisfies the marginal-average rule.`,
      prerequisiteRecap: `Lesson 1 established how to calculate all seven cost measures from a data table and proved that MC must pass through the minimum of both AVC and ATC. Lesson 2 now translates those numerical relationships into precise geometry — every curve shape and intersection you draw must be consistent with the arithmetic you already know.`,
      recallQuestions: [
        {
          id: 'ap1-l2-recall-1',
          type: 'mcq',
          question: 'A firm has TFC = $60 and produces 6 units with TVC = $90. Which of the following correctly states ATC at 6 units?',
          options: ['$15.00', '$25.00', '$10.00', '$9.00'],
          correctAnswer: 1,
          explanation: 'ATC = TC / Q = (TFC + TVC) / Q = ($60 + $90) / 6 = $150 / 6 = $25.00. You can verify via components: AFC = $60/6 = $10; AVC = $90/6 = $15; ATC = AFC + AVC = $10 + $15 = $25. Option A ($15) is just AVC; option C ($10) is just AFC.',
          marks: 1,
          difficulty: 'standard',
        },
        {
          id: 'ap1-l2-recall-2',
          type: 'mcq',
          question: 'At an output level where MC < ATC, which of the following must be true about ATC?',
          options: [
            'ATC is falling, because each additional unit costs less than the current average.',
            'ATC is rising, because marginal cost is below average cost.',
            'ATC has reached its minimum value.',
            'ATC equals AVC at this output level.',
          ],
          correctAnswer: 0,
          explanation: 'When MC < ATC, the cost of the last unit produced is below the running average. By the marginal-average rule, this pulls the average down — ATC must be falling. ATC reaches its minimum only when MC = ATC, and ATC is rising only when MC > ATC.',
          marks: 1,
          difficulty: 'standard',
        },
      ],
      realWorldHook: `The 2022 Federal Reserve rate hikes forced dozens of US tech firms to confront their cost structures visually for the first time. Stripe, Lyft, and Meta all laid off workers when they realised their ATC curves — bloated by years of zero-interest-rate hiring — were far above the prices the market would bear. Being able to look at a cost diagram and immediately identify whether P > ATC, P is between ATC and AVC, or P < AVC is the skill that separates financial analysts who can diagnose a distressed company from those who just read the earnings report.`,
      vocabulary: [
        {
          term: 'U-shaped cost curve',
          definition: 'The characteristic shape of MC, AVC, and ATC, reflecting first increasing then decreasing marginal returns. MC falls when the marginal product of labour is rising, and rises when it is falling.',
          example: "A restaurant's marginal cost of meals initially falls as a second chef allows specialisation, then rises as the kitchen becomes crowded.",
        },
        {
          term: 'Marginal-average rule',
          definition: 'When MC < AVC (or ATC), the average is falling. When MC > AVC (or ATC), the average is rising. When MC = AVC (or ATC), the average is at its minimum.',
          example: 'If your last exam score (marginal) is below your current average, your average falls. Same mathematics applies to cost curves.',
        },
        {
          term: 'Shut-down price',
          definition: 'The market price equal to minimum AVC — the lowest price at which a competitive firm will produce rather than temporarily close. Graphically, it is the lowest point on the AVC curve, where MC intersects AVC.',
          example: 'If minimum AVC = $12, a firm facing P = $11 shuts down; facing P = $13, it produces at a loss but stays open.',
        },
      ],
      examinerTip: `On the AP Micro diagram question, graders use a checklist. Earn all 3-4 diagram points by: (1) drawing MC as U-shaped and steeper than AVC; (2) ensuring MC intersects both AVC and ATC at their minimum points, with the AVC minimum to the LEFT of the ATC minimum; (3) showing ATC always above AVC (the gap = AFC); (4) drawing AFC as a continuously declining curve that never touches the x-axis. A common 1-point deduction is drawing the MC curve that intersects ATC at a point to the left of its minimum — this violates the marginal-average rule. Label every curve.`,
      thinkAboutIt: {
        question: `Here's a seemingly paradoxical statement: 'A firm's average total cost is falling even though its average variable cost is rising.' Is this possible, or is it a contradiction?`,
        answer: `It's entirely possible — and it happens regularly in the range between the minima of AVC and ATC. ATC = AVC + AFC. If AVC is rising slightly but AFC is still falling steeply, the net effect is that ATC continues to decline. Think of it numerically: if AVC rises from $10 to $11 (up $1) but AFC falls from $8 to $6 (down $2), then ATC falls from $18 to $17. This is exactly the region between the two minimum points on the cost diagram. Once AVC rises fast enough to overcome the falling AFC — i.e., the rise in AVC exceeds the fall in AFC — ATC starts rising too. This is why the AVC minimum is always to the LEFT of the ATC minimum on every correctly drawn cost diagram.`,
      },
    },
    lessonAssignment: {
      prompt: `Draw a fully labelled cost diagram showing all five cost curves (MC, ATC, AVC, AFC, and a reference point for TFC as a horizontal line) for a typical perfectly competitive firm. Then annotate your diagram by (a) identifying the shutdown price, (b) identifying the break-even price, (c) shading the area that represents total fixed cost at a specific output of your choice, and (d) explaining in two sentences why AVC reaches its minimum at a lower output than ATC.`,
      rubric: `Award points for:\n- All 5 curves correctly shaped and labelled (MC U-shaped, ATC above AVC, AFC declining, TFC horizontal) — 3 pts\n- MC correctly intersects AVC at AVC minimum AND ATC at ATC minimum, with AVC minimum to the left — 2 pts\n- (a) Shutdown price correctly identified at minimum AVC — 1 pt\n- (b) Break-even price correctly identified at minimum ATC — 1 pt\n- (c) TFC shaded correctly as the vertical distance between ATC and AVC multiplied by Q, or as TFC rectangle — 1 pt\n- (d) Explanation references ATC = AVC + AFC and the offsetting role of declining AFC — 2 pts`,
      exampleTopics: [
        'Draw from scratch: start with U-shaped MC, then add U-shaped ATC above it, then AVC below ATC (parallel but lower), then falling AFC',
        'Mark the two minimum points carefully — MC passes through both, but AVC minimum is LEFT of ATC minimum',
        'The shutdown price is at minimum AVC (where MC intersects AVC), not minimum ATC',
        'For part (d): use numbers — at Q between the two minima, AVC is rising by say $2 but AFC is falling by $4, so ATC still falls by $2',
      ],
    },
  },
  {
    id: 'ap1-l3',
    moduleId: 'ap1-costs',
    title: 'Short-Run Shutdown vs. Long-Run Exit',
    description: 'Explain the logic: shut down if P < AVC; exit if P < ATC.',
    order: 3,
    estimatedMinutes: 25,
    tags: ['shutdown', 'exit', 'supply-curve'],
    flashcards: [
      {
        id: 'fc-ap1-l3-1',
        front: 'What is the short-run shutdown rule for a competitive firm?',
        back: 'Shut down if P < AVC. At that point, revenue does not cover variable costs, so producing increases losses relative to simply paying fixed costs and producing nothing.',
        tags: ['shutdown', 'supply-curve'],
      },
      {
        id: 'fc-ap1-l3-2',
        front: 'What is the long-run exit rule for a competitive firm?',
        back: 'Exit the industry if P < ATC. In the long run all costs are variable, so if revenue does not cover total cost the firm earns a sustained negative economic profit and should redeploy its capital.',
        tags: ['exit', 'supply-curve'],
      },
      {
        id: 'fc-ap1-l3-3',
        front: 'Why might a firm continue to operate in the short run even while making a loss?',
        back: 'If P ≥ AVC, operating covers all variable costs and contributes toward unavoidable fixed costs. The loss from producing is smaller than the loss from shutting down (all fixed costs). Fixed costs are sunk in the short run.',
        tags: ['shutdown', 'supply-curve'],
      },
      {
        id: 'fc-ap1-l3-4',
        front: 'Describe the three possible short-run situations for a competitive firm in terms of price vs. cost benchmarks.',
        back: '1. P > ATC: firm earns economic profit — produces at MR=MC. 2. AVC ≤ P < ATC: firm earns a loss but covers variable costs — produces at MR=MC to minimise loss. 3. P < AVC: firm shuts down — loss equals TFC (smaller than operating loss).',
        tags: ['shutdown', 'supply-curve'],
      },
      {
        id: 'fc-ap1-l3-5',
        front: "Why is the firm's short-run supply curve the MC curve above AVC rather than the entire MC curve?",
        back: 'Below minimum AVC, the firm shuts down (produces zero). Above minimum AVC, the firm produces the quantity where P = MC. The supply curve therefore starts at the minimum AVC point and follows MC upward — the MC curve above AVC is the competitive firm\'s short-run supply curve.',
        tags: ['shutdown', 'supply-curve'],
      },
      {
        id: 'fc-ap1-l3-6',
        front: 'A firm has AVC = $14, ATC = $20, and faces P = $17. Calculate total profit or loss if TFC = $60 and Q = 10 at the profit-maximising output.',
        back: 'TR = P × Q = $17 × 10 = $170. TC = ATC × Q = $20 × 10 = $200. Economic profit = $170 − $200 = −$30 (loss). Check short-run decision: P ($17) > AVC ($14), so operating is correct — the operating loss ($30) is less than the shut-down loss ($60 = TFC). ✓',
        tags: ['shutdown', 'calculation'],
      },
      {
        id: 'fc-ap1-l3-7',
        front: 'In the long run, why are all costs variable (and why does this change the exit decision)?',
        back: 'In the long run, contracts expire, leases end, and capital can be redeployed or sold. There are no unavoidably fixed costs. Therefore, a firm compares price to full ATC — if P < min ATC, total revenue doesn\'t cover total cost and the firm earns negative economic profit indefinitely. Rational owners exit, redeploying resources to their next-best use.',
        tags: ['exit', 'long-run'],
      },
    ],
    quiz: [
      {
        id: 'q-ap1-l3-1',
        type: 'mcq',
        question: 'A firm has AVC = $10, ATC = $16, and faces a market price of $13. What is the firm\'s rational short-run and long-run strategy?',
        options: [
          'Shut down immediately in both the short run and long run',
          'Produce in the short run to minimise losses; plan to exit in the long run',
          'Produce in both the short run and long run and earn a profit',
          'Shut down in the short run; re-enter when price rises above AVC',
        ],
        correctAnswer: 1,
        explanation: 'P = $13 > AVC = $10, so each unit sold covers variable costs and contributes $3 toward fixed costs — producing reduces losses compared to shutting down. However, P = $13 < ATC = $16, meaning the firm incurs an economic loss on every unit. In the long run, when all costs become variable, the firm should exit unless price rises to at least $16.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-2',
        type: 'mcq',
        question: 'Fixed costs are irrelevant to the short-run shutdown decision primarily because:',
        options: [
          'Fixed costs are zero when the firm shuts down temporarily',
          'Fixed costs must be paid whether or not the firm produces, so they cannot be avoided by shutting down',
          'Fixed costs equal variable costs at the shutdown point, cancelling each other out',
          'The government reimburses fixed costs when a firm temporarily ceases production',
        ],
        correctAnswer: 1,
        explanation: 'Fixed costs are sunk in the short run — rent, loan payments, and lease obligations cannot be escaped by ceasing output. The only costs a firm avoids by shutting down are variable costs. Therefore, the shutdown comparison is between revenue and variable cost (AVC), not total cost.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-3',
        type: 'mcq',
        question: 'A competitive firm has minimum AVC = $8 and minimum ATC = $14. The market price falls to $10. Which of the following best describes the firm\'s situation?',
        options: [
          'The firm should exit the industry immediately because it is earning a loss',
          'The firm should shut down because P < minimum ATC',
          'The firm should continue producing in the short run because P > minimum AVC, but should plan to exit in the long run if price remains at $10',
          'The firm should continue producing and will earn economic profit because P > minimum AVC',
        ],
        correctAnswer: 2,
        explanation: 'P = $10 > min AVC = $8: the firm covers variable costs and contributes $2 per unit toward fixed costs — producing minimises the short-run loss. But P = $10 < min ATC = $14: the firm earns a loss. In the long run, all costs are variable, so if price stays at $10, the firm cannot cover total costs and should exit.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-4',
        type: 'mcq',
        question: 'At the shutdown point, which of the following is true?',
        options: [
          'P = minimum ATC, so the firm earns zero economic profit',
          'P = minimum AVC, so the firm is exactly indifferent between producing and shutting down',
          'P = MC, so the firm is maximising profit',
          'P = AFC, so the firm\'s revenue exactly covers fixed costs',
        ],
        correctAnswer: 1,
        explanation: 'At the shutdown point, P = min AVC. The firm\'s total revenue exactly equals total variable cost (P×Q = AVC×Q = TVC). The firm is indifferent — it loses exactly TFC whether it produces or shuts down. Any price above this makes producing strictly better.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-5',
        type: 'mcq',
        question: 'A firm has TFC = $100, TVC = $80, and TR = $95 at its profit-maximising output. In the short run, the firm should:',
        options: [
          'Shut down, because TR < TC',
          'Produce, because TR > TVC — the firm more than covers variable costs and contributes $15 toward fixed costs',
          'Exit the industry, because it is making a loss',
          'Produce at a different output where TR > TC',
        ],
        correctAnswer: 1,
        explanation: 'Shutdown loss = TFC = $100. Operating loss = TC − TR = ($100 + $80) − $95 = $85. Since the operating loss ($85) < shutdown loss ($100), the firm minimises losses by producing. The key test: TR ($95) > TVC ($80) ✓ — covers variable costs with $15 to spare.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-6',
        type: 'mcq',
        question: 'In the long run, a competitive firm will exit if:',
        options: [
          'P < AVC, because it cannot cover variable costs',
          'P < ATC, because total revenue does not cover total (economic) cost',
          'P < MC at the profit-maximising output',
          'Profits are below normal profit in the short run',
        ],
        correctAnswer: 1,
        explanation: 'In the long run, all costs are variable — there are no sunk fixed costs. A firm should exit if its revenue cannot cover total economic cost (including a normal profit on capital). The long-run exit condition is P < min ATC.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-7',
        type: 'mcq',
        question: 'A hotel has annual fixed costs of $2 million (mortgage, insurance, management). Variable costs per occupied room = $40. During an off-peak period, the best achievable room rate is $30/night. What should the hotel do in the short run?',
        options: [
          'Operate — the room rate is close to variable cost and will cover some fixed costs',
          'Shut down — P < AVC means every room rented deepens the loss beyond the fixed-cost loss',
          'Exit the industry — the hotel should sell the property immediately',
          'Operate only if it can raise the room rate above average total cost',
        ],
        correctAnswer: 1,
        explanation: 'P = $30 < AVC = $40. Each room rented loses $10 in variable costs alone, on top of the $2 million in unavoidable fixed costs. Shutdown loss = $2M fixed costs. Operating loss = $2M + (number of rooms × $10). Every additional room deepens losses. The hotel should shut down the room operation (though it may keep staff on reduced hours).',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-8',
        type: 'mcq',
        question: "Which of the following correctly states the competitive firm's short-run supply curve?",
        options: [
          'The entire MC curve, from the origin upward',
          'The MC curve at output levels above minimum ATC',
          'The MC curve at output levels above minimum AVC, with zero output at prices below minimum AVC',
          'The AVC curve, since AVC determines whether the firm produces',
        ],
        correctAnswer: 2,
        explanation: 'The short-run supply curve is the MC curve above minimum AVC. At P < min AVC, quantity supplied = 0 (shutdown). At P ≥ min AVC, the firm supplies the quantity where P = MC (from the MC curve). The supply curve \'starts\' at the minimum AVC point.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-9',
        type: 'mcq',
        question: 'Sunk costs are irrelevant to production decisions because:',
        options: [
          'Sunk costs have already been paid and cannot be recovered — they do not change based on the firm\'s output decision',
          'Sunk costs are small compared to variable costs in most industries',
          'Government accounting rules exclude sunk costs from profit calculations',
          'Sunk costs are refundable if the firm exits the industry',
        ],
        correctAnswer: 0,
        explanation: 'Sunk costs are irrelevant because they are the same regardless of the decision made. Whether the firm produces 0 or 1,000 units, a sunk fixed cost (like a non-refundable lease) is paid. Only costs that CHANGE with the decision — variable costs — affect the optimal output choice.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l3-10',
        type: 'mcq',
        question: "Evaluate the following claim: 'A firm earning a loss should always shut down to stop losing money.'",
        options: [
          'Correct — losses mean TR < TC, so the firm is always better off producing nothing',
          'Incorrect — if P ≥ AVC, the firm minimises losses by producing rather than shutting down, because shutting down only avoids variable costs while fixed costs remain',
          'Correct — in both the short run and long run, losses indicate the firm should exit',
          'Incorrect — a firm earning a loss should increase output until TR = TC',
        ],
        correctAnswer: 1,
        explanation: 'This claim confuses the short run with the long run. In the short run, a loss-making firm (P < ATC) should produce as long as P ≥ AVC — producing reduces the total loss below TFC. Shutting down only avoids variable costs; fixed costs remain. The claim is correct only in the long run (P < min ATC triggers exit) or when P < min AVC (shutdown in the short run).',
        marks: 1,
        difficulty: 'higher',
      },
    ],
    content: {
      isStub: false,
      conceptualExplanation: `The distinction between shutting down and exiting hinges entirely on the time horizon. In the short run, some costs — rent, loan payments, equipment leases — are fixed and cannot be avoided whether the firm produces or not. These are sunk costs from a short-run perspective. The only costs a firm avoids by ceasing production are variable costs (labour, materials). Therefore, a rational firm compares price to average variable cost: if P ≥ AVC, producing is better than not producing because revenue at least covers avoidable costs and contributes something toward unavoidable fixed costs. The firm minimises its loss by staying open. Only if P < AVC does shutting down reduce losses further.

In the long run, no costs are fixed — contracts expire, leases end, capital can be sold. A firm compares price to full average total cost. If P < ATC, the firm earns negative economic profit indefinitely and rational owners exit the industry, redeploying capital elsewhere. This two-horizon framework explains why industries sustain loss-making firms for extended periods: as long as price clears the AVC hurdle, short-run operation is rational. AP free-response questions frequently present numerical scenarios requiring students to apply both rules — always state which time horizon applies, which cost benchmark is relevant, and what the firm should do.`,
      prerequisiteRecap: `Lessons 1 and 2 built and graphed all seven cost curves and established that MC passes through the minimum of both AVC and ATC. Lesson 3 puts those curves to work: the minimum points of AVC and ATC are not just geometric features — they are the critical price thresholds that determine whether a firm produces or shuts down in the short run, and whether it stays in or exits an industry in the long run.`,
      recallQuestions: [
        {
          id: 'ap1-l3-recall-1',
          type: 'mcq',
          question: 'On a correctly drawn cost diagram, the MC curve intersects the AVC curve at AVC\'s minimum point. What does this minimum of AVC represent for a competitive firm\'s short-run decision?',
          options: [
            'The shutdown point — if price falls below minimum AVC, the firm minimises losses by ceasing production.',
            'The break-even point — if price equals minimum AVC, the firm earns zero economic profit.',
            'The profit-maximising point — the firm should always produce at minimum AVC.',
            'The exit point — if price falls below minimum AVC, the firm must leave the industry permanently.',
          ],
          correctAnswer: 0,
          explanation: 'Minimum AVC is the shutdown price. If P < min AVC, revenue per unit is insufficient to cover even variable costs, so each unit produced deepens the loss beyond the fixed-cost loss of zero output. The firm minimises loss by shutting down. Exit (leaving the industry permanently) is the long-run decision triggered when P < min ATC.',
          marks: 1,
          difficulty: 'standard',
        },
        {
          id: 'ap1-l3-recall-2',
          type: 'mcq',
          question: 'A firm\'s AFC at 10 units is $8. If AVC at 10 units is $14, what is ATC, and what is TFC?',
          options: [
            'ATC = $22; TFC = $80',
            'ATC = $6; TFC = $80',
            'ATC = $22; TFC = $140',
            'ATC = $14; TFC = $80',
          ],
          correctAnswer: 0,
          explanation: 'ATC = AVC + AFC = $14 + $8 = $22. TFC = AFC × Q = $8 × 10 = $80. TFC is constant at all output levels — a key fact that connects the AFC curve (TFC/Q, always falling) to the fixed-cost concept from Lesson 1.',
          marks: 1,
          difficulty: 'standard',
        },
      ],
      realWorldHook: `During the 2020 COVID-19 lockdowns, thousands of restaurants had to make the exact shutdown-vs-exit calculation in real time. A Manhattan restaurant with $40,000/month rent (fixed), $25,000 in variable costs per month, and only $20,000 in potential revenue faced two choices: shut down temporarily (lose $40,000/month in fixed costs only) or operate (lose $40,000 + the $5,000 shortfall on variable costs = $45,000). The rational choice was to shut down. But a restaurant in the same position with $35,000 in revenue would keep operating — $35,000 > $25,000 in variable costs means operating reduces the loss. Understanding this exactly is the difference between Chapter 7 bankruptcy and Chapter 11 reorganisation.`,
      vocabulary: [
        {
          term: 'Shutdown point',
          definition: 'The price level equal to minimum AVC. If P < min AVC, the firm minimises losses by shutting down in the short run (output = 0). If P ≥ min AVC, producing reduces losses relative to shutdown.',
          example: 'If min AVC = $12 and market price falls to $10, the firm shuts down. At P = $14, it produces at a loss but stays open because each unit contributes $2 toward unavoidable fixed costs.',
        },
        {
          term: 'Break-even price',
          definition: 'The price equal to minimum ATC. At this price, total revenue exactly equals total cost and the firm earns zero economic profit (normal profit). Above this price, the firm earns economic profit.',
          example: 'If min ATC = $20, a firm with P = $20 earns zero economic profit — it covers all explicit and implicit costs including a normal return on capital.',
        },
        {
          term: 'Sunk cost',
          definition: 'A cost that has already been incurred and cannot be recovered, regardless of the decision made. Sunk costs are irrelevant to rational forward-looking decisions.',
          example: 'A $50,000 custom oven installation that cannot be removed or resold is sunk. Whether to operate the restaurant tomorrow depends on future revenue vs. variable costs, not the already-paid oven cost.',
        },
      ],
      examinerTip: `AP FRQ graders dock points for conflating the two time horizons. Always explicitly state: 'In the short run, the shutdown rule is P compared to min AVC' and 'In the long run, the exit rule is P compared to min ATC.' If a question gives you AVC and ATC and asks what the firm should do, identify BOTH the short-run and long-run decisions separately. A common error is saying the firm 'should shut down' when P < ATC — this is only true in the long run. In the short run, if P ≥ AVC, the firm minimises losses by continuing to produce.`,
      thinkAboutIt: {
        question: `Why do economists say that 'fixed costs don't matter for the shutdown decision' — but those fixed costs are clearly causing the firm to lose money. How can costs that are causing losses be irrelevant?`,
        answer: `The key word is irrelevant — not zero. Fixed costs are real and painful. But they are irrelevant to the SHUTDOWN decision specifically because they are unavoidable: you pay them whether you produce or not. When deciding whether to produce, the only costs that are avoidable are variable costs. The comparison is: 'If I produce, will I at least recover my variable costs?' If yes, producing reduces the total loss. The fixed costs are a sunk cost from the perspective of the short-run production decision — they've been committed to regardless. Technically, fixed costs are relevant to the exit decision (long run) because eventually contracts expire and you can avoid them. But in the short run, they are irrelevant to whether you operate. This distinction — between costs that change with your decision and costs that don't — is one of the most important ideas in managerial economics.`,
      },
    },
    lessonAssignment: {
      prompt: `A competitive firm faces the following cost data at its profit-maximising output of 50 units: Price = $18, AVC = $15, ATC = $22, MC = $18, TFC = $350. (a) Calculate total revenue, total cost, and economic profit or loss. (b) Is the firm making the correct short-run decision by producing? Show your reasoning using the shutdown rule. (c) What should the firm do in the long run if price remains at $18? (d) At what minimum price would the firm just break even in the long run? At what minimum price would it shut down in the short run?`,
      rubric: `Award points for:\n- (a) TR = $18×50 = $900; TC = $22×50 = $1,100; Loss = $900−$1,100 = −$200: 2 pts\n- (b) Yes — P ($18) > AVC ($15), so producing is correct. Operating loss = $200 < shutdown loss = TFC = $350: 2 pts\n- (c) Exit in the long run because P ($18) < min ATC ($22) — earns sustained economic loss: 2 pts\n- (d) Break-even (long-run stay): P = min ATC = $22; Shutdown (short-run): P = min AVC = $15: 2 pts\n- Clear communication using correct economic terminology throughout: 2 pts`,
      exampleTopics: [
        'For part (a): TR = P × Q, TC = ATC × Q — don\'t forget to use Q = 50',
        'For part (b): compare P to AVC (not ATC!) — the shutdown rule is P vs AVC, not P vs ATC',
        'For part (c): in the long run, all costs are variable — compare P to ATC for the exit decision',
        'For part (d): minimum ATC = break-even price; minimum AVC = shutdown price — these are the two critical prices on every cost diagram',
      ],
    },
  },
  {
    id: 'ap1-l4',
    moduleId: 'ap1-costs',
    title: 'Long-Run Cost and Industry Adjustment',
    description: "Trace a perfectly competitive industry's long-run adjustment after a demand shock.",
    order: 4,
    estimatedMinutes: 35,
    tags: ['long-run', 'industry-adjustment', 'entry-exit'],
    flashcards: [
      {
        id: 'fc-ap1-l4-1',
        front: 'What is the Long-Run Average Cost (LRAC) curve?',
        back: 'The envelope of all short-run ATC curves. It shows the lowest achievable average cost for each output level when the firm can choose any scale of operation (all inputs are variable).',
        tags: ['long-run', 'industry-adjustment'],
      },
      {
        id: 'fc-ap1-l4-2',
        front: 'What causes economies of scale?',
        back: 'LRAC falls as output rises due to greater specialisation of labour, spreading of indivisible capital costs, bulk purchasing discounts, and learning-by-doing effects. Diseconomies of scale arise from managerial complexity at very large scales.',
        tags: ['long-run', 'entry-exit'],
      },
      {
        id: 'fc-ap1-l4-3',
        front: 'How does a constant-cost perfectly competitive industry adjust to a positive demand shock in the long run?',
        back: 'The demand shock raises price and creates short-run economic profit. New firms enter, shifting market supply rightward, until price falls back to minimum ATC and economic profit returns to zero. Long-run supply is horizontal.',
        tags: ['long-run', 'industry-adjustment', 'entry-exit'],
      },
      {
        id: 'fc-ap1-l4-4',
        front: 'What is minimum efficient scale (MES), and why does it matter for industry structure?',
        back: 'Minimum efficient scale is the lowest output level at which LRAC reaches its minimum — the point where all available economies of scale have been fully exploited. Industries where MES is large relative to total market demand tend to support only a few firms (concentrated industries), because a small-scale firm would face higher average costs and be unable to compete on price with large-scale rivals.',
        tags: ['long-run', 'industry-adjustment'],
      },
      {
        id: 'fc-ap1-l4-5',
        front: 'How does an increasing-cost industry differ from a constant-cost industry in its long-run supply response?',
        back: 'In an increasing-cost industry, expansion of the industry bids up the prices of specialised inputs (land, skilled labour, raw materials). New entrant firms therefore face higher input costs than original firms did, so the new long-run equilibrium price is higher than the original equilibrium price. The long-run supply curve slopes upward rather than being horizontal. Each firm still earns zero economic profit in the new equilibrium, but at a higher minimum ATC.',
        tags: ['long-run', 'industry-adjustment', 'entry-exit'],
      },
      {
        id: 'fc-ap1-l4-6',
        front: 'What happens in a perfectly competitive industry when economic losses persist in the short run?',
        back: 'Sustained losses (P < ATC) trigger long-run exit: firms whose leases and contracts expire redeploy capital to better uses. As firms leave, market supply shifts leftward, pushing price upward until price returns to minimum ATC and the remaining firms earn zero economic profit. The industry shrinks — fewer firms, lower total output — but each surviving firm returns to its efficient scale.',
        tags: ['long-run', 'entry-exit'],
      },
      {
        id: 'fc-ap1-l4-7',
        front: 'Why does the long-run equilibrium for a perfectly competitive firm always land at minimum LRAC?',
        back: 'If price exceeds minimum LRAC, economic profit draws in new entrants, expanding supply and pushing price down toward minimum LRAC. If price is below minimum LRAC, losses drive exit, contracting supply and pushing price up. Only at price = minimum LRAC are there no incentives to enter or exit. This self-correcting mechanism is why economists call minimum LRAC the long-run zero-profit point — it is the only stable rest state for a competitive industry.',
        tags: ['long-run', 'industry-adjustment'],
      },
    ],
    quiz: [
      {
        id: 'q-ap1-l4-1',
        type: 'mcq',
        question: 'If a firm doubles all inputs and output rises by 150%, the firm is experiencing:',
        options: [
          'Diseconomies of scale — costs are rising faster than output',
          'Constant returns to scale — output doubles with inputs',
          'Economies of scale — LRAC is falling as output expands',
          'Diminishing marginal returns — a short-run phenomenon',
        ],
        correctAnswer: 2,
        explanation: 'When output rises proportionally more than inputs (150% > 100%), the firm\'s long-run average cost falls — this is economies of scale. Diminishing marginal returns is a short-run concept about adding a variable input to a fixed input, not about scaling all inputs simultaneously.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-2',
        type: 'mcq',
        question: 'In a constant-cost perfectly competitive industry, a permanent increase in market demand leads to a new long-run equilibrium with:',
        options: [
          'A higher equilibrium price and the same number of firms',
          'The same equilibrium price and greater total industry output',
          'A lower equilibrium price due to economies of scale in new entrant firms',
          'A higher equilibrium price and each firm producing a larger quantity',
        ],
        correctAnswer: 1,
        explanation: 'In a constant-cost industry, input prices do not rise as the industry expands, so new firms enter until price returns to the original minimum ATC. The long-run supply curve is perfectly elastic (horizontal). Total industry output is higher because more firms are now in the market, but the equilibrium price and each individual firm\'s output are unchanged.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-3',
        type: 'mcq',
        question: 'The LRAC curve is described as the "envelope" of all short-run ATC curves. This means:',
        options: [
          'LRAC is always higher than each individual short-run ATC curve at every output level',
          'LRAC traces the lowest attainable average cost at each output level across all possible plant sizes',
          'LRAC intersects each short-run ATC curve at that curve\'s minimum point',
          'LRAC is a straight horizontal line connecting the minima of all short-run ATC curves',
        ],
        correctAnswer: 1,
        explanation: 'The LRAC curve is the lower boundary formed by all possible short-run ATC curves — one for each feasible plant size. At any output level, a firm can choose the plant size that minimises average cost, so LRAC shows the best achievable cost. LRAC touches each short-run ATC curve from below (at tangency) but only intersects a short-run ATC at its minimum at the minimum efficient scale output.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-4',
        type: 'mcq',
        question: 'A perfectly competitive industry is in long-run equilibrium. A permanent decrease in demand then reduces market price below each firm\'s ATC. Tracing the full long-run adjustment, which of the following correctly describes the new long-run equilibrium (assume a constant-cost industry)?',
        options: [
          'More firms, same price as before, lower total industry output',
          'Fewer firms, same price as before, lower total industry output',
          'Fewer firms, lower price than before, same total industry output',
          'Same number of firms, lower price, each firm produces less',
        ],
        correctAnswer: 1,
        explanation: 'When P falls below ATC, firms incur losses. In the long run, some firms exit, shifting supply left and raising price back to minimum ATC — the same price as the original equilibrium in a constant-cost industry. With fewer firms, total industry output is lower. Each remaining firm is back at its efficient scale (minimum ATC), earning zero economic profit.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-5',
        type: 'mcq',
        question: 'In an increasing-cost perfectly competitive industry, a permanent increase in demand leads to a long-run equilibrium with:',
        options: [
          'The same price as before, more firms, and greater total industry output',
          'A higher price than before, more firms, and greater total industry output',
          'A lower price than before, because new entrants bring economies of scale',
          'The same price as before, same number of firms, and the same total industry output',
        ],
        correctAnswer: 1,
        explanation: 'In an increasing-cost industry, industry expansion bids up the price of specialised inputs, raising the minimum ATC for all firms. New long-run equilibrium price is higher than the original — the upward-sloping long-run supply curve reflects this. More firms enter (compared to the original number) and total output rises, but equilibrium price is permanently higher than before the demand shock.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-6',
        type: 'mcq',
        question: 'Minimum efficient scale (MES) is best defined as:',
        options: [
          'The output level at which MC equals LRAC, minimising marginal cost',
          'The smallest output level at which LRAC reaches its minimum, exhausting all economies of scale',
          'The output level at which a firm first earns zero economic profit in the long run',
          'The point at which the short-run ATC curve first intersects the LRAC curve',
        ],
        correctAnswer: 1,
        explanation: 'MES is the lowest output at which the LRAC curve reaches its bottom — the scale beyond which no further average cost reductions are available from expanding output. It determines competitive viability: firms operating below MES have higher unit costs and are vulnerable to price competition from larger rivals. MES is about LRAC, not MC or short-run curves.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-7',
        type: 'mcq',
        question: 'A firm is currently producing on the downward-sloping portion of its LRAC curve. Which of the following actions would move the firm toward minimum efficient scale?',
        options: [
          'Reducing output and laying off workers to cut variable costs',
          'Expanding plant size and output to exploit remaining economies of scale',
          'Raising price to cover the current above-minimum average cost',
          'Exiting the industry, since the downward-sloping portion indicates losses',
        ],
        correctAnswer: 1,
        explanation: 'On the downward-sloping portion of LRAC, the firm has economies of scale — expanding output lowers average cost. Moving toward MES means increasing scale until LRAC reaches its minimum. Reducing output would move further from MES and raise average cost. The shape of LRAC says nothing directly about whether the firm is profitable — that depends on price relative to LRAC.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-8',
        type: 'mcq',
        question: 'At the long-run competitive equilibrium, each firm produces at minimum LRAC and earns zero economic profit. A student argues: "Zero profit means firms are losing money and will exit." This argument is:',
        options: [
          'Correct — zero profit is a loss and will trigger exit until only monopolists remain',
          'Incorrect — zero economic profit means all factors of production earn their opportunity cost, including a normal return on capital; there is no incentive to exit',
          'Correct — accounting profit is zero, so the firm cannot pay dividends to shareholders',
          'Incorrect — zero economic profit means the firm is subsidised by the government to stay open',
        ],
        correctAnswer: 1,
        explanation: 'Zero economic profit (normal profit) means total revenue covers all explicit and implicit costs, including the opportunity cost of the owner\'s capital and time. The firm earns exactly what it could earn in its next-best alternative use. There is no incentive to exit (or enter). This is different from accounting profit, which may be positive even when economic profit is zero.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-9',
        type: 'mcq',
        question: 'Which of the following best explains why the long-run supply curve of a constant-cost industry is perfectly elastic (horizontal)?',
        options: [
          'Individual firms face horizontal demand curves, so the industry curve must also be horizontal',
          'Input prices are unchanged as the industry expands, so each new entrant\'s minimum ATC equals that of existing firms — price always returns to the same level after any demand shift',
          'The government regulates prices in constant-cost industries to prevent inflation',
          'Fixed costs are zero in the long run, making the supply curve flat',
        ],
        correctAnswer: 1,
        explanation: 'In a constant-cost industry, expanding the number of firms does not drive up input prices. Every new entrant faces the same cost curves as existing firms, so minimum ATC is unchanged. After any demand shock, entry or exit returns price to the same minimum ATC — no matter how large or small the industry. This is the mechanism that produces a horizontal (perfectly elastic) long-run supply curve.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap1-l4-10',
        type: 'mcq',
        question: 'A firm operating at diseconomies of scale is on which part of the LRAC curve, and what should it do to reduce long-run average cost?',
        options: [
          'On the downward-sloping portion; it should expand output further',
          'On the upward-sloping portion; it should reduce scale (produce less) to return toward minimum LRAC',
          'At the minimum point; it is already at the lowest possible average cost',
          'On the downward-sloping portion; it should raise price to cover higher costs',
        ],
        correctAnswer: 1,
        explanation: 'Diseconomies of scale means LRAC is rising as output increases — the firm is on the upward-sloping portion of its LRAC curve. Average cost is above the minimum attainable level. To reduce LRAC, the firm should scale back: smaller plant, lower output. Management complexity and coordination failures that cause diseconomies of scale are reduced by operating at a more manageable size.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
    content: {
      isStub: false,
      conceptualExplanation: `In the long run, firms choose their scale of operation — the size of their plant and capital stock. For each possible plant size there is a corresponding short-run ATC curve. The long-run average cost (LRAC) curve is the lower envelope of all these short-run curves, tracing the minimum cost achievable at each output level when the firm can select any scale. Where LRAC declines with output, the firm enjoys economies of scale — typically driven by specialisation of labour, indivisible capital, and spreading fixed development costs. Where LRAC rises, diseconomies of scale set in, often from managerial complexity and communication failures in very large organisations.

Industry adjustment in the long run depends on cost conditions. In a constant-cost industry (input prices unaffected by industry size), an economic profit attracts entry, supply shifts right, price falls back to minimum ATC, and profits return to zero — the long-run supply curve is horizontal. In increasing-cost industries (entry bids up input prices), the new long-run equilibrium price is higher; in decreasing-cost industries (expansion lowers input costs through learning or supplier scale), it is lower. The AP exam tests whether students can trace this full adjustment — draw the short-run shift, identify where excess profit or loss exists, show the entry or exit, and arrive at the long-run equilibrium price and quantity.`,
      prerequisiteRecap: `Lesson 3 established the two critical price benchmarks — minimum AVC (shutdown point) and minimum ATC (break-even/exit point) — and explained why firms operating between those thresholds rationally tolerate short-run losses. Lesson 4 extends that logic to the industry level: when price persistently falls below minimum ATC, the exit decisions of individual firms aggregate into an industry-wide contraction, and the long-run cost structure of that industry determines where price ultimately settles.`,
      recallQuestions: [
        {
          id: 'ap1-l4-recall-1',
          type: 'mcq' as const,
          question: 'A competitive firm has minimum AVC = $9 and minimum ATC = $15. The market price is $11. Which of the following correctly states the firm\'s short-run and long-run strategies?',
          options: [
            'Shut down in the short run; exit in the long run if price stays at $11',
            'Produce in the short run (P > AVC); plan to exit in the long run if price stays at $11 (P < ATC)',
            'Produce in both the short run and the long run because P > AVC',
            'Exit immediately because the firm is earning an economic loss',
          ],
          correctAnswer: 1,
          explanation: 'P = $11 > min AVC = $9, so the firm covers variable costs and contributes $2 per unit toward fixed costs — producing minimises the short-run loss. But P = $11 < min ATC = $15, so the firm earns a loss. In the long run, when all costs are variable, the firm should exit if price remains at $11 because it cannot cover total economic cost.',
          marks: 1,
          difficulty: 'standard' as const,
        },
        {
          id: 'ap1-l4-recall-2',
          type: 'mcq' as const,
          question: 'At the short-run profit-maximising output, a competitive firm has P = $22, ATC = $22, and AVC = $16. Which statement is correct?',
          options: [
            'The firm earns zero economic profit and should exit in the long run',
            'The firm earns zero economic profit and is at the long-run break-even point — no incentive to exit',
            'The firm earns an economic loss because AVC is below ATC',
            'The firm should shut down because P equals ATC, not AVC',
          ],
          correctAnswer: 1,
          explanation: 'P = ATC = $22 means total revenue exactly covers total cost — the firm earns zero economic profit (normal profit). This is the break-even point. All costs, including the implicit opportunity cost of capital, are covered. There is no incentive to exit in the long run. AVC being below ATC is normal (ATC = AVC + AFC); it does not indicate a loss.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `The semiconductor fabrication industry offers a striking illustration of long-run cost dynamics. Building a cutting-edge chip fab (a TSMC or Intel facility) costs $20–30 billion and takes five years — an extreme case of indivisible capital that produces massive economies of scale. For a fab running at full capacity, average cost per chip drops dramatically as output spreads those fixed billions across hundreds of millions of chips. This is why the global foundry market has consolidated to just a handful of companies: the minimum efficient scale is enormous relative to total market demand. When a demand shock hits — as happened during the 2020–2022 semiconductor shortage driven by surging consumer electronics and automotive demand — even persistently high prices could not rapidly attract new entrants. The long-run adjustment that takes wheat farmers a single growing season takes chip foundries a decade. The industry adjustment mechanism is the same as in any competitive market; only the timeline differs.`,
      vocabulary: [
        {
          term: 'LRAC curve',
          definition: 'The Long-Run Average Cost curve is the lower envelope of all possible short-run ATC curves. It shows the minimum average cost achievable at every output level when the firm can freely choose its scale of operation (all inputs variable).',
          example: 'A brewery\'s LRAC curve falls steeply from small artisan batches to mid-sized regional production as fixed brewing equipment is spread over more barrels, then flattens out at industrial scale where all economies of scale are exhausted.',
        },
        {
          term: 'Economies of scale',
          definition: 'The cost advantage that arises when a firm increases all inputs and output grows proportionally more, causing LRAC to decline. Sources include labour specialisation, spreading of indivisible capital costs, bulk input purchasing, and learning-by-doing.',
          example: 'Amazon\'s fulfilment centres: doubling the number of packages processed less than doubles total cost because the same warehouse management system, sorting technology, and logistics network handle the additional volume at near-zero marginal infrastructure cost.',
        },
        {
          term: 'Minimum efficient scale',
          definition: 'The lowest output level at which LRAC reaches its minimum — the point where all economies of scale have been fully exploited. Firms operating below MES face higher per-unit costs than larger rivals and are competitively vulnerable.',
          example: 'Commercial aircraft manufacturing has extremely high MES. A new entrant producing 10 planes per year would face far higher per-unit costs than Boeing or Airbus producing hundreds annually — explaining why the global market supports only two major producers.',
        },
      ],
      examinerTip: `AP long-run adjustment FRQ questions almost always require a two-panel diagram: one panel showing the market (supply and demand with price and total quantity) and one panel showing the representative firm (price as a horizontal MR = D line, with MC, ATC, and the profit/loss area shaded). Practice drawing both panels side by side, showing the initial short-run equilibrium, the demand shock, the resulting profit or loss, the entry or exit arrow on the market panel, and the new long-run equilibrium where price = minimum ATC on the firm panel. Label every curve and every equilibrium point. Graders award separate points for correctly identifying the direction of entry/exit, the direction of the supply shift, and the final equilibrium conditions — do not skip any step.`,
      thinkAboutIt: {
        question: `Why does a constant-cost industry have a perfectly horizontal (perfectly elastic) long-run supply curve — even though every individual firm in that industry has an upward-sloping short-run supply curve?`,
        answer: `The key is to distinguish between what happens to an individual firm's costs and what happens to the industry's equilibrium price over time. An individual firm's short-run supply curve is upward-sloping because, in the short run, the firm moves up its MC curve to produce more — higher output means higher marginal cost. But the industry's long-run supply curve reflects a different mechanism: entry and exit of entire firms, not movement along a single firm's MC curve.

In a constant-cost industry, input prices do not change as the industry expands. This means every new entrant faces exactly the same cost curves as existing firms — the same minimum ATC. Whenever price rises above minimum ATC, profits attract new entrants. Those entrants keep arriving until price is driven back down to minimum ATC. Since minimum ATC is the same for every firm (inputs don't get more expensive), price always returns to the exact same level — not a higher or lower level. The industry can supply any quantity demanded at that constant price simply by adjusting the number of firms. That is precisely what a horizontal supply curve means: quantity adjusts, price stays fixed.`,
      },
    },
    lessonAssignment: {
      prompt: `A perfectly competitive industry is initially in long-run equilibrium. Consumer incomes then rise permanently, increasing market demand for the good. The industry is a constant-cost industry.\n\n(a) Using a correctly labelled two-panel diagram (market panel and representative firm panel), show the short-run effect of the demand increase on price, quantity, and the firm's profit situation.\n(b) Explain the long-run adjustment process that follows the short-run result. Identify what happens to the number of firms, market supply, and price.\n(c) Draw the new long-run equilibrium on your diagrams, showing the market and the representative firm.\n(d) On a separate diagram, draw the long-run supply curve for this constant-cost industry and explain in two sentences why it takes the shape it does.\n(e) How would your answer to parts (b) and (d) differ if the industry were an increasing-cost industry instead of a constant-cost industry?`,
      rubric: `Award points for:\n- (a) Market panel: rightward shift of demand, new short-run equilibrium at higher P and Q — 2 pts; Firm panel: higher price line above ATC, shaded economic profit rectangle — 2 pts\n- (b) Economic profit attracts new firms; supply shifts right; price falls back to minimum ATC; profit returns to zero; number of firms increases — 3 pts (1 pt each for: entry identified, supply shift rightward, price returning to original level)\n- (c) New long-run equilibrium shown correctly: market at higher total Q, same price as original; firm at same price = min ATC, zero profit — 2 pts\n- (d) Horizontal long-run supply curve drawn and correctly explained: constant input prices mean minimum ATC is unchanged for all entrants, so price always returns to the same level — 2 pts\n- (e) Increasing-cost: entry bids up input prices, minimum ATC rises for all firms, long-run equilibrium price is higher than original, long-run supply curve slopes upward — 2 pts (1 pt each for: higher equilibrium price identified, upward-sloping LRS curve)\n- Clear use of economic terminology and logical chain of reasoning throughout — 2 pts`,
      exampleTopics: [
        'Draw both panels side by side from the start — graders award points separately for the market diagram and the firm diagram',
        'In the firm panel, the short-run profit is a rectangle: its height is (P − ATC) and its width is Q* — shade it and label it "economic profit"',
        'The long-run adjustment story has a clear sequence: profit → entry → supply shifts right → price falls → profit disappears — write out each step explicitly',
        'For the increasing-cost comparison in part (e): the key difference is that input prices rise as more firms enter, so the new long-run equilibrium price is above the original — the long-run supply curve slopes upward rather than being horizontal',
      ],
    },
  },
]
