import type { CurriculumModule, Lesson } from '@/lib/types'

export const moduleInfo: Omit<CurriculumModule, 'lessons'> = {
  id: 'ap3-failures',
  title: 'AP Micro — Market Failures and Government',
  description: 'Cover every externality, public goods, and regulation question the AP exam uses.',
  tier: 'AP' as const,
  track: 'AP' as const,
  unit: 3,
  estimatedHours: 2,
  color: '#f59e0b',
  icon: 'Target',
}

export const lessons: Lesson[] = [
  {
    id: 'ap3-l1',
    moduleId: 'ap3-failures',
    title: 'Externalities — Welfare Analysis and Policy',
    description: 'Calculate the socially optimal output, the size of the externality, the Pigouvian tax/subsidy, and DWL.',
    order: 1,
    estimatedMinutes: 40,
    tags: ['externalities', 'Pigouvian-tax', 'welfare'],
    flashcards: [
      {
        id: 'fc-ap3-l1-1',
        front: 'What is a negative externality, and how does it distort the market outcome?',
        back: 'A cost imposed on third parties not reflected in the market price. MPC < MSC (marginal social cost includes the external cost), so the market overproduces relative to the social optimum. Corrected by a Pigouvian tax equal to the marginal external cost at the social optimum quantity.',
        tags: ['externalities', 'Pigouvian-tax'],
      },
      {
        id: 'fc-ap3-l1-2',
        front: 'What is a positive externality, and what policy corrects the market failure?',
        back: 'A benefit conferred on third parties not reflected in market demand. MPB < MSB (marginal social benefit exceeds private benefit), so the market underproduces. Corrected by a Pigouvian subsidy that raises effective demand to the social optimum.',
        tags: ['externalities', 'welfare'],
      },
      {
        id: 'fc-ap3-l1-3',
        front: 'What does the Coase Theorem state about externalities?',
        back: 'When property rights are well-defined and transaction costs are low, private bargaining between the affected parties will internalise externalities and reach the socially efficient outcome, regardless of the initial assignment of the property right.',
        tags: ['externalities', 'welfare'],
      },
      {
        id: 'fc-ap3-l1-4',
        front: 'How is deadweight loss from a negative externality identified on a supply-demand diagram?',
        back: 'DWL is the triangle bounded by the MSC curve above, the demand (MPB) curve below, and the vertical distance between the market quantity and the social optimum quantity. It represents units where social cost exceeds social benefit that are nonetheless produced. The area shrinks to zero when a correctly calibrated Pigouvian tax shifts output to the social optimum.',
        tags: ['externalities', 'welfare'],
      },
      {
        id: 'fc-ap3-l1-5',
        front: 'How does a cap-and-trade permit system correct a negative externality?',
        back: 'The government sets a total emissions cap and distributes or auctions permits equal to that cap. Firms that can reduce emissions cheaply do so and sell surplus permits; high-abatement-cost firms buy permits instead. Trading ensures that abatement occurs where it is cheapest, achieving the quantity target at minimum aggregate cost — a cost-effective alternative to a uniform Pigouvian tax when individual marginal costs of abatement differ.',
        tags: ['externalities', 'Pigouvian-tax'],
      },
      {
        id: 'fc-ap3-l1-6',
        front: 'What is the difference between a production externality and a consumption externality?',
        back: 'A production externality originates in the production process — e.g., factory smoke polluting a river (negative) or a beekeeper whose hives pollinate a neighbouring farm (positive). A consumption externality stems from the use of the good — e.g., second-hand cigarette smoke (negative) or vaccination creating herd immunity for others (positive). Both types shift MSC or MSB away from MPC or MPB, but the policy response may differ in where the tax or subsidy is applied.',
        tags: ['externalities', 'welfare'],
      },
      {
        id: 'fc-ap3-l1-7',
        front: 'Why might command-and-control regulation be less efficient than a Pigouvian tax?',
        back: 'Command-and-control rules (e.g., a uniform emission standard for every firm) ignore differences in abatement costs across producers. A Pigouvian tax allows each firm to choose how much to reduce emissions based on its own marginal abatement cost, concentrating reduction where it is cheapest. The tax also generates revenue the government can use productively, while quantity mandates do not. However, taxes require accurate knowledge of the marginal external cost — a significant informational challenge.',
        tags: ['externalities', 'Pigouvian-tax'],
      },
    ],
    quiz: [
      {
        id: 'q-ap3-l1-1',
        type: 'mcq',
        question: 'The optimal Pigouvian tax on a negative externality equals:',
        options: [
          'The total external cost summed across all units of output',
          'The marginal external cost at the socially optimal quantity',
          'The market price of the good at the competitive equilibrium',
          'The difference between MPC and ATC at the profit-maximising output',
        ],
        correctAnswer: 1,
        explanation: 'The Pigouvian tax is set equal to the marginal external cost (MEC) evaluated at the social optimum quantity — not the market quantity. This shifts the MPC curve upward by exactly MEC, making private and social costs equal at the optimal output. Setting the tax at the market quantity would over-correct, pushing output too far below optimum.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-2',
        type: 'mcq',
        question: 'A steel producer emits pollution that imposes external costs on nearby residents. Compared to the socially optimal output, the free market:',
        options: [
          'Underproduces steel because the pollution raises production costs for the firm',
          'Overproduces steel because MPC < MSC, so the market price is too low and quantity is too high',
          'Produces the efficient quantity because competition drives price equal to marginal cost',
          'Underproduces steel because consumers discount the price of goods associated with pollution',
        ],
        correctAnswer: 1,
        explanation: 'Pollution is a negative production externality. The firm does not bear the full social cost (MPC < MSC = MPC + MEC), so the market price is lower than the socially optimal price and quantity produced exceeds the social optimum. The deadweight loss is the triangle between MSC and demand, from the social optimum to the market quantity.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-3',
        type: 'mcq',
        question: 'A vaccine against influenza confers immunity benefits on non-vaccinated individuals, generating a positive externality. Compared with the social optimum, the free market for vaccines will:',
        options: [
          'Overproduce vaccines because producers capture the full social benefit through the market price',
          'Produce the efficient quantity because demand reflects all social benefits',
          'Underproduce vaccines because MPB < MSB, so the market price and quantity are below the social optimum',
          'Overproduce vaccines because the government subsidises vaccination programmes',
        ],
        correctAnswer: 2,
        explanation: 'Positive externalities mean MSB > MPB — some benefits accrue to people who do not pay for the vaccine (herd immunity). The market price only reflects private benefit, so demand is too low relative to the social optimum, causing underproduction. A Pigouvian subsidy equal to the marginal external benefit at the social optimum quantity would correct this. Options A and B are wrong because the market price does not capture spill-over benefits; option D describes a policy intervention, not the free-market outcome.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-4',
        type: 'mcq',
        question: 'The Coase Theorem predicts private bargaining will achieve an efficient outcome provided that:',
        options: [
          'The government assigns all property rights to the polluting firm',
          'Transaction costs are negligible and property rights are clearly defined',
          'The number of affected parties is large enough to deter free-riding',
          'The externality generates deadweight loss exceeding the cost of negotiation',
        ],
        correctAnswer: 1,
        explanation: 'Coase argued that efficiency does not depend on who holds the property right — only that someone does and that the parties can bargain costlessly. With low transaction costs and clear rights, the injured party can pay the polluter to reduce emissions, or the polluter can be required to compensate the harmed party; either way the socially efficient level of the activity emerges. The theorem breaks down in reality with many affected parties (high transaction costs, free-riding in coalition formation).',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-5',
        type: 'mcq',
        question: 'A government imposes a per-unit tax on a good that generates a negative externality. Which of the following correctly describes the impact on deadweight loss?',
        options: [
          'DWL increases because the tax drives a wedge between the price producers receive and consumers pay',
          'DWL decreases toward zero as the tax shifts production toward the social optimum',
          'DWL is unaffected because the tax transfers income from producers to the government',
          'DWL increases because consumers bear the full burden of the tax through higher prices',
        ],
        correctAnswer: 1,
        explanation: 'Before the tax, the market produces in excess of the social optimum — every unit beyond the optimum has social cost exceeding social benefit, creating DWL. A correctly calibrated Pigouvian tax shifts the firm\'s effective marginal cost curve up to MSC, moving output toward the social optimum and eliminating the DWL triangle. The tax does create a wedge between buyer and seller prices, but this wedge corrects the externality rather than introducing a new distortion.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-6',
        type: 'mcq',
        question: 'In a cap-and-trade system for carbon emissions, which outcome is most consistent with economic efficiency?',
        options: [
          'Each firm is required to reduce emissions by the same percentage, regardless of abatement cost',
          'The government sets an emissions price equal to the average abatement cost across all firms',
          'Firms with low abatement costs reduce emissions and sell permits to high-abatement-cost firms',
          'The total number of permits expands each year to accommodate economic growth',
        ],
        correctAnswer: 2,
        explanation: 'Efficiency requires that abatement occur where it is cheapest. Permit trading allows low-cost reducers to cut more than required and sell permits, while high-cost firms buy permits and reduce less. This equalises marginal abatement costs across firms, achieving the total emissions target at minimum aggregate cost. Uniform percentage cuts (A) ignore cost differences and waste resources. A price set at average cost (B) is not cost-minimising. Expanding permits (D) undermines the environmental cap.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-7',
        type: 'mcq',
        question: 'At the market equilibrium with a negative production externality, the area of deadweight loss is best described as:',
        options: [
          'The rectangle between MPC and MSC over all units produced at the market quantity',
          'The triangle between MSC and the demand curve from the social optimum to the market quantity',
          'The area under the demand curve up to the market quantity',
          'The producer surplus transferred to the government through a Pigouvian tax',
        ],
        correctAnswer: 1,
        explanation: 'DWL is the triangle bounded by MSC above, the demand (MPB) curve below, from the social optimum quantity to the market quantity. For each of these excess units, MSC > MPB — social cost exceeds social benefit — yet the market produces them anyway. The area is a triangle because MSC and demand are linear and they converge at the social optimum. Option A describes a rectangle, not a triangle, and misidentifies the bounds. Option D describes tax revenue, not DWL.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-8',
        type: 'mcq',
        question: 'A pharmaceutical company discovers a new drug whose production process generates significant water pollution. An economist recommends a Pigouvian tax rather than a uniform emission standard. The main economic justification for this recommendation is that:',
        options: [
          'Taxes always generate more government revenue than equivalent quantity controls',
          'A tax allows the firm flexibility to reduce pollution where marginal abatement cost is lowest, achieving the efficiency target at minimum total cost',
          'The tax eliminates all pollution, while an emission standard permits some pollution to continue',
          'A tax is easier to administer than an emission standard because it requires no monitoring of actual emissions',
        ],
        correctAnswer: 1,
        explanation: 'The core efficiency advantage of a price instrument (tax) over a quantity instrument (uniform standard) is cost-effectiveness: the firm responds by abating pollution up to the point where its marginal abatement cost equals the tax rate, concentrating reduction where it is cheapest. A uniform standard ignores the firm\'s cost structure. Option A is not always true — revenues depend on design. Option C is wrong: a Pigouvian tax does not eliminate all pollution, only units whose social cost exceeds benefit. Option D is often false — tax compliance still requires emission measurement.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-9',
        type: 'mcq',
        question: 'If the government sets a Pigouvian tax below the true marginal external cost at the social optimum, what is the likely outcome?',
        options: [
          'The market will overshoot the social optimum and produce too little output',
          'The market will still produce more than the social optimum — DWL is reduced but not eliminated',
          'Producers will earn positive economic profit equal to the tax shortfall',
          'The externality is fully internalised because any positive tax shifts the MPC curve upward',
        ],
        correctAnswer: 1,
        explanation: 'A tax below the true MEC shifts MPC upward, but not far enough — the new equilibrium remains to the right of the social optimum. Output is reduced from the unregulated level, so DWL shrinks, but units are still produced where MSC > MPB, meaning DWL is not eliminated. Only a tax exactly equal to MEC at the social optimum achieves first-best efficiency. Option A describes an over-corrective tax. Option D is incorrect: the size of the shift matters, not merely its direction.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l1-10',
        type: 'mcq',
        question: 'Which of the following best explains why the Coase Theorem is often considered impractical for large-scale environmental problems such as ocean acidification?',
        options: [
          'The Coase Theorem applies only to positive externalities, not negative ones',
          'Ocean acidification does not constitute an externality because it affects no individual property owner',
          'The large number of affected parties and diffuse nature of the harm make transaction costs prohibitively high, preventing efficient bargaining',
          'Coasian bargaining requires government enforcement, which is unavailable in international contexts',
        ],
        correctAnswer: 2,
        explanation: 'Coase assumed negligible transaction costs — feasible when two or a few identifiable parties can negotiate directly. For global commons problems like ocean acidification, millions of emitters affect billions of people across many countries. Organising affected parties, verifying harm, and enforcing any agreement entails enormous costs. The free-rider problem within any coalition of harmed parties further undermines collective action. Options A and B misstate the theorem\'s scope. Option D conflates transaction costs (the real barrier) with enforcement issues, though enforcement is a related but separate problem.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
    content: {
      isStub: false,
      realWorldHook: `In 2009, the Obama administration estimated the "social cost of carbon" at $21 per metric tonne — essentially the marginal external cost of each additional tonne of CO2 emitted into the atmosphere. By 2021, the Biden administration revised that figure upward to $51, and some economists argued the true number exceeded $100. This single estimate determined the size of the Pigouvian tax that the U.S. implicitly placed on carbon through regulations. When the number is set too low, industry underprices fossil fuels, emits more than is socially optimal, and the climate bears the uncompensated cost. The battle over the social cost of carbon is not merely academic: every $10 change in the estimate shifts billions of dollars of compliance costs across the energy sector. It is, in real terms, the world's most consequential application of the externality diagram you are about to learn.`,
      conceptualExplanation: `Externalities arise when a market transaction affects parties outside the transaction, and the external effect is not priced. In a market with a negative production externality (e.g., air pollution from a factory), the producer's marginal private cost (MPC) lies below the marginal social cost (MSC = MPC + marginal external cost). The market equates MPC with demand, producing more than the socially optimal quantity where MSC intersects demand. The deadweight loss is the triangle between the MSC and demand curves from the social optimum quantity to the market quantity — units where social cost exceeds social benefit but are produced anyway.

Correction tools include Pigouvian taxes (shifting MPC up to MSC, directing quantity to the social optimum), cap-and-trade permit markets (setting a quantity ceiling and letting firms trade permits to achieve the cheapest abatement), and Coasian bargaining (private negotiation when transaction costs are low). For positive externalities — where MSB exceeds MPB — the market underproduces, and Pigouvian subsidies or public provision raise output toward the optimum. AP students must be able to draw the four-curve diagram (MPC, MSC, MPB/D, and MSB where applicable), identify the market equilibrium and the social optimum, shade the deadweight loss triangle, and specify the Pigouvian tax or subsidy amount — reading it as the vertical gap between MSC and MPC at the social optimum.`,
      prerequisiteRecap: `AP Module 2 completed the survey of market structures and showed that in factor markets firms hire where MRP = Wage. Market failures covered in this module arise when prices fail to reflect full social costs or benefits — a different breakdown from the structural distortions (monopoly power, strategic interaction) examined in Module 2.`,
      vocabulary: [
        {
          term: 'Marginal External Cost (MEC)',
          definition: 'The additional cost imposed on third parties — not borne by the producer or consumer — from producing one more unit of a good. It is the vertical gap between MSC and MPC at any given output level.',
          example: 'A coal plant burning one additional tonne of coal imposes approximately $50 in health and climate damages on society; that $50 is the MEC of that unit of coal.',
        },
        {
          term: 'Pigouvian Tax',
          definition: 'A per-unit tax set equal to the marginal external cost at the socially optimal quantity, designed to force producers to internalise the externality and equate MPC with MSC.',
          example: 'A carbon tax of $51 per tonne of CO2 is a Pigouvian tax if the marginal external cost of carbon at the efficient emissions level is $51 per tonne.',
        },
        {
          term: 'Deadweight Loss (DWL)',
          definition: 'The reduction in total social surplus caused by a market failure or policy distortion. For a negative externality it is the triangular area between MSC and demand (MPB) over the range of output that exceeds the social optimum.',
          example: 'If the efficient output is 80 units but the market produces 100, the DWL triangle spans from unit 80 to unit 100 — every one of those 20 extra units inflicts social cost exceeding its social benefit.',
        },
      ],
      examinerTip: `On AP FRQ diagrams, always label four elements: the MPC curve (or S curve), the MSC curve above it, the demand/MPB curve, the social optimum (Q*) and the market equilibrium (Qm). Shade the DWL triangle between MSC and demand from Q* to Qm. For the Pigouvian tax, draw a vertical arrow between MPC and MSC at Q* and label it "tax = MEC." Examiners award partial credit for correctly labelled axes and curves even if your DWL triangle is imperfect — never leave a diagram blank. For subsidy questions (positive externalities), draw MSB above demand and shade DWL between demand and MSB from Qm to Q*.`,
      recallQuestions: [
        {
          id: 'ap3-l1-recall-1',
          type: 'mcq' as const,
          question: 'A monopsonist hires fewer workers at a lower wage than a competitive labour market would. What is the direct cause of this under-hiring?',
          options: [
            'The monopsonist\'s marginal factor cost (MFC) exceeds the wage at every employment level, so hiring the MRP = MFC quantity is below the competitive level',
            'The monopsonist sets the wage above the competitive level, discouraging workers from entering the labour market',
            'The monopsonist faces a downward-sloping labour supply curve, reducing the number of available workers',
            'The monopsonist hires until MRP equals the wage, which coincides with the competitive equilibrium',
          ],
          correctAnswer: 0,
          explanation: 'A monopsonist faces an upward-sloping labour supply, so hiring an extra worker requires paying all existing workers more — making MFC > wage. The profit-maximising condition MRP = MFC produces a hiring level below the competitive outcome (where MRP = wage). The wage is then read off the supply curve at that lower employment, giving both lower employment and a lower wage than competition would produce.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      thinkAboutIt: {
        question: 'If a government introduces a carbon tax but sets it at half the true marginal external cost, is the policy worth doing at all? Could it make things worse?',
        answer: 'A tax set at half the true MEC still moves the market in the right direction — it shifts MPC upward, reduces output from the unregulated equilibrium, and shrinks (though does not eliminate) the deadweight loss triangle. It is almost certainly worth doing: even partial internalisation of external costs improves welfare relative to no tax. The policy cannot make things worse in a simple one-market model because any positive tax reduces overproduction of the externality-generating good.\n\nHowever, second-best complications can arise. If the carbon tax raises costs in one energy sector but not substitutes, it may shift production toward other polluting sources — the "carbon leakage" problem. If the revenue is used inefficiently or redistributed in ways that cause distortions elsewhere in the economy, the net welfare gain shrinks. And politically, a low tax can crowd out advocacy for a correct-sized tax by creating the appearance that the problem is "solved." So while the economics of a partial Pigouvian tax are generally positive, the practical and political economy considerations are real concerns AP economists should acknowledge.',
      },
    },
    lessonAssignment: {
      prompt: 'A city government is considering two policies to reduce traffic congestion, which imposes time costs on all drivers (a negative externality): (A) a $5 per-trip congestion charge on vehicles entering the downtown core during peak hours, or (B) a regulation banning all personal vehicles from the downtown core between 7 a.m. and 9 a.m. Using the concepts of externalities, Pigouvian taxation, deadweight loss, and cost-effectiveness, evaluate both policies and recommend one, supporting your recommendation with economic reasoning.',
      rubric: `Award up to 10 points as follows:
1. Externality identification (2 pts): Correctly identifies traffic congestion as a negative consumption externality (1 pt); explains that MPC of driving < MSC because time costs imposed on other drivers are not borne by the individual driver (1 pt).
2. Pigouvian tax analysis (3 pts): Explains that the congestion charge functions as a Pigouvian tax (1 pt); argues it should equal MEC at the social optimum number of trips (1 pt); describes how it shifts drivers' effective marginal cost upward toward MSC, reducing trips to the efficient level (1 pt).
3. Command-and-control analysis (2 pts): Explains that the ban is a quantity restriction — analogous to setting Q = 0 for peak-hour personal vehicles (1 pt); notes it ignores variation in individual trip values, potentially excluding high-value trips while allowing zero-value trips at other times (1 pt).
4. Cost-effectiveness comparison (2 pts): Argues the congestion charge is more economically efficient because it allows drivers who value trips most highly to continue driving while deterring low-value trips (1 pt); notes the charge generates revenue that can fund public transit or other interventions, while a ban generates no revenue (1 pt).
5. Recommendation and caveats (1 pt): Provides a clear recommendation with at least one caveat (e.g., equity concerns — the charge may disproportionately burden lower-income commuters; or practical concerns — the ban may be easier to enforce).`,
      exampleTopics: [
        'Draw the externality diagram showing MPC, MSC, demand, market equilibrium, social optimum, and DWL before the policy — this earns partial credit even if your written analysis is incomplete.',
        'Consider who bears the external cost of congestion: other drivers lose time, so the externality is imposed within the market itself — be precise about this in your explanation.',
        'Compare the two policies on cost-effectiveness: a Pigouvian charge lets drivers self-sort by trip value, while a flat ban treats all peak-hour trips as equally undesirable — explain why this matters for efficiency.',
        'Address one equity concern: congestion charges are regressive (a $5 charge is a bigger share of income for a low-wage worker). What complementary policy might address this without sacrificing efficiency?',
      ],
    },
  },
  {
    id: 'ap3-l2',
    moduleId: 'ap3-failures',
    title: 'Public Goods and Asymmetric Information',
    description: 'Distinguish public goods, common resources, club goods; introduce adverse selection and moral hazard.',
    order: 2,
    estimatedMinutes: 30,
    tags: ['public-goods', 'asymmetric-information'],
    flashcards: [
      {
        id: 'fc-ap3-l2-1',
        front: 'What two properties define a public good, and what problem do they cause?',
        back: 'Non-rival: one person\'s consumption does not reduce availability for others. Non-excludable: impossible or prohibitively costly to prevent non-payers from consuming. Together they cause the free-rider problem — private markets underprovide or do not provide public goods at all.',
        tags: ['public-goods'],
      },
      {
        id: 'fc-ap3-l2-2',
        front: 'What is adverse selection, and give an example?',
        back: 'A pre-contractual problem where one party has hidden information about their type, causing the uninformed party to attract a disproportionate share of high-risk counterparties. Example: in health insurance markets, sicker individuals are more likely to seek coverage, raising average costs and premiums in a potential "death spiral."',
        tags: ['asymmetric-information'],
      },
      {
        id: 'fc-ap3-l2-3',
        front: 'What is moral hazard, and how does it differ from adverse selection?',
        back: 'Moral hazard is a post-contractual change in behaviour when one party bears less than the full cost of their actions. Example: a driver takes more risks after purchasing comprehensive insurance. Unlike adverse selection (hidden type before contracting), moral hazard involves hidden actions after contracting.',
        tags: ['asymmetric-information'],
      },
      {
        id: 'fc-ap3-l2-4',
        front: 'How do common resources differ from public goods, and what problem do common resources face?',
        back: 'Common resources are non-excludable (like public goods) but rival — one person\'s use reduces availability for others. Examples include ocean fisheries and public grazing land. The rivalry without excludability creates the "tragedy of the commons": each individual over-exploits the resource because they bear only a fraction of the social cost of their use, leading to depletion. Solutions include privatisation, government quotas, or community governance (Ostrom\'s work).',
        tags: ['public-goods'],
      },
      {
        id: 'fc-ap3-l2-5',
        front: 'What is signalling in the context of information asymmetry, and what makes a signal credible?',
        back: 'Signalling is an action taken by the informed party to communicate hidden information to the uninformed party. A signal is credible (a separating equilibrium) only if it is costly enough that low-quality types cannot profitably mimic it. Example: a university degree signals worker ability — it is credible because it is sufficiently costly in time and money that low-ability workers find it unprofitable to obtain.',
        tags: ['asymmetric-information'],
      },
      {
        id: 'fc-ap3-l2-6',
        front: 'What is Akerlof\'s "market for lemons" result, and what does it show about adverse selection?',
        back: 'Akerlof (1970) showed that in used-car markets, sellers know quality but buyers do not. Buyers discount all cars to expected average quality. High-quality sellers exit because they cannot obtain full value. Average quality falls, so the price buyers will pay falls, and more sellers exit — a potential "unravelling" of the market. It demonstrates that information asymmetry alone can cause markets to collapse or allocate goods very inefficiently even without externalities or public goods.',
        tags: ['asymmetric-information'],
      },
      {
        id: 'fc-ap3-l2-7',
        front: 'What policy tools address the free-rider problem in public goods provision?',
        back: 'The main tool is government provision financed by compulsory taxation, which eliminates free-riding by making contribution mandatory. Alternatives include: direct regulation mandating participation (e.g., compulsory vaccination), subsidies to private producers, and Lindahl pricing (charging each consumer their marginal willingness to pay — theoretically efficient but requires truthful preference revelation). The challenge is determining the socially optimal quantity of the public good when willingness to pay is difficult to elicit honestly.',
        tags: ['public-goods'],
      },
    ],
    quiz: [
      {
        id: 'q-ap3-l2-1',
        type: 'mcq',
        question: 'National defence is classified as a public good because it is:',
        options: [
          'Provided by the government and funded through compulsory taxation',
          'Non-rival and non-excludable — one citizen\'s protection does not reduce others\', and non-payers cannot be excluded',
          'Free at the point of use and owned collectively by all citizens',
          'Underprovided by the private sector due to high fixed costs and natural monopoly characteristics',
        ],
        correctAnswer: 1,
        explanation: "National defence is non-rival (protecting one citizen doesn't reduce protection for others) and non-excludable (it is technically impossible to deny protection to any resident). These two properties, not government provision per se, define a public good. Government provision is the response to the resulting free-rider problem, not the definition.",
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-2',
        type: 'mcq',
        question: 'A homeowner invests less in fire-prevention measures after purchasing comprehensive fire insurance. This is an example of:',
        options: [
          'Adverse selection — the homeowner revealed private information about fire risk by purchasing insurance',
          'Moral hazard — a post-contractual change in behaviour because the homeowner bears less of the financial risk of fire',
          'The Coase Theorem — the insurer and homeowner could bargain to reach the efficient level of fire prevention',
          'A positive externality — fire prevention benefits neighbours, so the homeowner under-invests without insurance',
        ],
        correctAnswer: 1,
        explanation: 'Moral hazard is a post-contractual hidden-action problem: after purchasing insurance, the homeowner changes behaviour because they bear less financial risk. This is distinct from adverse selection, which occurs before a contract is signed when high-risk individuals disproportionately self-select into insurance pools.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-3',
        type: 'mcq',
        question: 'A public swimming pool charges admission but becomes less enjoyable as more swimmers use it simultaneously. How is this good classified?',
        options: [
          'A public good — it is open to the public and provided by the government',
          'A common resource — it is rival because congestion reduces enjoyment, and non-excludable because admission cannot be charged',
          'A club good — it is excludable (admission is charged) but rival once congested',
          'A private good — it is both excludable and non-rival at all usage levels',
        ],
        correctAnswer: 2,
        explanation: 'A club good is excludable (you must pay admission) but becomes rival once congestion sets in — each additional swimmer reduces the experience for others. This is the defining characteristic of club goods. It is not a public good (which is non-excludable); not a common resource (which is non-excludable); not a pure private good (rivalry only emerges with congestion, not at low usage).',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-4',
        type: 'mcq',
        question: 'In Akerlof\'s market for lemons, why do sellers of high-quality used cars exit the market?',
        options: [
          'High-quality car sellers are subject to stricter regulations that raise their selling costs',
          'Buyers, unable to distinguish quality, offer only the average-quality price — below what high-quality sellers need to cover their opportunity cost',
          'High-quality sellers prefer to keep their cars because they have higher personal utility from ownership',
          'The government imposes price ceilings that prevent high-quality sellers from charging a premium',
        ],
        correctAnswer: 1,
        explanation: 'Information asymmetry means buyers cannot verify quality before purchase, so they price all cars at expected average value. High-quality sellers receive less than their car is worth and exit. This lowers the average quality of cars on the market, causing the price buyers will pay to fall further — a potential unravelling. This is the core adverse selection mechanism. Options C and D introduce factors not in Akerlof\'s model.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-5',
        type: 'mcq',
        question: 'Which policy is best designed to mitigate moral hazard in health insurance?',
        options: [
          'Mandatory disclosure of pre-existing conditions to insurers before policy issuance',
          'A community rating requirement that charges all customers the same premium regardless of risk',
          'Deductibles and co-payments that require insured patients to bear part of the cost of medical care',
          'Government provision of health insurance funded through general taxation',
        ],
        correctAnswer: 2,
        explanation: 'Deductibles and co-payments reintroduce financial consequences for the insured\'s health-related decisions, reducing the moral hazard of over-consuming medical care. Option A addresses adverse selection (screening pre-existing conditions), not moral hazard. Community rating (B) reduces adverse selection discrimination but does nothing to align incentives post-contract. Government provision (D) does not inherently reduce moral hazard — it may worsen it if cost-sharing is eliminated.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-6',
        type: 'mcq',
        question: 'Ocean fisheries are often over-fished by competing fishing fleets. The most direct cause of over-fishing is that:',
        options: [
          'Fish are a public good — non-rival and non-excludable — so private firms cannot profit from fishing',
          'Fish are a common resource — rival but non-excludable — so each fleet ignores the cost it imposes on others, leading to over-exploitation',
          'Fishing companies collude to maximise joint profit, which involves catching more than the social optimum',
          'Government subsidies to fishing fleets reduce the private cost of fishing below the social optimum cost',
        ],
        correctAnswer: 1,
        explanation: 'Fish are a common resource: each fish caught by one fleet is unavailable to others (rival), but no fleet can be excluded from fishing in international waters (non-excludable). Each fleet bears only its private cost but not the cost it imposes on future catches for all fleets — a negative externality among users. This is the tragedy of the commons. Fish are not non-rival (option A is wrong). Collusion (C) typically reduces output. Subsidies (D) are a separate market distortion, not the primary cause of the commons problem.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-7',
        type: 'mcq',
        question: 'A university requires all students to contribute to a campus sustainability fund, even those who personally disagree with the fund\'s activities. This policy is best justified as:',
        options: [
          'Correcting a positive externality — sustainability investments benefit students who do not pay for them',
          'Solving the free-rider problem inherent in club goods by making membership compulsory',
          'Solving the free-rider problem by making contribution to a public good compulsory so non-contributors cannot avoid paying',
          'Correcting adverse selection — students who care about sustainability would otherwise pay more than students who do not',
        ],
        correctAnswer: 2,
        explanation: 'Campus sustainability improvements are non-rival and non-excludable among students — a public good within the campus community. Without compulsory contributions, students would free-ride (benefit without paying), leading to underprovision. Mandatory contributions solve this by eliminating the ability to free-ride. Option A is partly right in spirit (positive externalities) but imprecise — the correct framing is public goods and free-riding. Option B misidentifies sustainability as a club good. Option D confuses the situation with adverse selection.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-8',
        type: 'mcq',
        question: 'An employer offers two health insurance plans: Plan A has high premiums but no deductible; Plan B has low premiums but a $2,000 deductible. Employees with chronic illnesses disproportionately choose Plan A. This is an example of:',
        options: [
          'Moral hazard — chronically ill employees will over-use Plan A because they pay no deductible',
          'Adverse selection — employees self-select into plans based on hidden information about their own health, causing Plan A to attract high-cost individuals',
          'Signalling — chronically ill employees signal their health status to the insurer by choosing Plan A',
          'A Pigouvian subsidy — the employer subsidises Plan A to encourage health-seeking behaviour',
        ],
        correctAnswer: 1,
        explanation: 'Adverse selection is a pre-contractual hidden-information problem: employees know their own health status but the insurer does not. Chronically ill individuals rationally choose Plan A (no deductible) because they expect to use many services — the plan\'s terms attract high-cost users. This worsens the risk pool for Plan A, potentially raising premiums further and accelerating self-selection of sicker patients. This is distinct from moral hazard, which concerns post-contractual behaviour changes — though both may be present simultaneously.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-9',
        type: 'mcq',
        question: 'A firm offers a warranty on its products to communicate product quality to consumers. For the warranty to function as an effective signal, it must be the case that:',
        options: [
          'The warranty is offered freely, so even low-quality producers can use it without cost',
          'Government regulations require all firms in the industry to offer equivalent warranties',
          'The cost of honouring the warranty is low for high-quality producers but prohibitively high for low-quality producers',
          'Consumers cannot observe product quality even after purchasing, eliminating the need for post-purchase signals',
        ],
        correctAnswer: 2,
        explanation: 'For a signal to separate high-quality from low-quality types (a separating equilibrium), it must be costly enough that low-quality producers cannot profitably imitate it. A warranty is inexpensive for a firm whose products rarely break (high quality) but very expensive for a firm whose products break frequently (low quality). This cost asymmetry makes the warranty a credible signal. If all firms could offer the same warranty cheaply (A) or must do so by regulation (B), the signal conveys no information about quality.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l2-10',
        type: 'mcq',
        question: 'Which of the following is the most accurate distinction between a public good and a positive externality?',
        options: [
          'Public goods are provided by governments; positive externalities arise only from private transactions',
          'A positive externality is a spill-over benefit from a transaction; a public good is a specific category of good that is both non-rival and non-excludable, so the positive spill-over extends to everyone simultaneously',
          'Positive externalities cause underproduction; public goods always cause overproduction because non-rivalry means zero marginal cost',
          'There is no meaningful distinction — every public good is simply an extreme positive externality',
        ],
        correctAnswer: 1,
        explanation: 'A positive externality is a benefit conferred on a third party from a private transaction — it could affect a few neighbours or a whole city. A public good is defined by non-rivalry and non-excludability, meaning the benefit is simultaneously available to all and cannot be withheld from non-payers. Public goods can be thought of as an extreme form of positive externality (benefits spill over to everyone), but the classification matters for policy: positive externalities are corrected by subsidies; public goods require government provision or compulsory finance because voluntary markets collapse entirely.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
    content: {
      isStub: false,
      realWorldHook: `In 1970, economist George Akerlof published "The Market for Lemons" in the Quarterly Journal of Economics — a paper initially rejected by three top journals as "too trivial." The paper eventually won the Nobel Prize. Akerlof showed that a single fact — sellers of used cars know more about quality than buyers — could cause markets to collapse. By 2008, the same logic was applied to mortgage-backed securities: banks knew more about the quality of the loans they packaged than the investors who bought them. Adverse selection contributed to the worst financial crisis since the Great Depression. Information asymmetry is not a footnote to market theory; it is a first-order cause of real-world catastrophes. This lesson explains how hidden information and free-rider problems systematically prevent markets from achieving efficiency, and what governments and institutions do to fight back.`,
      conceptualExplanation: `Public goods represent a specific category of market failure defined by two joint properties: non-rivalry (my consumption does not diminish yours — one more person watching a fireworks display costs nothing extra) and non-excludability (once provided, it is impossible or prohibitively expensive to exclude non-payers). Because non-payers can free-ride on others' contributions, private markets underprovide public goods or fail to provide them at all. Government provision funded by taxation solves the free-rider problem, though determining the optimal quantity requires estimating aggregate willingness to pay — notoriously difficult because individuals have incentives to understate their true preferences when they know provision is not contingent on their reported valuation.

Asymmetric information distorts markets in distinct ways depending on whether the information gap is pre- or post-contractual. Adverse selection occurs before a contract is signed: the less-informed party attracts a disproportionate share of high-risk counterparties. In Akerlof's "market for lemons," sellers know car quality but buyers do not; buyers discount all cars to expected average quality; sellers of high-quality cars withdraw, lowering average quality further. Solutions include signalling (sellers credibly signal quality through warranties) and screening (buyers design contracts to extract information). Moral hazard occurs after contracting when insured parties take greater risks because costs are partly borne by others — mitigated through deductibles, co-payments, and monitoring. Both problems illustrate why information is as important as prices in determining whether markets allocate resources efficiently.`,
      prerequisiteRecap: `Lesson 1 showed that a negative production externality drives a wedge between MPC and MSC, causing the market to overproduce and generating deadweight loss correctable by a Pigouvian tax. Public goods represent an extreme form of positive externality — benefits are shared by all simultaneously, so private markets provide far too little without government intervention.`,
      vocabulary: [
        {
          term: 'Free-Rider Problem',
          definition: 'The tendency for individuals to consume a non-excludable good without contributing to its cost, because they know provision is not conditional on their payment. This causes private markets to underprovide or completely fail to supply public goods.',
          example: 'A resident enjoys a city\'s fireworks display without paying for it; if everyone reasons this way, the fireworks will not be privately funded, illustrating why fireworks are typically government-provided.',
        },
        {
          term: 'Adverse Selection',
          definition: 'A pre-contractual market failure in which asymmetric information causes the uninformed party to transact disproportionately with high-risk or low-quality counterparties, potentially causing the market to unravel.',
          example: 'When health insurers cannot observe individual health status, chronically ill people are more likely to purchase insurance, raising the average cost in the risk pool and pushing premiums up until healthier people exit — the "death spiral."',
        },
        {
          term: 'Moral Hazard',
          definition: 'A post-contractual market failure in which one party changes their behaviour in ways that impose costs on another because they are shielded from the full consequences of their actions.',
          example: 'A restaurant owner installs cheaper fire suppression equipment after taking out full fire insurance, knowing the insurer will cover losses — increasing the expected cost of fire to the insurer.',
        },
      ],
      examinerTip: `AP exam questions on public goods frequently test whether students can correctly classify a good using the rivalry/excludability framework — not simply whether it is "government-provided." Practice the 2x2 table: private goods (rival + excludable), club goods (non-rival + excludable), common resources (rival + non-excludable), public goods (non-rival + non-excludable). For information asymmetry FRQs, distinguish clearly whether the scenario is pre-contractual (adverse selection) or post-contractual (moral hazard) — examiners award a separate point for this distinction. When recommending solutions, link adverse selection to screening/signalling and moral hazard to deductibles/co-pays/monitoring. Partial credit is available for correctly identifying the type of market failure even if the policy prescription is incomplete.`,
      recallQuestions: [
        {
          id: 'ap3-l2-recall-1',
          type: 'mcq' as const,
          question: 'The optimal Pigouvian tax on a negative externality is set equal to the marginal external cost at the social optimum quantity, not at the market quantity. Why does this distinction matter?',
          options: [
            'Setting the tax at the market quantity would over-correct, pushing output below the social optimum where MSC exceeds MSB',
            'Setting the tax at the social optimum quantity would raise too little revenue to compensate harmed parties',
            'The marginal external cost is always larger at the market quantity than at the social optimum',
            'Both quantities yield the same optimal tax because marginal external cost is constant',
          ],
          correctAnswer: 0,
          explanation: 'The Pigouvian tax shifts MPC upward to equal MSC, redirecting the firm to produce at the social optimum. If the tax were calibrated to the market quantity (where output is too high), it would be set too large — pushing output past the social optimum into a range where social cost exceeds social benefit on net. The correct tax reads the MEC at the socially optimal output, not at the unregulated equilibrium.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      thinkAboutIt: {
        question: 'Could a private firm ever profitably provide a pure public good without government intervention? Think of a mechanism that might work.',
        answer: 'In theory, private provision of a pure public good faces the fundamental barrier of non-excludability: any firm that provides the good cannot prevent non-payers from consuming it, making it impossible to recover costs through voluntary market transactions. This explains why private fireworks displays, lighthouses, and basic research are chronically underprovided.\n\nHowever, creative mechanisms can sometimes make private provision viable. Tie-in sales attach a public good to a private good: a shopping mall provides free parking and a pleasant environment (public goods within the mall) because doing so attracts paying customers to shops. Advertising-funded media provides non-excludable content (a public good) by monetising attention to advertisers. Open-source software firms contribute to public code because doing so builds reputation that supports consulting revenue.\n\nThese mechanisms partially solve the free-rider problem by bundling the public good with an excludable complement. The AP lesson is that markets sometimes innovate around the free-rider problem, but they consistently underprovide pure public goods — government provision or compulsory finance remains the standard solution.',
      },
    },
    lessonAssignment: {
      prompt: 'The United States government is considering two reforms to the health insurance market: (A) requiring all insurers to accept applicants regardless of pre-existing conditions at community-rated premiums (no variation by health status), and (B) mandating that all individuals purchase health insurance or pay a tax penalty. Using the concepts of adverse selection, moral hazard, and the free-rider problem, analyse each reform and explain how they interact to address market failures in health insurance.',
      rubric: `Award up to 10 points as follows:
1. Adverse selection identification (2 pts): Correctly identifies that without Reform A, adverse selection causes sicker individuals to self-select into insurance while healthier individuals remain uninsured (1 pt); explains this raises premiums, potentially triggering a death spiral in which only the sickest remain insured (1 pt).
2. Reform A analysis (2 pts): Explains that community rating and guaranteed issue eliminate adverse selection discrimination (1 pt); but without compulsion, they worsen adverse selection — healthy people exit because they can obtain insurance whenever they fall ill, worsening the risk pool (1 pt).
3. Reform B (mandate) analysis (2 pts): Explains that the mandate addresses the free-rider problem — without it, healthy people could free-ride on emergency care and community-rated markets (1 pt); and reduces adverse selection by forcing all risk types into the pool, lowering average cost (1 pt).
4. Interaction between reforms (2 pts): Argues that Reforms A and B must work together — community rating without a mandate collapses the risk pool; a mandate without community rating leaves high-risk individuals priced out (1 pt); together they create a stable, inclusive insurance pool (1 pt).
5. Moral hazard caveat (1 pt): Notes that comprehensive mandatory insurance may worsen moral hazard (over-consumption of care); recommends co-pays or deductibles to mitigate this while preserving coverage.
6. Quality of reasoning (1 pt): Uses correct economic terminology consistently and presents a coherent argument structure.`,
      exampleTopics: [
        'Define adverse selection precisely — it is a pre-contractual hidden-information problem, not simply "sicker people buying more insurance." The key is that the insurer cannot observe individual risk type before issuing the policy.',
        'Think through the death spiral logic step by step: community rating without a mandate raises premiums for healthy people; some healthy people exit; the pool becomes sicker; premiums rise further; repeat. The mandate interrupts this cycle by preventing exit.',
        'Moral hazard in health insurance is a separate but related problem — insured patients may over-consume medical care because they do not bear its full cost. Consider how the mandate and community rating affect moral hazard, and what additional policies (deductibles, co-pays) might be needed.',
        'Consider the distributional dimension: community rating redistributes from low-risk to high-risk individuals. Is this fair? How does your economic analysis interact with normative judgments about equity in healthcare access?',
      ],
    },
  },
  {
    id: 'ap3-l3',
    moduleId: 'ap3-failures',
    title: 'Antitrust and Regulation',
    description: 'Explain horizontal and vertical mergers, natural monopoly regulation, and the efficiency-profit tradeoff.',
    order: 3,
    estimatedMinutes: 30,
    tags: ['antitrust', 'regulation', 'natural-monopoly'],
    flashcards: [
      {
        id: 'fc-ap3-l3-1',
        front: 'What is the primary goal of antitrust policy?',
        back: 'To promote competition by preventing monopolisation, blocking anti-competitive mergers, and prohibiting per se illegal practices such as price-fixing, bid-rigging, and market allocation agreements between rivals.',
        tags: ['antitrust'],
      },
      {
        id: 'fc-ap3-l3-2',
        front: 'What is the efficiency-profit tradeoff in natural monopoly regulation?',
        back: 'MC pricing (P = MC) achieves allocative efficiency but produces losses when LRAC is declining, requiring a subsidy. ATC pricing (P = ATC) is commercially viable (zero profit) but P > MC leaves allocative inefficiency. Neither fully solves both problems simultaneously.',
        tags: ['regulation', 'natural-monopoly'],
      },
      {
        id: 'fc-ap3-l3-3',
        front: 'What is regulatory capture?',
        back: 'When a regulatory agency comes to serve the interests of the industry it regulates rather than the public — a form of government failure. It can cause regulation to raise barriers to entry, protect incumbents, or allow above-normal profits, making regulation counterproductive.',
        tags: ['regulation'],
      },
      {
        id: 'fc-ap3-l3-4',
        front: 'What is the Herfindahl-Hirschman Index (HHI), and how is it used in antitrust analysis?',
        back: 'The HHI is the sum of squared market share percentages of all firms in an industry. It ranges from near zero (perfect competition) to 10,000 (pure monopoly). Antitrust authorities flag post-merger HHI above 2,500 with a large increase (>200 points) as presumptively anti-competitive. The index captures both the number of firms and the distribution of market power — a market with one dominant firm scores much higher than a market with many equal-sized firms.',
        tags: ['antitrust'],
      },
      {
        id: 'fc-ap3-l3-5',
        front: 'What is the Averch-Johnson effect in rate-of-return regulation?',
        back: 'Under rate-of-return regulation, the regulated firm is permitted a "fair" return on its capital base. This creates an incentive to over-invest in capital — by inflating the capital base, the firm increases its permitted total profit. The result is productive inefficiency: the firm uses more capital than the least-cost production method requires. Rate-cap (RPI-X) regulation was developed partly to address this distortion.',
        tags: ['regulation', 'natural-monopoly'],
      },
      {
        id: 'fc-ap3-l3-6',
        front: 'What distinguishes a horizontal merger from a vertical merger, and which faces greater antitrust scrutiny?',
        back: 'A horizontal merger combines firms at the same stage of the supply chain — direct competitors — and directly increases market concentration and pricing power. A vertical merger combines firms at different stages (e.g., a manufacturer acquiring a supplier), which may produce efficiency gains but can foreclose rivals from key inputs. Horizontal mergers face greater automatic scrutiny because the reduction in the number of competing sellers is immediate and unambiguous.',
        tags: ['antitrust'],
      },
      {
        id: 'fc-ap3-l3-7',
        front: 'Why is a natural monopoly unable to earn positive profit if it is required to price at marginal cost?',
        back: 'A natural monopoly arises when long-run average costs are declining over the relevant range of output — meaning LRAC > MC at all output levels the market demands. Marginal-cost pricing sets P = MC < LRAC, so total revenue (P × Q) falls short of total cost (LRAC × Q), producing a loss. The firm requires a government subsidy to remain financially viable under P = MC regulation, which is the fundamental tension between allocative efficiency and commercial viability for natural monopolies.',
        tags: ['regulation', 'natural-monopoly'],
      },
    ],
    quiz: [
      {
        id: 'q-ap3-l3-1',
        type: 'mcq',
        question: 'Average-cost pricing (P = ATC) for a natural monopoly results in which combination of outcomes?',
        options: [
          'Allocative efficiency and positive economic profit for the regulated firm',
          'Zero economic profit for the firm but allocative inefficiency because P > MC',
          'Maximum consumer surplus because price is set as low as possible',
          'The same allocative outcome as marginal-cost pricing but with higher firm profits',
        ],
        correctAnswer: 1,
        explanation: 'At P = ATC the firm earns zero economic profit — commercially viable without a subsidy. However, because LRAC is still declining for a natural monopoly, MC < ATC at the regulated output, meaning P > MC. The firm produces less than the allocatively efficient quantity. This is a second-best outcome: better than unregulated monopoly, but not first-best.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-2',
        type: 'mcq',
        question: 'Which of the following actions would most clearly violate antitrust law as a per se illegal practice?',
        options: [
          'A firm lowering its prices to attract customers away from a rival',
          'Two rival firms agreeing to divide sales territories so they do not compete with each other',
          'A firm acquiring a supplier through a vertical merger to secure inputs',
          'A firm earning large market share through superior product innovation and lower costs',
        ],
        correctAnswer: 1,
        explanation: 'Market allocation agreements between competitors — agreeing not to compete in each other\'s territories — are per se illegal under antitrust law. Per se violations do not require proof of actual harm; the anti-competitive intent is inherent in the practice. The other options are either pro-competitive (price cutting, innovation) or subject to case-by-case "rule of reason" analysis (vertical mergers).',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-3',
        type: 'mcq',
        question: 'A natural monopoly regulated at marginal cost (P = MC) will necessarily:',
        options: [
          'Earn positive economic profit because the regulated price equals its most efficient cost level',
          'Earn zero economic profit because regulation prevents excess returns',
          'Incur an economic loss because for a natural monopoly MC < LRAC, so revenue is insufficient to cover average costs',
          'Produce less output than the unregulated monopoly because P = MC restricts quantity below the profit-maximising level',
        ],
        correctAnswer: 2,
        explanation: 'For a natural monopoly, LRAC is declining, so at any output level MC < LRAC. Setting P = MC means price falls below average cost — total revenue is less than total cost — so the firm incurs a loss and requires a government subsidy to operate. This is why marginal-cost pricing, despite being allocatively efficient, is financially unsustainable for natural monopolies without subsidy support.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-4',
        type: 'mcq',
        question: 'Before a merger, Firm A has a 40% market share and Firm B has a 30% market share. What is the change in the HHI caused by the merger?',
        options: [
          'An increase of 700 points',
          'An increase of 2,400 points',
          'An increase of 1,200 points',
          'An increase of 4,900 points',
        ],
        correctAnswer: 1,
        explanation: 'Pre-merger HHI contribution from A and B: 40² + 30² = 1,600 + 900 = 2,500. Post-merger the combined firm has 70% share, contributing 70² = 4,900. The change in HHI = 4,900 − 2,500 = 2,400. This large increase would trigger close antitrust scrutiny. A useful shortcut: the increase in HHI from a merger of firms with shares s₁ and s₂ equals 2 × s₁ × s₂ = 2 × 40 × 30 = 2,400.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-5',
        type: 'mcq',
        question: 'The Averch-Johnson effect predicts that a regulated utility subject to rate-of-return regulation will:',
        options: [
          'Under-invest in capital to minimise costs and maintain profitability under the rate cap',
          'Over-invest in capital to expand its permitted profit base, leading to productive inefficiency',
          'Set prices below marginal cost to deter entry and preserve its regulated monopoly',
          'Lobby for deregulation because rate-of-return rules prevent it from earning positive economic profit',
        ],
        correctAnswer: 1,
        explanation: 'Rate-of-return regulation grants the firm a permitted profit proportional to its invested capital. This creates an incentive to inflate the capital base — more capital means more permitted total profit. The result is that the firm uses a capital-intensive production method even when cheaper alternatives exist, causing productive inefficiency. This distortion motivated the development of RPI-X (price-cap) regulation in the UK and elsewhere.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-6',
        type: 'mcq',
        question: 'Which of the following best describes a "rule of reason" analysis in antitrust law, as opposed to a per se rule?',
        options: [
          'Per se rules require proof of economic harm; rule of reason presumes harm from certain practices automatically',
          'Rule of reason analysis evaluates the competitive effects and business justifications of a practice case by case; per se rules declare certain practices illegal without requiring proof of harm',
          'Per se rules apply only to horizontal mergers; rule of reason analysis applies only to vertical practices',
          'Rule of reason analysis is applied by courts; per se rules are established by the regulatory agencies without judicial review',
        ],
        correctAnswer: 1,
        explanation: 'Per se illegal practices (price-fixing, market allocation, bid-rigging) are condemned without inquiry into their actual effects — the anti-competitive harm is deemed inherent. Rule of reason analysis applies to practices with ambiguous competitive effects (exclusive dealing, tying arrangements, most vertical restraints), where courts weigh pro-competitive efficiencies against anti-competitive harms on the specific facts. Option A inverts the definitions. Options C and D incorrectly limit the rules by practice type or institution.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-7',
        type: 'mcq',
        question: 'A government regulator is deciding how to regulate a newly privatised water utility. Which regulatory approach best incentivises the firm to reduce costs over time?',
        options: [
          'Rate-of-return regulation — sets a permitted return on the firm\'s capital, ensuring cost increases are passed to consumers',
          'Average-cost pricing — sets price equal to current average total cost, reimbursing all costs the firm incurs',
          'Price-cap (RPI-X) regulation — sets a cap that falls in real terms each period, forcing the firm to reduce costs to maintain profitability',
          'Marginal-cost pricing — sets price equal to marginal cost, ensuring allocative efficiency and strong cost-cutting incentives',
        ],
        correctAnswer: 2,
        explanation: 'RPI-X regulation sets a price ceiling that declines by X percent above inflation each period. The firm can earn profit only by cutting costs faster than the cap declines — creating strong dynamic efficiency incentives. Rate-of-return regulation (A) and average-cost pricing (B) allow cost pass-through, weakening incentives to reduce costs. Marginal-cost pricing (D) achieves allocative efficiency but produces losses for natural monopolies and provides no dynamic efficiency incentive per se.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-8',
        type: 'mcq',
        question: 'Two airlines merge, claiming the combination will allow them to eliminate duplicated routes and lower costs. An antitrust regulator should primarily evaluate whether:',
        options: [
          'The merged firm\'s combined profit exceeds the sum of pre-merger profits of the two firms',
          'The claimed efficiency gains are merger-specific and sufficient to outweigh the competitive harm from reduced rivalry',
          'The merged firm will charge prices above the industry average cost of provision',
          'The merger increases the total number of routes served by the combined airline',
        ],
        correctAnswer: 1,
        explanation: 'Antitrust analysis of horizontal mergers balances claimed efficiency gains against the anti-competitive harm from consolidation. For efficiency claims to be credited, they must be merger-specific (achievable only through the merger, not through less anti-competitive means) and large enough to offset the price increases expected from reduced rivalry. Combined profit levels (A) are not the relevant standard. Above-average prices (C) do not capture the comparison with the but-for competitive benchmark. Route count (D) is incomplete without considering pricing and service quality.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-9',
        type: 'mcq',
        question: 'Regulatory capture most directly represents which type of market or government failure?',
        options: [
          'A natural monopoly failure — the regulated firm exploits declining average costs to extract profits',
          'An information asymmetry — the regulated firm has better information about its costs than the regulator, allowing it to influence the regulatory process in its favour',
          'A negative externality — regulation imposes costs on consumers not reflected in the firm\'s prices',
          'A public goods problem — regulatory oversight is non-rival and non-excludable, so firms free-ride on others\' compliance',
        ],
        correctAnswer: 1,
        explanation: 'Regulatory capture is primarily an information asymmetry problem: the regulated industry has detailed knowledge of its costs, technology, and market conditions that regulators lack. Over time, firms exploit this knowledge gap through lobbying, revolving-door employment, and information provision, steering regulation to serve industry rather than public interests. This is a form of government failure — regulation that was intended to correct market failure instead becomes a source of distortion.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'q-ap3-l3-10',
        type: 'mcq',
        question: 'An electricity transmission network is a classic natural monopoly because:',
        options: [
          'Electricity is a public good — non-rival and non-excludable — making private provision impossible',
          'The high ratio of fixed to variable costs means that average cost falls continuously over the relevant output range, making a single provider more efficient than multiple competing networks',
          'Government policy has historically granted a single firm exclusive rights to operate, preventing competition regardless of cost structure',
          'Electricity production requires patents and proprietary technology that create legal barriers to entry for competitors',
        ],
        correctAnswer: 1,
        explanation: 'A natural monopoly arises from cost structure, not legal barriers. Electricity transmission requires enormous upfront fixed investment in wires, pylons, and transformers that is largely independent of the volume of electricity carried. Once built, the marginal cost of transmitting additional electricity is very low. LRAC declines continuously, so a single network serves the market at lower average cost than duplicating the infrastructure. Option A confuses electricity with a public good (it is excludable and rival). Options C and D describe legal or technological barriers, not the natural cost-based monopoly.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
    content: {
      isStub: false,
      realWorldHook: `In 1998, the U.S. Department of Justice sued Microsoft Corporation for illegally maintaining its Windows monopoly by tying its Internet Explorer browser to Windows and pressuring PC manufacturers not to promote rival browsers. The case ended in a settlement in 2001 — Microsoft was not broken up — but it reshaped how Silicon Valley competed. Twenty years later, regulators around the world opened new antitrust investigations into Google's search advertising dominance, Apple's App Store policies, and Amazon's treatment of third-party sellers. The questions are identical to those the AP exam will ask you: does the firm's market power harm consumers? Is the dominant position earned through efficiency or entrenched through anti-competitive conduct? And when one firm controls essential infrastructure — a network, a grid, a platform — should the state regulate prices, mandate access, or simply break the firm up?`,
      conceptualExplanation: `Antitrust policy aims to maintain competitive market structures and prevent firms from acquiring or abusing monopoly power. The Sherman Act (1890) prohibits restraint of trade and monopolisation; the Clayton Act (1914) targets mergers that substantially lessen competition. Horizontal mergers (between rivals) raise concentration and are scrutinised most heavily; vertical mergers (between suppliers and buyers) and conglomerate mergers receive less automatic suspicion but may still face review. Regulators use the Herfindahl-Hirschman Index (HHI = sum of squared market share percentages) to measure concentration — post-merger HHI above 2,500 in a market with a large increase triggers close scrutiny. Price-fixing, bid-rigging, and market allocation are per se violations requiring no proof of harm.

Where competition is not viable — natural monopolies such as electricity grids and water networks — regulation substitutes for market discipline. The fundamental trade-off is between allocative efficiency and commercial viability. Marginal-cost pricing (P = MC) achieves allocative efficiency but generates losses when average cost exceeds marginal cost, requiring subsidies. Average-cost pricing (P = ATC) achieves zero economic profit without a subsidy but leaves P > MC, creating residual allocative inefficiency. Rate-of-return regulation allows a "fair" return on capital but can incentivise over-investment in capital (the Averch-Johnson effect). Modern price-cap (RPI-X) regulation sets a ceiling that declines in real terms, forcing the firm to improve efficiency to maintain profitability — shifting the incentive structure without requiring regulators to monitor costs directly.`,
      prerequisiteRecap: `Lesson 2 established that public goods generate a free-rider problem causing private markets to underprovide, and that information asymmetries (adverse selection before contracting; moral hazard after) cause further market failures. Antitrust and regulation address a third category — concentrated market power — using the efficiency analysis of monopoly pricing from Module 2.`,
      vocabulary: [
        {
          term: 'Natural Monopoly',
          definition: 'An industry in which long-run average cost declines continuously over the relevant output range, meaning a single firm can serve the entire market at lower cost than two or more competing firms could. Competition is inherently inefficient because duplicating the infrastructure wastes resources.',
          example: 'A city\'s water distribution network requires enormous fixed investment in pipes but has very low marginal cost per additional litre delivered — making it cheaper for one network to serve all households than for two competing pipe networks to exist side by side.',
        },
        {
          term: 'Herfindahl-Hirschman Index (HHI)',
          definition: 'A measure of market concentration calculated as the sum of the squared market share percentages of all firms in an industry. Values range from near 0 (many small firms) to 10,000 (pure monopoly). Antitrust authorities treat post-merger HHI above 2,500 with an increase of more than 200 points as presumptively problematic.',
          example: 'If a market has three firms with shares of 50%, 30%, and 20%, HHI = 50² + 30² + 20² = 2,500 + 900 + 400 = 3,800 — already highly concentrated, meaning any further merger would face heavy scrutiny.',
        },
        {
          term: 'Per Se Illegal Practice',
          definition: 'An action that is automatically unlawful under antitrust law without requiring proof of anti-competitive harm, because the practice is deemed inherently destructive to competition. Contrast with "rule of reason" practices, which require case-by-case analysis of competitive effects.',
          example: 'Three competing airlines secretly agree to fix ticket prices on a major route — this is per se illegal price-fixing regardless of whether prices actually increased or consumers were measurably harmed.',
        },
      ],
      examinerTip: `For natural monopoly FRQs, draw the diagram with LRAC, MC, demand, and MR curves. Label three price-output pairs: unregulated monopoly (MR = MC), average-cost regulation (P = ATC), and marginal-cost regulation (P = MC). The AP exam frequently asks you to compare outcomes at each point — price, quantity, profit, and allocative efficiency. Always note that at P = MC the firm makes a loss (since MC < LRAC) and requires a subsidy. For antitrust FRQs, the HHI calculation is a common quantitative component — memorise the formula (sum of squared shares) and the 2,400-point merger increase shortcut (2 × s₁ × s₂). Partial credit is available for correctly computing pre-merger HHI even if the post-merger figure is wrong.`,
      recallQuestions: [
        {
          id: 'ap3-l3-recall-1',
          type: 'mcq' as const,
          question: 'A good is non-rival and non-excludable. Which market outcome does this most directly predict?',
          options: [
            'Private markets underprovide or do not provide the good at all, because non-payers cannot be excluded and free-riding undermines willingness to pay',
            'Private markets overprovide the good because non-rivalry means production costs are zero',
            'Private markets provide the efficient quantity because non-excludability ensures all consumers reveal their true preferences',
            'Private markets underprovide the good only if it also generates positive externalities for third parties',
          ],
          correctAnswer: 0,
          explanation: 'Non-excludability means free-riding is possible — individuals can consume the good without paying. Rational agents have no incentive to contribute voluntarily, so private producers cannot recover costs and will not supply the good. Non-rivalry means one person\'s consumption does not reduce availability for others — but this amplifies the free-rider problem rather than solving it. Government provision funded by taxation is the standard response.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      thinkAboutIt: {
        question: 'If breaking up a natural monopoly reduces average costs for each fragment, could it ever be welfare-improving to have two competing firms instead of one regulated monopolist?',
        answer: 'The defining feature of a natural monopoly is that a single firm can serve the market at lower average cost than multiple firms. Breaking it up means each firm operates at a smaller scale with higher average costs — duplicating infrastructure (two sets of pipes, two electricity grids) wastes resources. In a pure natural monopoly, competition increases costs and therefore prices for consumers, making the break-up welfare-reducing.\n\nHowever, this logic assumes the natural monopoly extends across the entire relevant market at current demand levels. If demand grows substantially, a second firm may eventually be viable — the industry could cease to be a natural monopoly. Additionally, if the break-up is vertical rather than horizontal — separating the infrastructure (the "pipes") from the service layer — competition can be introduced at the service layer while the infrastructure remains a regulated monopoly. The UK energy and telecoms sectors were restructured this way. So the answer depends critically on where the natural monopoly actually lies in the value chain, not whether the industry label "natural monopoly" applies to the whole firm.',
      },
    },
    lessonAssignment: {
      prompt: 'Two of the three largest hospital systems in a mid-sized U.S. city propose a merger. Combined, they would control 68% of inpatient hospital beds in the metropolitan area. The hospitals argue the merger will allow them to eliminate administrative duplication, share electronic health records systems, and direct patients to the most appropriate facility — reducing costs by an estimated 12%. Analyse this proposed merger using antitrust principles. Should the regulator approve, block, or conditionally approve the merger? Justify your answer with specific economic reasoning.',
      rubric: `Award up to 10 points as follows:
1. Market definition and concentration analysis (2 pts): Defines the relevant market as inpatient hospital services in the metropolitan area (1 pt); calculates or estimates the HHI increase — firms with 68% combined share represent a very high-concentration outcome — and correctly identifies this as presumptively problematic under U.S. antitrust guidelines (1 pt).
2. Anti-competitive harm analysis (3 pts): Explains that reduced competition between hospitals increases pricing power over insurers and patients (1 pt); argues that market allocation of patients (directing patients to "appropriate" facilities) could function as a horizontal restraint if it reduces competition between the merged facilities (1 pt); notes that hospital mergers reduce the quality competition that drives investment in care standards (1 pt).
3. Efficiency defence evaluation (2 pts): Identifies the hospitals' efficiency claims (cost savings from shared EHR systems, administrative de-duplication) as a potential efficiency defence (1 pt); evaluates whether the claimed savings are merger-specific — i.e., could they be achieved through a less anti-competitive arrangement such as a data-sharing agreement or joint venture without full merger? (1 pt).
4. Regulatory recommendation (2 pts): Recommends a specific outcome: block, approve, or conditionally approve — with conditions being the preferred AP-level answer (divestiture of one hospital, price commitments, or mandatory access for rival providers) (1 pt); links the recommendation back to the balance between efficiency gains and competitive harm (1 pt).
5. Government failure caveat (1 pt): Notes that regulatory oversight could itself be subject to capture by hospital industry interests, or that post-merger monitoring is costly — acknowledging that regulation is an imperfect solution to market concentration.`,
      exampleTopics: [
        'Calculate the approximate HHI increase from this merger using the shortcut formula: ΔHHI ≈ 2 × s₁ × s₂. If you do not know the pre-merger shares exactly, estimate them from the 68% combined share and note the range of plausible results. The key point is whether the post-merger market is "highly concentrated" (HHI > 2,500 with ΔHHI > 200).',
        'Evaluate the efficiency claims carefully: are the hospitals claiming they will lower prices to patients, or merely reduce costs to themselves? A 12% cost reduction that is retained as profit does not improve consumer welfare. And could EHR integration be achieved through a contractual arrangement without a full merger?',
        'Consider the "rule of reason" versus per se framework: this is not a per se case (the merger is not automatically illegal), but requires rule of reason analysis weighing competitive harm against efficiency gains. Structure your argument to reflect this balancing test.',
        'Think about what conditions might allow approval: requiring divestiture of one hospital in a specific specialty, mandating price caps for a defined period, or requiring the merged entity to maintain open referral practices that allow patients to seek care at rival facilities.',
      ],
    },
  },
]
