import type { CurriculumModule, Lesson } from '@/lib/types'

export const moduleInfo: Omit<CurriculumModule, 'lessons'> = {
  id: 'ap7-growth',
  title: 'AP Macro — Long-Run Growth & Policy',
  description: 'Productivity, the loanable funds market, Phillips curve, and macro policy debates tested on AP Macro FRQ.',
  tier: 'AP' as const,
  track: 'AP' as const,
  unit: 7,
  estimatedHours: 3,
  color: '#f59e0b',
  icon: 'TrendingUp',
}

export const lessons: Lesson[] = [
  // ── Lesson 1 ──────────────────────────────────────────────────────────────
  {
    id: 'ap7-l1',
    moduleId: 'ap7-growth',
    title: 'Long-Run Economic Growth & Productivity',
    description: 'Supply-side factors that raise potential output, the Rule of 70, and the critical distinction between growth effects and level effects.',
    order: 1,
    estimatedMinutes: 40,
    tags: ['long-run-growth', 'productivity', 'rule-of-70', 'supply-side', 'AP-macro'],
    content: {
      conceptualExplanation: `Long-run economic growth is measured as a sustained increase in **real GDP per capita** — the economy's ability to produce more goods and services per person over time. Unlike short-run fluctuations driven by demand shocks, long-run growth is fundamentally a supply-side phenomenon. The productive capacity of an economy — its potential output — is determined by the quantity and quality of its factors of production: labour, physical capital, human capital, natural resources, and technology. When any of these factors expands or improves, the long-run aggregate supply (LRAS) curve shifts rightward, raising both potential output and the sustainable standard of living. AP students must be able to identify which supply-side policies shift LRAS and by how much.\n\nThe most powerful drivers of long-run growth are **productivity improvements** — getting more output from the same inputs. Total factor productivity (TFP), sometimes called the Solow residual, captures the efficiency with which inputs are combined. Investment in physical capital (machinery, infrastructure) raises the capital-to-labour ratio and boosts output per worker, but with diminishing returns — each additional machine adds less than the previous one. Investment in **human capital** (education, training, health) improves labour quality and is widely seen as a source of increasing rather than diminishing returns. Technological progress — new ideas, processes, and innovations — is the only factor capable of sustaining growth indefinitely, since ideas are non-rival: one firm's use of a production technique does not prevent another from using it too.\n\nEconomists distinguish sharply between a **level effect** and a **growth effect**. A policy that produces a one-time jump in the level of GDP per capita — such as a higher saving rate that moves the economy to a richer steady state — is a level effect: growth temporarily accelerates but then returns to its original long-run rate. A policy that permanently raises the *rate* of growth — such as a breakthrough in the pace of technological innovation — is a growth effect: GDP per capita pulls permanently further ahead of where it would have been. On the AP exam, students are expected to identify which type of effect a given policy produces and to draw the consequence on an LRAS/production possibilities frontier diagram.`,
      prerequisiteRecap: `AP Module 6 concluded with FRQ strategy, linking monetary policy, loanable funds, forex, and the Phillips curve into multi-market chains. Module 7 now builds the supply-side foundations of long-run growth: what determines an economy's potential output, why small differences in growth rates compound dramatically, and how policy can raise the LRAS curve over time.`,
      recallQuestions: [
        {
          id: 'ap7-l1-recall-1',
          type: 'mcq' as const,
          question: 'An AP Macro FRQ asks you to show the effect of expansionary fiscal policy on the loanable funds market. Which curve shifts, and in which direction?',
          options: [
            'Demand for loanable funds shifts rightward, because the government borrows more to finance the deficit, raising the real interest rate',
            'Supply of loanable funds shifts rightward, because government spending injects income that households save',
            'Demand for loanable funds shifts leftward, because higher government spending reduces private sector borrowing needs',
            'Supply of loanable funds shifts leftward, because the deficit reduces national saving',
          ],
          correctAnswer: 0,
          explanation: 'Expansionary fiscal policy (G > T) requires the government to borrow, increasing demand for loanable funds. The demand curve shifts rightward, raising the equilibrium real interest rate and crowding out private investment. Shifting the supply curve leftward is an alternative (and also acceptable) modelling approach — national saving falls when public saving turns negative — but the standard AP answer shifts demand rightward to represent additional government borrowing.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `South Korea's transformation from one of the world's poorest countries in the 1960s to a high-income economy today is a textbook illustration of supply-side growth. Between 1960 and 2000, South Korea's real GDP per capita grew at roughly 7% per year — which, by the Rule of 70, meant living standards doubled approximately every 10 years. This was driven by mass investment in education (human capital), rapid accumulation of physical capital in manufacturing, and technology catch-up. By contrast, many resource-rich African nations that experienced commodity booms saw level effects — temporary income spikes — without the sustained productivity improvements needed for permanent convergence to high-income status.`,
      interactiveElement: `**Rule of 70 Doubling-Time Exercise:** Use the Rule of 70 to complete this table and reflect on compounding's power.\n\n| Country | Annual Growth Rate | Years to Double GDP/capita |\n|---|---|---|\n| China | 6.5% | ? |\n| USA | 2.0% | ? |\n| Zimbabwe | -2.0% | ? (halving time) |\n\nFormula: Doubling time ≈ 70 ÷ growth rate. Answers: China ≈ 10.8 years; USA ≈ 35 years; Zimbabwe: halves every 35 years.\n\n**LRAS Shift Diagram:** Draw a standard AD/AS diagram with LRAS₁ at potential output Y₁. Then show how an increase in labour force participation shifts LRAS rightward to Y₂. Label: horizontal axis = Real GDP, vertical axis = Price Level, curves = AD, SRAS, LRAS₁, LRAS₂, equilibria E₁ and E₂. Note that long-run equilibrium price level falls from P₁ to P₂ if AD is unchanged — a deflationary growth dividend.`,
      vocabulary: [
        {
          term: 'Total Factor Productivity (TFP)',
          definition: 'The portion of output growth not explained by growth in measurable inputs; a measure of how efficiently an economy uses its factors of production.',
          example: 'The digital revolution raised TFP in retail: the same number of workers and stores generate far more sales per hour because of inventory management software and online ordering.',
        },
        {
          term: 'Rule of 70',
          definition: 'A quick approximation stating that a variable growing at rate g% per year will double in approximately 70/g years.',
          example: 'An economy growing at 3.5% per year doubles its GDP in roughly 70/3.5 = 20 years; one growing at 1% takes 70 years to double.',
        },
        {
          term: 'Human Capital',
          definition: 'The stock of knowledge, skills, and health embodied in workers that raises their productive capacity.',
          example: 'A country that increases secondary school completion rates raises its human capital stock, shifting LRAS rightward and boosting long-run potential output.',
        },
      ],
      deeperDive: `The distinction between growth and level effects has profound policy implications. Endogenous growth theory, developed by Paul Romer and others, argues that unlike physical capital, **ideas** and human capital do not suffer from diminishing returns. If government policy can permanently raise the economy's rate of idea production — through R&D subsidies, stronger intellectual property rights, or publicly funded basic research — it can achieve a true growth effect, not merely a level effect. This contrasts sharply with the neoclassical (Solow) framework, in which long-run growth is entirely determined by exogenous technological progress and policy can only affect the level of output.\n\nFor the AP exam, growth questions almost always test the **determinants of LRAS**. The key shifters are: (1) changes in the quantity or quality of labour (immigration, education, health); (2) changes in the quantity or quality of physical capital (net investment, infrastructure); (3) changes in the quantity of natural resources (resource discoveries, conservation); and (4) improvements in technology or institutional quality (property rights, rule of law). Students must not confuse LRAS shifters with AD shifters — a tax cut that boosts consumer spending shifts AD but does not automatically shift LRAS. Only if the tax cut incentivises more work, saving, or investment does it affect potential output. AP FRQ graders will penalise responses that claim a demand-side policy raises LRAS without a clear supply-side transmission mechanism.`,
      commonMisconceptions: [
        'Confusing SRAS and LRAS shifts: An increase in input prices shifts SRAS leftward (cost shock) but does NOT shift LRAS — potential output depends on resource quantities and productivity, not their prices.',
        'Treating all growth as a permanent acceleration: Most policy changes (higher saving rates, one-time capital investment) produce level effects — a new, higher GDP plateau — not a permanently faster growth rate. Only sustained TFP improvements create lasting growth-rate effects.',
        'Assuming a strong GDP growth rate means high living standards: GDP per capita growth is the correct welfare measure; fast aggregate GDP growth in a country with rapid population expansion may leave individuals no better off.',
      ],
      examinerTip: `AP FRQs on long-run growth almost always ask you to (a) identify a determinant of long-run growth, (b) show the effect on the LRAS curve with a correctly labeled diagram, and (c) state the effect on potential output and price level. Practise the standard diagram: axes labeled (Real GDP; Price Level), three curves (AD, SRAS, LRAS), original equilibrium at LRAS₁, then show the rightward shift to LRAS₂. Explicitly state that real GDP *increases* and the price level *decreases* (if AD is fixed). Do not draw SRAS shifting when the question is about long-run growth — graders deduct for irrelevant curve shifts.`,
      didYouKnow: `If the entire global economy had grown at 2% per year from the year 1 CE to today, world GDP would be so large it would exceed the mass of the observable universe converted to gold. Compounding over long periods is staggeringly powerful — which is why even a 0.5 percentage-point difference in annual growth rates, sustained over a century, produces dramatically different standards of living.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ap7-l1-fc1',
        front: 'What is the Rule of 70 and how is it applied to economic growth?',
        back: 'Doubling time (years) ≈ 70 ÷ annual growth rate (%). Example: a 2% growth rate doubles real GDP in ≈ 35 years; a 7% rate doubles it in ≈ 10 years. It illustrates why small differences in growth rates compound into enormous differences in living standards.',
        hint: 'Divide 70 by the percentage growth rate.',
        tags: ['rule-of-70', 'long-run-growth'],
      },
      {
        id: 'ap7-l1-fc2',
        front: 'Distinguish a "level effect" from a "growth effect" in long-run growth theory.',
        back: 'A **level effect** raises the path of GDP per capita to a new, higher trajectory but leaves the long-run growth *rate* unchanged (e.g., a higher saving rate in the Solow model). A **growth effect** permanently increases the *rate* at which GDP per capita grows (e.g., faster technological progress in endogenous growth models).',
        hint: 'Ask: does the growth *rate* change permanently, or only the *level*?',
        tags: ['level-effect', 'growth-effect', 'long-run-growth'],
      },
      {
        id: 'ap7-l1-fc3',
        front: 'List four supply-side factors that shift LRAS rightward.',
        back: '1. Increase in labour force size or quality (human capital). 2. Increase in physical capital stock (net investment). 3. Discovery or better use of natural resources. 4. Technological progress / improvement in total factor productivity (TFP).',
        hint: 'Think: labour, capital, resources, technology.',
        tags: ['LRAS', 'supply-side', 'AP-macro'],
      },
    ],
    quiz: [
      {
        id: 'ap7-l1-q1',
        type: 'mcq',
        question: 'According to the Rule of 70, an economy growing at an annual rate of 3.5% will approximately double its real GDP per capita in how many years?',
        options: [
          '20 years',
          '35 years',
          '10 years',
          '70 years',
        ],
        correctAnswer: 0,
        explanation: 'Doubling time ≈ 70 ÷ 3.5 = 20 years. The Rule of 70 is a quick logarithmic approximation: at 3.5% annual growth, compounding doubles the level in approximately 20 years.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l1-q2',
        type: 'mcq',
        question: 'A government subsidises university education, raising the share of workers with degrees. In the AD/AS framework, this policy primarily affects which curve and in which direction?',
        options: [
          'LRAS shifts rightward, because human capital accumulation raises potential output.',
          'AD shifts rightward, because higher incomes from education increase consumption.',
          'SRAS shifts rightward, because educated workers accept lower wages.',
          'LRAS shifts leftward, because government spending crowds out private investment.',
        ],
        correctAnswer: 0,
        explanation: 'Investing in human capital raises labour productivity and the economy\'s potential output, shifting LRAS rightward. This is a supply-side effect. AD may also shift rightward later (via higher incomes), but the direct, primary effect tested on AP exams is the LRAS shift.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l1-q3',
        type: 'mcq',
        question: 'Which of the following best illustrates a "level effect" rather than a "growth effect" in long-run economic growth?',
        options: [
          'A permanently higher national saving rate moves the economy to a richer steady state but leaves the long-run growth rate unchanged.',
          'A breakthrough in artificial intelligence permanently raises the annual rate of productivity improvement.',
          'A country discovers vast oil reserves, permanently accelerating its GDP growth rate for the next century.',
          'Expanded R&D tax credits permanently raise the economy\'s rate of idea production and innovation.',
        ],
        correctAnswer: 0,
        explanation: 'In the Solow model, a higher saving rate raises the steady-state level of capital and output per worker — a level effect — but the long-run growth rate returns to the rate of exogenous technological progress. Options B, C (if sustained), and D describe growth effects that permanently alter the growth rate.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },

  // ── Lesson 2 ──────────────────────────────────────────────────────────────
  {
    id: 'ap7-l2',
    moduleId: 'ap7-growth',
    title: 'The Loanable Funds Market',
    description: 'How real interest rates are determined, how budget deficits crowd out private investment, and why the loanable funds model is central to AP FRQs.',
    order: 2,
    estimatedMinutes: 40,
    tags: ['loanable-funds', 'real-interest-rate', 'crowding-out', 'budget-deficit', 'AP-macro'],
    content: {
      conceptualExplanation: `The **loanable funds market** is the market where savers supply funds to borrowers. The price in this market is the **real interest rate** (nominal rate adjusted for expected inflation), which equilibrates the supply of loanable funds with the demand for them. The supply of loanable funds comes from domestic private saving (households and businesses that defer consumption), foreign saving (net capital inflows), and — in some formulations — government saving (budget surpluses). The demand for loanable funds comes from firms seeking to finance investment projects and from government borrowing to cover budget deficits. The AP exam treats this as a standard supply-and-demand model: when the real interest rate is above equilibrium, there is a surplus of funds (excess saving) and rates fall; when it is below, there is a shortage and rates rise.\n\nThe most tested application is **crowding out**. When the government runs a budget deficit, it must borrow by selling bonds, which increases the demand for loanable funds. The demand curve shifts rightward, pushing the real interest rate up. At the higher real interest rate, private investment spending is reduced — firms borrow less to build factories, buy equipment, or fund R&D. This is crowding out: government borrowing "crowds out" private investment. On a diagram, the rightward shift of the demand curve for loanable funds raises the equilibrium real interest rate from r* to r** and reduces the quantity of funds available for private investment. In an open economy, higher domestic real interest rates also attract foreign capital inflows, causing the currency to appreciate and net exports to fall — a second crowding-out channel.\n\nConversely, policies that increase private saving shift the supply of loanable funds rightward, lowering the real interest rate and increasing the equilibrium quantity of loanable funds — "crowding in" private investment. Examples include tax incentives for saving (Roth IRAs, lower capital gains taxes) and reductions in the budget deficit. The AP exam also tests the effect of economic expansions and contractions on the loanable funds market: during expansions, firms see profitable investment opportunities and demand for loanable funds rises; during recessions, investment demand falls, putting downward pressure on real interest rates.`,
      prerequisiteRecap: `Lesson 1 identified four supply-side determinants of LRAS — labour, physical capital, human capital, and technology — and used the Rule of 70 to show how small growth rate differences compound into vast living standard gaps. Lesson 2 now examines the loanable funds market, which channels saving into the physical capital investment that is one of those four LRAS determinants, and shows how government borrowing can crowd it out.`,
      recallQuestions: [
        {
          id: 'ap7-l2-recall-1',
          type: 'mcq' as const,
          question: 'A government subsidises university education, raising the share of workers with advanced degrees. In the long-run AD/AS framework, what is the primary effect, and is it a level effect or a growth effect?',
          options: [
            'LRAS shifts rightward (higher potential output) — a level effect if it raises the stock of human capital to a new plateau, not the ongoing rate of TFP growth',
            'AD shifts rightward (higher consumer spending from educated workers) — a growth effect because income rises permanently',
            'SRAS shifts rightward (lower unit labour costs from more efficient workers) — a level effect on the price level only',
            'LRAS shifts rightward — a growth effect because human capital improvements permanently raise the annual productivity growth rate',
          ],
          correctAnswer: 0,
          explanation: 'Investing in human capital raises labour quality and shifts LRAS rightward — the economy\'s potential output increases. This is primarily a level effect: the economy moves to a higher LRAS, but the long-run growth rate (determined by the ongoing pace of technological progress) is not permanently raised by a one-time education subsidy. Endogenous growth theory suggests it could be a growth effect if education permanently raises the rate of idea production, but the standard AP/Solow answer classifies it as a level effect.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `During the COVID-19 pandemic, the U.S. federal government ran a budget deficit exceeding $3 trillion in fiscal year 2020 — roughly 15% of GDP. Standard loanable funds theory predicts this massive increase in government borrowing should have crowded out private investment and raised real interest rates. In practice, the Federal Reserve simultaneously purchased trillions in Treasury bonds (quantitative easing), vastly increasing the supply of loanable funds and keeping real interest rates near zero or negative. This episode illustrates both the mechanics of the loanable funds model and how monetary policy can offset fiscal crowding out — a nuance tested in AP FRQ multi-market questions.`,
      interactiveElement: `**Loanable Funds Diagram — Budget Deficit Crowding Out:**\n\nDraw a correctly labeled loanable funds market diagram:\n- Horizontal axis: Quantity of Loanable Funds ($ billions)\n- Vertical axis: Real Interest Rate (%)\n- Upward-sloping Supply curve: S (private saving + foreign saving)\n- Downward-sloping Demand curve: D₁ (private investment demand)\n- Original equilibrium: E₁ at real interest rate r* and quantity Q*\n\nNow show a government budget deficit:\n1. Shift demand rightward to D₂ (government borrowing added to private investment demand)\n2. Mark new equilibrium E₂ at higher real interest rate r** and larger quantity Q**\n3. Shade the region showing private investment crowded out: at r**, private investment is lower than Q*\n\n**Key labels:** S (supply of loanable funds = private saving), D₁ (private investment), D₂ (private investment + government borrowing), r*, r**, E₁, E₂, "Crowding-out gap."`,
      vocabulary: [
        {
          term: 'Crowding Out',
          definition: 'The reduction in private investment that results when government borrowing raises real interest rates, making investment projects less profitable for firms.',
          example: 'If a $500 billion budget deficit pushes the real interest rate from 3% to 5%, firms cancel factory expansions that were profitable at 3% but not at 5% — private investment is crowded out.',
        },
        {
          term: 'Real Interest Rate',
          definition: 'The nominal interest rate minus the expected inflation rate; the true cost of borrowing and the true return to saving in terms of purchasing power.',
          example: 'If a bank charges 7% nominal interest and inflation is expected at 3%, the real interest rate is 4% — what the borrower truly pays in goods-and-services terms.',
        },
        {
          term: 'National Saving',
          definition: 'The sum of private saving (household + business) and public saving (government budget surplus, or minus the deficit); the total domestic supply of loanable funds.',
          example: 'If households save $800B, businesses retain $400B, and the government runs a $200B deficit, national saving = $800B + $400B − $200B = $1,000B.',
        },
      ],
      deeperDive: `The loanable funds model rests on the **savings-investment identity**: in a closed economy, investment must equal saving (I = S) by accounting definition. In an open economy, this extends to I = S + net capital inflows (foreign saving). A budget deficit reduces public saving; if private saving does not rise to fully offset it (Ricardian equivalence predicts it might, but empirically it does not), national saving falls, the supply of loanable funds shifts left, and real interest rates rise. The degree of crowding out depends on the slope of the investment demand curve: if investment is very interest-rate sensitive (elastic), a small rise in the real interest rate produces large crowding out; if investment is interest-rate inelastic (e.g., during a Keynesian liquidity trap), the real interest rate may not rise much even with large deficits.\n\n**Ricardian Equivalence** is an important counterargument: if households fully anticipate future tax increases needed to repay deficit-financed borrowing, they will save more today to pay those future taxes, exactly offsetting the fall in government saving. In this case, deficits do not crowd out investment because private saving rises by exactly the amount of the deficit. However, empirical evidence suggests Ricardian equivalence holds only partially, if at all — households are not fully forward-looking, face borrowing constraints, and may not survive to pay future taxes. For AP purposes, the standard model assumes deficits do crowd out investment (the Ricardian equivalence exception is an AP exam bonus point, not the baseline answer).`,
      commonMisconceptions: [
        'Confusing the nominal and real interest rate: The loanable funds market determines the REAL interest rate. On AP diagrams, always label the vertical axis "Real Interest Rate" — never "Nominal Interest Rate." Monetary policy affects the nominal rate in the short run; the loanable funds market is primarily a real-side market.',
        'Thinking government borrowing shifts the supply curve: Government deficits increase the DEMAND for loanable funds (government is a borrower), not the supply. The supply curve shifts right only when saving increases (e.g., private saving rises, capital inflows increase, or government runs a surplus).',
        'Assuming crowding out is always 100%: Complete crowding out (where every dollar of government borrowing displaces exactly one dollar of private investment) requires a vertical supply curve. In practice, crowding out is partial — some private investment is displaced but not all, especially when idle resources exist.',
      ],
      examinerTip: `On the AP FRQ loanable funds diagram, earn ALL available points by: (1) drawing an upward-sloping supply curve and downward-sloping demand curve with axes correctly labeled (Quantity of Loanable Funds; Real Interest Rate); (2) shifting DEMAND rightward for deficit spending (not supply); (3) labeling original equilibrium E₁ at r* and new equilibrium E₂ at r**; (4) explicitly stating in your written explanation that the real interest rate RISES and private investment FALLS (crowding out). Many students lose a point by shifting the wrong curve or labeling the axis "interest rate" instead of "real interest rate."`,
      didYouKnow: `The U.S. government's interest payments on the national debt exceeded $1 trillion annually for the first time in 2024 — more than the entire federal defence budget. As real interest rates rise with large deficits, debt service costs consume an ever-larger share of the federal budget, leaving less room for discretionary spending. This is the long-run fiscal consequence of the crowding-out mechanism the AP loanable funds model illustrates.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ap7-l2-fc1',
        front: 'In the loanable funds market, what shifts the DEMAND for loanable funds rightward?',
        back: '1. Increased private investment demand (firms see more profitable opportunities). 2. Government deficit spending (government borrows more). 3. Optimistic business expectations raising expected returns on investment. Each of these increases the quantity of funds demanded at every real interest rate, shifting demand right and raising the equilibrium real interest rate.',
        hint: 'Think about who borrows in this market: firms (investment) and governments (deficits).',
        tags: ['loanable-funds', 'crowding-out'],
      },
      {
        id: 'ap7-l2-fc2',
        front: 'Explain the crowding-out mechanism in the loanable funds market.',
        back: 'Government deficit → increased demand for loanable funds → demand curve shifts right → real interest rate rises → private investment becomes less profitable → firms borrow and invest less. The government "crowds out" private investment by competing for the same pool of loanable funds.',
        hint: 'Follow the chain: deficit → demand → r → investment.',
        tags: ['crowding-out', 'loanable-funds', 'AP-macro'],
      },
      {
        id: 'ap7-l2-fc3',
        front: 'What is national saving and how does a budget deficit affect the loanable funds market supply?',
        back: 'National saving = Private saving + Public saving (budget surplus). A budget deficit means negative public saving, which reduces national saving and shifts the SUPPLY of loanable funds leftward — raising real interest rates from the supply side. On the AP exam, this supply-side crowding out is an alternative (and equally correct) way to model deficit effects.',
        hint: 'National saving = Private saving + Government budget surplus (or − deficit).',
        tags: ['national-saving', 'loanable-funds', 'budget-deficit'],
      },
    ],
    quiz: [
      {
        id: 'ap7-l2-q1',
        type: 'mcq',
        question: 'In a correctly labeled loanable funds market diagram, an increase in the federal budget deficit will most directly cause which of the following?',
        options: [
          'The demand for loanable funds shifts rightward, raising the real interest rate and reducing private investment.',
          'The supply of loanable funds shifts rightward, lowering the real interest rate and increasing private investment.',
          'The demand for loanable funds shifts leftward, lowering the real interest rate and stimulating private investment.',
          'The supply of loanable funds shifts leftward with no change in private investment demand.',
        ],
        correctAnswer: 0,
        explanation: 'A larger budget deficit means the government must borrow more, increasing the demand for loanable funds. The demand curve shifts right, equilibrium real interest rate rises, and at the higher rate, private investment is crowded out. This is the standard AP loanable funds crowding-out result.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l2-q2',
        type: 'mcq',
        question: 'If households increase their personal saving rate significantly, what happens in the loanable funds market?',
        options: [
          'Supply of loanable funds increases, real interest rate falls, private investment increases — "crowding in."',
          'Demand for loanable funds increases, real interest rate rises, private investment increases.',
          'Supply of loanable funds decreases, real interest rate rises, private investment falls.',
          'The loanable funds market is unaffected because saving equals investment by identity.',
        ],
        correctAnswer: 0,
        explanation: 'Higher household saving increases the supply of loanable funds (shifts supply rightward). The equilibrium real interest rate falls, making borrowing cheaper and stimulating private investment — the opposite of crowding out, sometimes called "crowding in." This illustrates why policies that raise national saving lower the cost of capital.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l2-q3',
        type: 'mcq',
        question: 'Ricardian equivalence, if it held perfectly, would imply that a government deficit financed by bond issuance would:',
        options: [
          'Not affect private investment, because households would increase saving by exactly the amount of the deficit to pay future taxes.',
          'Fully crowd out private investment, because every dollar borrowed by government displaces a dollar of private borrowing.',
          'Stimulate private investment by injecting demand into the economy.',
          'Lower real interest rates, because bond supply increases household wealth.',
        ],
        correctAnswer: 0,
        explanation: 'Ricardian equivalence holds that rational, forward-looking households anticipate the future taxes needed to repay deficit financing. They save more today to offset the future tax burden, exactly replacing the fall in public saving. Result: national saving is unchanged, loanable funds supply is unchanged, real interest rates are unchanged, and there is no crowding out. In practice, evidence for full Ricardian equivalence is weak.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },

  // ── Lesson 3 ──────────────────────────────────────────────────────────────
  {
    id: 'ap7-l3',
    moduleId: 'ap7-growth',
    title: 'Short-Run & Long-Run Phillips Curve',
    description: 'SRPC and LRPC relationships, how supply shocks create stagflation, and how the Phillips curve connects to AD/AS analysis.',
    order: 3,
    estimatedMinutes: 40,
    tags: ['Phillips-curve', 'SRPC', 'LRPC', 'stagflation', 'supply-shocks', 'AP-macro'],
    content: {
      conceptualExplanation: `The **Phillips curve** describes the short-run relationship between the unemployment rate and the inflation rate. When the economy is running above potential output (output gap positive), unemployment falls below the natural rate and firms compete for scarce workers, pushing wages and prices up — inflation rises. When the economy is in recession (output gap negative), unemployment rises above the natural rate and inflationary pressures ease — inflation falls. On the **short-run Phillips curve (SRPC)**, inflation and unemployment move in opposite directions: the curve slopes downward. Policymakers can use expansionary policy to move up the SRPC (lower unemployment, higher inflation) or contractionary policy to move down it (higher unemployment, lower inflation).\n\nThe **long-run Phillips curve (LRPC)** is vertical at the **natural rate of unemployment (NRU)** — the unemployment rate consistent with stable (non-accelerating) inflation. Also called the Non-Accelerating Inflation Rate of Unemployment (NAIRU), it reflects frictional and structural unemployment that exists even in a healthy economy. In the long run, any attempt to push unemployment permanently below the NRU fails: workers and firms adjust their inflation expectations upward, wages rise, costs increase, and the SRPC shifts up. The economy returns to the NRU at a higher inflation rate. This is the **expectations-augmented Phillips curve** insight: the short-run trade-off disappears in the long run because expectations adjust.\n\n**Supply shocks** cause the SRPC to shift, creating the dreaded **stagflation** — simultaneous high unemployment and high inflation. A negative supply shock (oil price spike, pandemic supply disruption) raises production costs, shifting the SRPC upward and to the right. The economy moves to a point of higher inflation AND higher unemployment — off the original SRPC. This shift cannot be represented as movement along a single SRPC; rather, the entire curve moves. Policymakers then face an impossible trade-off: fight inflation with contractionary policy (pushing unemployment even higher) or fight unemployment with expansionary policy (pushing inflation even higher). The stagflation of the 1970s — driven by OPEC oil embargoes — is the canonical historical example.`,
      prerequisiteRecap: `Lesson 2 showed that government deficit spending increases demand for loanable funds, raising the real interest rate and crowding out private investment. Lesson 3 connects these real-sector dynamics to the Phillips curve: the same investment changes that shift LRAS and capital accumulation also determine where the economy sits relative to the natural rate of unemployment, tracing the inflation-unemployment trade-off.`,
      recallQuestions: [
        {
          id: 'ap7-l3-recall-1',
          type: 'mcq' as const,
          question: 'An increase in the federal budget deficit crowds out private investment via the loanable funds market. What is the long-run implication of reduced private investment for the economy\'s productive capacity?',
          options: [
            'The capital stock grows more slowly, reducing the rate of LRAS rightward shift and lowering future potential output compared to what it would otherwise have been',
            'Potential output is unchanged because government spending directly replaces private investment in the production function',
            'The capital stock falls immediately, shifting LRAS leftward in the short run',
            'Future potential output rises because government borrowing funds productive public investment that more than offsets the private investment displaced',
          ],
          correctAnswer: 0,
          explanation: 'Crowding out means less private capital formation each year. Physical capital is one of the four LRAS determinants: with less investment, the capital stock grows more slowly, and LRAS shifts rightward less rapidly over time. Potential output in future years is lower than it would have been without the deficit. This long-run growth cost is the key reason economists worry about structural deficits — the fiscal impact on living standards compounds over decades.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `In 2021–2022, the United States experienced a near-textbook supply shock: COVID-19 disrupted global supply chains, the war in Ukraine spiked energy and food prices, and "reshoring" pressures raised production costs. The result was the highest inflation since the early 1980s (peaking near 9% CPI) alongside an unemployment rate that had already fallen to 3.5% — a point above and to the left of where the pre-pandemic SRPC would have predicted. The Federal Reserve's aggressive response — raising the federal funds rate from near zero to over 5% in 18 months — was a deliberate move down the SRPC: accept higher unemployment to wring out inflation expectations before they became entrenched in the LRPC.`,
      interactiveElement: `**Phillips Curve Diagram — Supply Shock Stagflation:**\n\nDraw a coordinate plane:\n- Horizontal axis: Unemployment Rate (%), with Natural Rate (NRU) marked with a dashed vertical line\n- Vertical axis: Inflation Rate (%)\n\nStep 1 — Original SRPC₁: Draw a downward-sloping curve passing through NRU at the target inflation rate (e.g., 2%). Mark the original equilibrium A at (NRU, 2%).\n\nStep 2 — Negative supply shock: Draw a new SRPC₂ shifted UP and to the RIGHT of SRPC₁. Mark stagflation point B: higher inflation AND higher unemployment than point A simultaneously.\n\nStep 3 — LRPC: Draw a vertical line at NRU. Show that long-run equilibrium always lies on the LRPC, regardless of where the SRPC is.\n\nStep 4 — Label: SRPC₁ (original), SRPC₂ (after supply shock), LRPC (vertical at NRU), points A (original equilibrium), B (stagflation), and the policy dilemma arrow showing that contractionary policy moves to C (lower inflation, higher unemployment on SRPC₂) while expansionary policy moves to D (lower unemployment, even higher inflation on SRPC₂).`,
      vocabulary: [
        {
          term: 'Natural Rate of Unemployment (NRU)',
          definition: 'The unemployment rate at which inflation is stable; equals frictional plus structural unemployment; the unemployment rate at the vertical LRPC.',
          example: 'If the U.S. NRU is approximately 4%, an unemployment rate of 3.5% means the economy is above potential, and inflation will tend to accelerate until unemployment returns to 4%.',
        },
        {
          term: 'Stagflation',
          definition: 'The simultaneous occurrence of high inflation and high unemployment, typically caused by a negative supply shock that shifts the SRPC upward.',
          example: 'The 1970s oil embargo caused stagflation in the U.S.: unemployment rose to ~9% while inflation exceeded 10% — a point far to the upper-right of the previous SRPC.',
        },
        {
          term: 'Expectations-Augmented Phillips Curve',
          definition: 'The theory that the short-run Phillips curve shifts when inflation expectations change; workers and firms build expected inflation into wage and price decisions, making the long-run trade-off vertical.',
          example: 'If workers expect 5% inflation and negotiate wages accordingly, actual inflation will tend toward 5% regardless of the unemployment rate — the SRPC shifts up to reflect the higher expectations.',
        },
      ],
      deeperDive: `The **Lucas critique** deepened the expectations-augmented Phillips curve: policymakers cannot systematically exploit the short-run trade-off, because rational agents will anticipate policy moves and adjust expectations immediately. If the Federal Reserve announces it will tolerate higher inflation to reduce unemployment, rational workers immediately demand higher wages, shifting the SRPC upward before the policy even takes effect. This insight underpins modern central bank emphasis on **credibility and anchored inflation expectations**: if households and firms believe the Fed will always bring inflation back to 2%, the SRPC is more stable and supply shocks are less likely to become entrenched.\n\nThe **sacrifice ratio** measures how much unemployment (or GDP loss) is needed to reduce inflation by one percentage point. Estimates range from 1.5 to 5 percentage point-years of unemployment per point of inflation reduction. The 1979–1982 Volcker disinflation — when the Fed raised rates sharply to break the stagflation of the 1970s — involved unemployment peaking at 10.8% and is the key empirical example. For AP, understand that disinflation (reducing the inflation rate) requires moving down the SRPC (accepting higher unemployment), and that the SRPC shifts down over time as inflation expectations adjust downward — eventually restoring the economy to lower inflation at the NRU.`,
      commonMisconceptions: [
        'Thinking movement along the SRPC and shifts of the SRPC are the same: AD shocks cause movement ALONG a given SRPC (demand-pull inflation = move up; recession = move down). Supply shocks SHIFT the SRPC itself. Students who draw a movement along SRPC₁ for a supply shock will lose all diagram points.',
        'Confusing the LRPC being vertical with "no trade-off ever": There IS a short-run trade-off (the SRPC is downward-sloping). The LRPC being vertical means only that the trade-off cannot be exploited permanently — in the long run, any inflation rate is compatible with the NRU, so no permanent reduction in unemployment can be achieved by accepting more inflation.',
        'Saying a supply shock causes movement up a fixed SRPC: A supply shock (e.g., oil price spike) shifts the SRPC upward — the entire curve moves. It does NOT cause upward movement along the original SRPC, which would represent demand-pull inflation from an AD increase.',
      ],
      examinerTip: `AP FRQs on the Phillips curve almost always pair it with an AD/AS scenario. When AD increases (expansionary policy), in the short run: output rises above potential, unemployment falls below NRU — on the SRPC this is a move UP-LEFT (lower unemployment, higher inflation). When a negative supply shock hits (SRAS shifts left in AD/AS), the SRPC shifts UP-RIGHT — this is the critical distinction. Label your diagrams: SRPC₁, SRPC₂, LRPC (vertical at NRU), and mark original equilibrium (A) and new equilibrium (B) explicitly. State in words: "Unemployment rises above/below the NRU" and "Inflation rises/falls" to collect verbal explanation points.`,
      didYouKnow: `A.W. Phillips originally discovered the Phillips curve relationship in 1958 by plotting UK wage inflation against unemployment from 1861 to 1957 — nearly a century of data. His original curve showed a remarkably stable inverse relationship. The relationship famously broke down in the 1970s when stagflation struck, prompting Milton Friedman and Edmund Phelps (independently, in 1968) to develop the expectations-augmented version that dominates macroeconomics today. Both Friedman and Phelps predicted the breakdown of the original Phillips curve before it happened — one of economics' most striking predictive successes.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ap7-l3-fc1',
        front: 'Why is the Long-Run Phillips Curve (LRPC) vertical at the Natural Rate of Unemployment?',
        back: 'In the long run, inflation expectations fully adjust. Any attempt to keep unemployment below the NRU causes workers to demand higher wages (anticipating inflation), which pushes costs up and raises actual inflation — the SRPC shifts up. The economy always returns to NRU regardless of the inflation rate, so the LRPC is vertical: every inflation rate is consistent with NRU in the long run.',
        hint: 'Key concept: expectations adjust in the long run.',
        tags: ['LRPC', 'NRU', 'Phillips-curve'],
      },
      {
        id: 'ap7-l3-fc2',
        front: 'What causes the Short-Run Phillips Curve (SRPC) to SHIFT (not move along)?',
        back: 'The SRPC shifts when: (1) inflation expectations change (higher expected inflation shifts SRPC up); (2) a supply shock occurs (negative supply shock — oil price spike — shifts SRPC up-right causing stagflation; positive supply shock shifts it down-left); (3) the NRU changes (structural changes shift SRPC left/right). Demand shocks cause MOVEMENT ALONG a given SRPC.',
        hint: 'Shifts: expectations change or supply shocks. Movement along: demand changes.',
        tags: ['SRPC', 'stagflation', 'Phillips-curve'],
      },
      {
        id: 'ap7-l3-fc3',
        front: 'Define stagflation and explain its origin in the Phillips curve framework.',
        back: 'Stagflation = simultaneous high inflation AND high unemployment. Caused by a negative supply shock (e.g., oil embargo) that shifts the SRPC upward and to the right. In AD/AS: SRAS shifts left, raising the price level (inflation) and lowering real GDP (higher unemployment). The economy ends up at a point above and to the right of the original SRPC — both variables worsen simultaneously.',
        hint: 'Supply shock → SRAS left → SRPC shifts up-right.',
        tags: ['stagflation', 'supply-shocks', 'SRPC'],
      },
    ],
    quiz: [
      {
        id: 'ap7-l3-q1',
        type: 'mcq',
        question: 'The Federal Reserve pursues expansionary monetary policy, increasing the money supply. In the Phillips curve framework, this most directly causes:',
        options: [
          'Movement up the SRPC: unemployment falls below the NRU and inflation rises.',
          'The SRPC shifts upward and to the right, causing stagflation.',
          'The LRPC shifts rightward, raising the natural rate of unemployment.',
          'Movement down the SRPC: unemployment rises and inflation falls.',
        ],
        correctAnswer: 0,
        explanation: 'Expansionary monetary policy increases AD. In the short run, output rises above potential and unemployment falls below the NRU — this is movement UP-LEFT along a fixed SRPC (lower unemployment, higher inflation). The SRPC itself does not shift from a demand stimulus; only supply shocks or expectation changes shift the SRPC.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l3-q2',
        type: 'mcq',
        question: 'A major oil-producing cartel drastically cuts production, causing global oil prices to surge. Which of the following correctly describes the effect on the Phillips curve?',
        options: [
          'The SRPC shifts upward, creating stagflation: both inflation and unemployment rise simultaneously.',
          'The economy moves upward along the existing SRPC: inflation rises and unemployment falls.',
          'The LRPC shifts rightward: the natural rate of unemployment permanently rises.',
          'The SRPC shifts downward: cheaper energy reduces costs and lowers inflation.',
        ],
        correctAnswer: 0,
        explanation: 'A supply shock (oil price spike) is a negative supply shock that raises production costs across the economy. In AD/AS terms, SRAS shifts left. In Phillips curve terms, the SRPC shifts upward and to the right — both inflation and unemployment rise simultaneously (stagflation). This is a SHIFT of the SRPC, not movement along it.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l3-q3',
        type: 'mcq',
        question: 'In the long run, after an expansionary demand shock temporarily reduces unemployment below the NRU, what happens to the Short-Run Phillips Curve and the economy\'s equilibrium?',
        options: [
          'Higher inflation expectations shift the SRPC upward; the economy returns to the NRU at a higher inflation rate on the LRPC.',
          'The SRPC stays fixed; the economy permanently remains at lower unemployment and higher inflation.',
          'The LRPC shifts leftward, lowering the NRU to match the new lower unemployment rate.',
          'The SRPC shifts downward as higher wages reduce production costs.',
        ],
        correctAnswer: 0,
        explanation: 'When unemployment is below the NRU, there is upward pressure on wages and prices. Workers and firms revise inflation expectations upward, shifting the SRPC upward. The economy moves back to the NRU — but at a higher inflation rate. This is the long-run self-correcting mechanism described by the expectations-augmented Phillips curve.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },

  // ── Lesson 4 ──────────────────────────────────────────────────────────────
  {
    id: 'ap7-l4',
    moduleId: 'ap7-growth',
    title: 'Fiscal & Monetary Policy Trade-offs',
    description: 'Liquidity traps, the zero lower bound, policy lags, and the debate between rules-based and discretionary macroeconomic policy.',
    order: 4,
    estimatedMinutes: 35,
    tags: ['fiscal-policy', 'monetary-policy', 'liquidity-trap', 'zero-lower-bound', 'policy-lags', 'AP-macro'],
    content: {
      conceptualExplanation: `Standard macroeconomic policy operates through two main levers. **Fiscal policy** — changes in government spending (G) and taxation (T) — directly shifts aggregate demand (AD) and works through the expenditure multiplier: an initial change in G or T triggers a chain of spending rounds, amplifying the original impulse. **Monetary policy** — central bank control of the money supply and short-term interest rates — shifts AD indirectly: lower interest rates reduce the cost of borrowing, stimulating investment (I) and some interest-sensitive consumption (C). In normal conditions, both tools can steer the economy toward potential output. But each has limitations that become severe in certain macroeconomic conditions.\n\nThe **liquidity trap** is a situation — first described by Keynes and later formalised by Paul Krugman — in which monetary policy becomes ineffective even though nominal interest rates are near zero. At the **zero lower bound (ZLB)**, the central bank cannot further reduce nominal interest rates (they cannot go significantly negative without undermining the banking system). If deflation is occurring or expected, the real interest rate can remain positive even with zero nominal rates, leaving investment depressed. In a liquidity trap, households and firms hold money rather than bonds because bond yields are so low that the opportunity cost of holding cash is negligible. Additional money creation does not stimulate spending — money just sits idle. Fiscal policy, which bypasses the interest rate channel entirely, becomes the primary stabilisation tool in this scenario.\n\n**Policy lags** are the delays between recognising a problem and achieving the desired economic effect. Monetary policy has short **inside lags** (the Fed can change rates at any FOMC meeting) but long **outside lags** (12–18 months for rate changes to fully affect output and inflation). Fiscal policy has long **inside lags** (Congress must debate and pass legislation) but shorter **outside lags** once spending occurs. The combination means policy can be destabilising: stimulus enacted during a recession may take effect during the subsequent recovery, amplifying rather than smoothing the business cycle. This timing problem is the core argument for **automatic stabilisers** (progressive taxes, unemployment insurance) that respond immediately to economic conditions without requiring legislative action.`,
      prerequisiteRecap: `Lesson 3 showed that the SRPC captures the short-run inflation-unemployment trade-off while the LRPC is vertical at the NAIRU because inflation expectations adjust. Lesson 4 explores the limits of the policy tools used to navigate that trade-off: what happens when monetary policy is constrained by the zero lower bound, and how policy lags can make stabilisation counterproductive.`,
      recallQuestions: [
        {
          id: 'ap7-l4-recall-1',
          type: 'mcq' as const,
          question: 'A negative supply shock (e.g., a spike in oil prices) shifts the SRPC upward. If policymakers respond with contractionary monetary policy to fight the resulting inflation, what happens to unemployment?',
          options: [
            'Unemployment rises further above the natural rate, as contractionary policy moves the economy down the new, higher SRPC — accepting even worse unemployment to reduce inflation',
            'Unemployment falls back to the natural rate immediately, because the SRPC shifts down when inflation is reduced',
            'Unemployment is unchanged, because the supply shock only affects the price level, not real output',
            'Unemployment falls, because lower inflation raises consumer purchasing power and stimulates demand',
          ],
          correctAnswer: 0,
          explanation: 'After a supply shock shifts the SRPC upward, the economy is already at higher inflation AND higher unemployment (stagflation). Contractionary policy moves the economy down-right along the new, elevated SRPC — trading still higher unemployment for lower inflation. This is the "disinflation via recession" path: the economy must suffer above-natural unemployment until falling inflation expectations shift the SRPC back down. There is no costless way to undo a supply shock with demand-side policy.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `Japan's experience from the 1990s through the 2010s is the world's most studied liquidity trap. After its asset bubble burst in 1991, Japan cut interest rates to zero by 1999 and introduced quantitative easing as early as 2001 — but growth remained sluggish and deflation persistent. The Bank of Japan found that even holding rates at zero (and eventually negative) failed to stimulate adequate borrowing and spending. Japan's government responded with massive fiscal stimulus packages, accumulating public debt exceeding 250% of GDP by the 2020s. The Japanese experience informed the Federal Reserve's playbook during the 2008 financial crisis and the COVID-19 pandemic — both episodes in which the ZLB was quickly reached and unconventional tools (QE, forward guidance) became the primary monetary instruments.`,
      interactiveElement: `**Policy Lag Timeline — Monetary vs. Fiscal Policy:**\n\nDraw two horizontal timelines:\n\nTimeline 1 — Monetary Policy:\n- Month 0: Recession recognised\n- Month 1: Fed meets and cuts rates (short inside lag)\n- Month 6–12: Investment begins to respond\n- Month 12–18: Full GDP impact (long outside lag)\n\nTimeline 2 — Fiscal Policy:\n- Month 0: Recession recognised\n- Month 6–12: Congress debates and passes stimulus bill (long inside lag)\n- Month 13–14: Government spending begins\n- Month 14–16: GDP impact (shorter outside lag)\n\n**ZLB Money Market Diagram:** Draw a money market with a vertical money supply and downward-sloping money demand. Show the demand curve shifting left (recession reduces money demand). Nominal interest rate hits zero — the "floor." Any further rightward shift of money supply cannot push the nominal rate below zero. Label: zero lower bound, interest rate floor, liquidity trap region where money demand becomes horizontal (perfectly elastic).`,
      vocabulary: [
        {
          term: 'Liquidity Trap',
          definition: 'A situation in which nominal interest rates are at or near zero and monetary policy is ineffective because increases in money supply are simply held as idle cash rather than stimulating spending.',
          example: 'Japan in the 1990s–2000s: despite zero interest rates and massive money creation, households and firms hoarded cash, preventing the monetary stimulus from boosting AD.',
        },
        {
          term: 'Zero Lower Bound (ZLB)',
          definition: 'The practical floor for nominal interest rates near zero, below which further cuts lose effectiveness because cash holding becomes attractive and banks cannot pass significantly negative rates to depositors.',
          example: 'The Federal Reserve hit the ZLB in December 2008 and again in March 2020, making conventional rate cuts impossible and forcing reliance on quantitative easing and forward guidance.',
        },
        {
          term: 'Policy Lag',
          definition: 'The time delay between the need for a policy action and its full effect on the economy; includes the inside lag (recognition + decision) and outside lag (implementation → economic impact).',
          example: 'A Fed rate cut in January 2024 may not fully affect mortgage rates, investment, and GDP until late 2025 — an outside lag of 12–18 months that complicates countercyclical stabilisation.',
        },
      ],
      deeperDive: `The debate between **discretionary policy** and **rules-based policy** is a central controversy in macroeconomics. Advocates of discretion argue that policymakers should have flexibility to respond to unique economic circumstances — each recession is different and a one-size-fits-all rule may be inappropriate. Critics argue that discretion leads to **time inconsistency**: policymakers claim they will maintain low inflation but face incentives to inflate the economy for short-term employment gains, undermining credibility. The **Taylor Rule** — a formula prescribing the federal funds rate as a function of inflation deviations from target and the output gap — is the leading rules-based proposal. It suggests, for example, that rates should rise by 1.5 percentage points for every 1 percentage point increase in inflation above the 2% target.\n\nThe **fiscal multiplier** is also context-dependent. In a liquidity trap at the ZLB, empirical estimates suggest the fiscal multiplier can exceed 2 — meaning $1 of government spending raises GDP by more than $1, because monetary policy does not offset the stimulus with higher interest rates. By contrast, when the economy is near potential output and interest rates are normal, crowding out reduces the multiplier below 1. The composition of fiscal policy also matters: government purchases of goods and services (G) have a higher multiplier than tax cuts, because some of a tax cut is saved rather than spent. AP students should recognise that the effectiveness of fiscal and monetary policy depends critically on the state of the economy and the institutional constraints facing policymakers.`,
      commonMisconceptions: [
        'Thinking monetary policy is always more effective than fiscal policy: In a liquidity trap or at the ZLB, monetary policy loses potency. Fiscal policy may be the more effective tool precisely when the economy is deepest in recession and the need is greatest.',
        'Confusing inside and outside lags: Students often reverse them. Fiscal policy has a LONG inside lag (legislative process) and shorter outside lag. Monetary policy has a SHORT inside lag (Fed can act quickly) but LONG outside lag (12–18 months to fully affect GDP). The distinction matters for evaluating policy timeliness.',
        'Assuming the expenditure multiplier is always greater than 1: Crowding out (rising interest rates displacing private investment) can reduce the fiscal multiplier below 1. At full employment, with a vertical LRAS, fiscal stimulus is fully crowded out and the multiplier is zero in the long run — all the stimulus just raises the price level.',
      ],
      examinerTip: `AP FRQs on policy limitations frequently ask about the ZLB or policy lags. For ZLB questions: explain that the central bank cannot lower nominal rates below zero, so the interest-rate transmission mechanism breaks down, and identify fiscal policy or unconventional monetary tools (QE, forward guidance) as alternatives. For lag questions: correctly identify whether the scenario describes an inside lag (slow to respond) or outside lag (slow to take effect). Always connect back to the ultimate goal — closing the recessionary or inflationary gap — and explain which direction AD must shift to reach potential output.`,
      didYouKnow: `The term "pushing on a string" — often attributed to John Maynard Keynes — perfectly captures the liquidity trap: just as you can pull a string (tight monetary policy restrains the economy effectively) but cannot push it (easy monetary policy cannot force borrowing and spending), central banks find it easy to cool an overheating economy but much harder to stimulate one that is deeply depressed. Keynes made this argument in 1936 to justify fiscal stimulus during the Great Depression, and it remains central to macroeconomic debates today.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ap7-l4-fc1',
        front: 'What is the zero lower bound (ZLB) and why does it undermine conventional monetary policy?',
        back: 'The ZLB is the practical floor near zero for nominal interest rates. Below zero, households prefer holding cash (which yields 0%) to bank deposits with negative yields, causing bank runs and financial instability. At the ZLB, the central bank cannot further stimulate borrowing by cutting rates — the standard transmission mechanism breaks down, rendering conventional monetary policy ineffective.',
        hint: 'Ask: what happens when rates cannot go lower?',
        tags: ['zero-lower-bound', 'monetary-policy', 'liquidity-trap'],
      },
      {
        id: 'ap7-l4-fc2',
        front: 'Compare inside and outside policy lags for fiscal versus monetary policy.',
        back: 'Monetary policy: SHORT inside lag (Fed can cut rates at any FOMC meeting) + LONG outside lag (12–18 months to fully affect GDP). Fiscal policy: LONG inside lag (legislation requires Congressional debate, months–years) + SHORTER outside lag (once money is spent, multiplier effects begin quickly). Lags mean policy may take effect at the wrong point in the business cycle.',
        hint: "Inside lag = time to ACT. Outside lag = time for the action to AFFECT the economy.",
        tags: ['policy-lags', 'fiscal-policy', 'monetary-policy'],
      },
      {
        id: 'ap7-l4-fc3',
        front: 'Why might automatic stabilisers be preferred to discretionary fiscal policy for business cycle management?',
        back: 'Automatic stabilisers (progressive income taxes, unemployment insurance) respond immediately to economic conditions without legislative action — eliminating the inside lag entirely. In a recession, tax revenue automatically falls and transfer payments rise, injecting support into the economy before Congress can act. They also phase out automatically in recoveries, avoiding the over-stimulation risk of poorly timed discretionary policy.',
        hint: 'Key advantage: no inside lag — they activate automatically.',
        tags: ['automatic-stabilisers', 'fiscal-policy', 'policy-lags'],
      },
    ],
    quiz: [
      {
        id: 'ap7-l4-q1',
        type: 'mcq',
        question: 'In a liquidity trap, which of the following policy responses is most likely to effectively stimulate aggregate demand?',
        options: [
          'Expansionary fiscal policy (increased government spending), because it directly raises AD without relying on the interest rate channel.',
          'Raising the nominal interest rate, because it signals confidence in the economy.',
          'Reducing the money supply to raise real interest rates and encourage saving.',
          'Conventional open-market operations purchasing short-term Treasury bills.',
        ],
        correctAnswer: 0,
        explanation: 'In a liquidity trap, monetary policy is ineffective because nominal rates cannot fall further and money injections are hoarded. Fiscal policy bypasses the interest rate channel entirely — government spending directly adds to AD (G is a component of GDP). This is why Keynes advocated fiscal stimulus during the Great Depression and why QE had to be supplemented by fiscal stimulus in 2008–2009.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l4-q2',
        type: 'mcq',
        question: 'Which of the following best describes why monetary policy has a "long outside lag"?',
        options: [
          'It takes 12–18 months for interest rate changes to work through the economy via investment, consumption, and exchange rate channels before GDP is fully affected.',
          'The Federal Reserve takes many months to reach a consensus on changing interest rates.',
          'Congress must approve interest rate changes before they take effect.',
          'Higher interest rates immediately reduce government bond prices, causing a financial shock that takes time to resolve.',
        ],
        correctAnswer: 0,
        explanation: 'The outside lag of monetary policy refers to the time between the policy action and its full macroeconomic effect. Rate changes affect mortgages, business loans, exchange rates, and asset prices gradually. Businesses revise capital spending plans over quarters; housing market responses take time; exchange rate effects on trade take even longer. The full GDP effect typically takes 12–18 months.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l4-q3',
        type: 'mcq',
        question: 'The Taylor Rule prescribes that the central bank should set the nominal interest rate based on which of the following factors?',
        options: [
          'The deviation of inflation from its target and the deviation of real GDP from potential GDP (the output gap).',
          'The current federal budget deficit and the level of the national debt.',
          'The unemployment rate and the level of nominal wages.',
          'The exchange rate and the current account balance.',
        ],
        correctAnswer: 0,
        explanation: 'The Taylor Rule: federal funds rate = neutral rate + 0.5×(inflation gap) + 0.5×(output gap), where the inflation gap is actual minus target inflation and the output gap is actual minus potential GDP. It provides a rules-based benchmark for monetary policy, prescribing higher rates when inflation is above target or output is above potential, and lower rates in the opposite situations.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },

  // ── Lesson 5 ──────────────────────────────────────────────────────────────
  {
    id: 'ap7-l5',
    moduleId: 'ap7-growth',
    title: 'Open Economy Macroeconomics Review',
    description: 'Current account, capital flows, exchange rates, and how they connect to domestic fiscal and monetary policy in multi-market AP FRQs.',
    order: 5,
    estimatedMinutes: 35,
    tags: ['open-economy', 'current-account', 'capital-flows', 'exchange-rates', 'AP-macro'],
    content: {
      conceptualExplanation: `In an open economy, domestic macroeconomic policy ripples outward through the **balance of payments**, exchange rates, and international capital flows, creating feedback effects that partially offset or amplify the original policy impulse. The **current account** records trade in goods, services, income, and transfers. The **capital and financial account** records cross-border flows of investment. By the balance of payments identity, these must sum to zero: a current account deficit is financed by a capital account surplus (net capital inflows), and vice versa. This accounting identity means every trade deficit has a mirror-image capital inflow story — the U.S. consistently imports more than it exports in goods precisely because the world finds U.S. financial assets (Treasuries, equities, real estate) highly attractive.\n\nThe **exchange rate** is the linchpin connecting domestic policy to international outcomes. When the Federal Reserve raises interest rates, real returns on U.S. dollar-denominated assets rise relative to foreign assets. Foreign investors purchase dollars to buy U.S. bonds, increasing demand for dollars and causing the dollar to **appreciate** (each dollar buys more foreign currency). A stronger dollar makes U.S. exports more expensive in foreign markets (reducing export demand) and makes imports cheaper for American consumers (increasing import demand). The combined effect is a **fall in net exports (NX)**, reducing aggregate demand. This exchange rate channel partially neutralises tight monetary policy's intended contractionary effect — a subtlety tested in AP FRQs asking for complete policy chains.\n\nFiscal policy creates a parallel open-economy chain. Expansionary fiscal policy (deficit spending) increases demand for loanable funds, raising the real interest rate. Higher real rates attract foreign capital inflows, increasing demand for dollars and appreciating the dollar. The appreciated dollar reduces net exports — partially **crowding out** the original fiscal stimulus through the trade account. This "twin deficits" relationship — budget deficits tending to coincide with current account deficits — is one of the most important open-economy insights for AP Macroeconomics. Students must trace the full chain: fiscal policy → loanable funds → real interest rate → capital flows → exchange rate → net exports → aggregate demand.`,
      prerequisiteRecap: `Lesson 4 examined the limits of stabilisation policy — the zero lower bound, policy lags, and the rules-versus-discretion debate. Lesson 5 now opens the economy internationally, tracing how the same fiscal and monetary tools produce additional effects via capital flows, exchange rates, and the current account, completing the full multi-market FRQ chain.`,
      recallQuestions: [
        {
          id: 'ap7-l5-recall-1',
          type: 'mcq' as const,
          question: 'Monetary policy has a short inside lag but a long outside lag. Which of the following best explains why the outside lag of monetary policy is 12–18 months?',
          options: [
            'Interest rate changes affect mortgages, business investment plans, exchange rates, and asset prices gradually, and businesses revise capital spending over many quarters before GDP fully responds',
            'The Federal Reserve must obtain Congressional approval before rate changes take effect, causing a long implementation delay',
            'Banks immediately pass rate changes to borrowers, but households take 12–18 months to read their new loan statements',
            'The outside lag reflects the time for the Federal Reserve to recognise that a recession has begun and decide to act',
          ],
          correctAnswer: 0,
          explanation: 'The outside lag is the time between the policy action and its full macroeconomic effect. Rate changes affect the cost of variable-rate mortgages and business loans gradually; firms revise multi-year capital spending plans over several quarters; exchange rate effects on export and import volumes take further time to materialise; and the housing market responds slowly to mortgage rate changes. The cumulative effect on GDP typically takes 12–18 months. Congressional approval (option B) describes fiscal policy\'s inside lag, not monetary policy\'s outside lag.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `The "strong dollar" of 2022–2023 provides a vivid real-world illustration. As the Federal Reserve raised rates aggressively to combat inflation, the U.S. dollar index appreciated by over 15% against a basket of currencies. American manufacturers complained of lost export competitiveness — a Boeing aircraft became dramatically more expensive in euros or yen. Meanwhile, countries holding dollar-denominated debt (many emerging markets borrow in USD) faced soaring debt service costs, triggering currency crises in Sri Lanka, Pakistan, and Argentina. This episode demonstrates how U.S. monetary policy, through the exchange rate channel, generates powerful spillovers into the global economy — the open-economy feedback the AP curriculum's multi-market FRQs are designed to test.`,
      interactiveElement: `**Full Policy Chain Diagram — Expansionary Fiscal Policy in an Open Economy:**\n\nTrace the complete chain with five mini-diagrams connected by arrows:\n\n1. **Loanable Funds Market:** G↑ → demand for loanable funds shifts RIGHT → real interest rate rises (r* → r**). Label: Supply (private saving), Demand₁ → Demand₂, r*, r**, E₁, E₂.\n\n2. **Capital Flows Arrow:** Higher r** → foreign investors demand more U.S. assets → net capital INFLOWS rise → demand for USD increases.\n\n3. **Foreign Exchange Market:** Demand for USD shifts RIGHT → dollar appreciates (exchange rate rises from e* to e**). Label: Supply of USD, Demand₁ → Demand₂, e*, e**, E₁, E₂.\n\n4. **Net Exports Effect:** Stronger dollar → U.S. exports more expensive → U.S. imports cheaper → NX falls (trade deficit widens).\n\n5. **AD/AS Model:** NX↓ partially offsets the original G↑ → AD shift is smaller than domestic multiplier alone predicts. Label: AD₁, AD₂ (smaller than it would be in closed economy), LRAS, SRAS, P*, Y*.\n\n**Key conclusion to write:** "Expansionary fiscal policy is partially crowded out in an open economy via the exchange rate channel — rising real interest rates attract capital inflows, appreciate the currency, and reduce net exports."`,
      vocabulary: [
        {
          term: 'Current Account',
          definition: 'The component of the balance of payments recording trade in goods, services, income flows, and transfer payments; a surplus means more is earned from abroad than paid out; a deficit is the reverse.',
          example: 'The U.S. current account deficit of ~$800 billion in 2022 means Americans imported $800B more in goods, services, and income than they exported — financed by foreigners investing that amount in U.S. assets.',
        },
        {
          term: 'Capital and Financial Account',
          definition: 'The balance of payments component recording cross-border purchases and sales of financial and real assets; a surplus (capital inflows exceed outflows) finances a current account deficit.',
          example: 'When foreign central banks, sovereign wealth funds, and private investors buy U.S. Treasury bonds, they create a capital account surplus that finances the U.S. current account deficit.',
        },
        {
          term: 'Exchange Rate Appreciation',
          definition: 'An increase in the value of one currency relative to another; the domestic currency buys more foreign currency, making exports more expensive and imports cheaper.',
          example: 'If the dollar appreciates from 1.10 to 1.25 dollars per euro, a $100,000 U.S. machine now costs Europeans €80,000 instead of €91,000 — fewer European buyers can afford it, reducing U.S. export revenue.',
        },
      ],
      deeperDive: `The **Mundell-Fleming model** extends the standard AD/AS framework to an open economy with perfect capital mobility and either fixed or flexible exchange rates. Under flexible exchange rates (the relevant case for AP), the key result is that **fiscal policy is largely ineffective** in the long run in a small open economy: the crowding out via the exchange rate is complete — every dollar of extra government spending is offset by a dollar less in net exports. Monetary policy, by contrast, is highly effective: lower interest rates depreciate the currency, boosting net exports and amplifying the domestic stimulus. This is the exact opposite of the closed-economy result, where fiscal policy has a multiplier but monetary policy works only indirectly.\n\nThe **twin deficits hypothesis** posits that budget deficits and current account deficits tend to move together. The theoretical chain is: budget deficit → lower national saving → higher real interest rates → capital inflows → dollar appreciation → reduced NX → current account deficit. Empirical evidence is mixed — the relationship holds in some periods (1980s U.S.) but not others (2000s, when global saving glut played a large role). Nevertheless, the twin deficits chain is a central AP FRQ narrative and should be memorised as a complete, multi-market sequence. AP examiners frequently construct FRQs that require students to trace a fiscal policy change through loanable funds, forex, and the current account in exactly this sequence.`,
      commonMisconceptions: [
        'Confusing currency appreciation and depreciation effects on net exports: Appreciation makes exports MORE expensive (foreign buyers pay more) and imports CHEAPER (domestic buyers pay less) — NX FALLS. Depreciation is the opposite. Students often reverse these; draw the forex market and track prices explicitly.',
        'Thinking capital inflows are always good for the current account: Capital inflows (capital account surplus) finance a current account DEFICIT — they are two sides of the same coin. More foreign investment in the U.S. is associated with a larger trade deficit, not a smaller one. The balance of payments identity CA + KA = 0 makes this a matter of accounting.',
        'Assuming domestic monetary policy has no international spillovers: A U.S. rate hike raises global interest rates through capital flows, appreciates the dollar, and can trigger currency crises in emerging markets with dollar-denominated debt. The Fed\'s decisions are the most important single factor in global financial conditions — ignoring spillovers misses a major dimension of open-economy macro.',
      ],
      examinerTip: `Open economy FRQs almost always test a multi-step chain. Memorise these two chains and practise them until automatic:\n\n**Chain 1 — Tight Monetary Policy:** Fed raises rates → money market: interest rate rises → capital inflows → forex: dollar appreciates → NX falls → AD shifts left (partially offsets tightening).\n\n**Chain 2 — Expansionary Fiscal Policy:** G↑ → loanable funds: real r rises → capital inflows → forex: dollar appreciates → NX falls → partially offsets the fiscal expansion (open-economy crowding out).\n\nFor each diagram in the chain, label axes, show curve shifts, mark E₁ and E₂, and state the direction of change in the key variable. Award yourself a point for each correctly labeled diagram and each verbal explanation of the mechanism.`,
      didYouKnow: `The U.S. dollar's status as the world's dominant **reserve currency** — held by central banks globally as the primary international asset — gives the United States an "exorbitant privilege" (a term coined by French Finance Minister Valéry Giscard d'Estaing in the 1960s). Because global demand for dollars is structurally high — countries need dollars to trade oil, finance international debt, and hold reserves — the U.S. can run persistent current account deficits without triggering a currency crisis that would afflict any other country. This reserve currency premium is estimated to save the U.S. government tens of billions of dollars per year in lower borrowing costs.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ap7-l5-fc1',
        front: 'State the balance of payments identity and explain what it implies about trade deficits.',
        back: 'CA + KA = 0. A current account deficit (imports > exports) must be exactly matched by a capital account surplus (net capital inflows — foreigners invest more in the country than residents invest abroad). A trade deficit is not independently "bad" — it is always financed by foreign willingness to hold the country\'s assets. The U.S. trade deficit reflects global demand for dollar-denominated assets.',
        hint: 'CA + KA = 0 is an accounting identity — it always holds.',
        tags: ['current-account', 'capital-flows', 'balance-of-payments'],
      },
      {
        id: 'ap7-l5-fc2',
        front: 'Trace the full chain from expansionary fiscal policy to the current account in an open economy.',
        back: 'G↑ → loanable funds demand rises → real interest rate rises → capital inflows increase (foreign investors seek higher yields) → demand for domestic currency rises → exchange rate appreciates → exports become more expensive abroad, imports become cheaper domestically → NX falls → current account deficit widens. This is the "twin deficits" mechanism.',
        hint: 'Five steps: G → r → capital → exchange rate → NX.',
        tags: ['fiscal-policy', 'exchange-rates', 'current-account', 'AP-macro'],
      },
      {
        id: 'ap7-l5-fc3',
        front: 'How does a domestic interest rate increase affect the exchange rate, and what is the effect on net exports?',
        back: 'Higher domestic interest rate → higher real returns on domestic assets → foreign investors convert their currencies into domestic currency to buy domestic bonds → demand for domestic currency rises → exchange rate APPRECIATES → domestic exports become more expensive for foreigners (export volume falls) → imports become cheaper for domestic consumers (import volume rises) → NET EXPORTS FALL (NX↓).',
        hint: 'Higher r → capital inflows → currency up → NX down.',
        tags: ['exchange-rates', 'net-exports', 'monetary-policy'],
      },
    ],
    quiz: [
      {
        id: 'ap7-l5-q1',
        type: 'mcq',
        question: 'The United States runs a large current account deficit. According to the balance of payments identity, this necessarily implies:',
        options: [
          'A capital account surplus of equal magnitude: foreigners are net purchasers of U.S. assets.',
          'A capital account deficit: U.S. investors are purchasing more foreign assets than foreigners buy in the U.S.',
          'A federal budget deficit equal in size to the trade deficit.',
          'A depreciation of the dollar to restore trade balance.',
        ],
        correctAnswer: 0,
        explanation: 'The balance of payments identity CA + KA = 0 requires that a current account deficit be exactly matched by a capital account surplus. Foreigners must be net purchasers of U.S. assets (stocks, bonds, real estate, FDI) in an amount exactly equal to the excess of U.S. imports over exports. This is an accounting identity, not a policy choice.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l5-q2',
        type: 'mcq',
        question: 'An economy with a flexible exchange rate runs expansionary fiscal policy. In the open-economy Mundell-Fleming framework, the long-run effect on net exports is:',
        options: [
          'Net exports fall, because higher real interest rates appreciate the currency and make exports less competitive.',
          'Net exports rise, because higher income from the fiscal stimulus increases import demand from trading partners.',
          'Net exports are unchanged, because the exchange rate adjustment is exactly offset by the income effect.',
          'Net exports rise, because government spending directly substitutes for imports.',
        ],
        correctAnswer: 0,
        explanation: 'Expansionary fiscal policy → demand for loanable funds rises → real interest rate rises → capital inflows → currency appreciates → exports more expensive, imports cheaper → NX falls. In the Mundell-Fleming model with perfect capital mobility and flexible exchange rates, this open-economy crowding out via the exchange rate is complete in the long run: NX falls by exactly as much as G rises, leaving total AD unchanged.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ap7-l5-q3',
        type: 'mcq',
        question: 'If the Federal Reserve raises the federal funds rate significantly above rates in other major economies, which sequence of effects correctly describes the international transmission?',
        options: [
          'Capital inflows rise → demand for dollars increases → dollar appreciates → U.S. exports fall and imports rise → U.S. current account deficit widens.',
          'Capital outflows rise → supply of dollars increases → dollar depreciates → U.S. exports rise and imports fall → U.S. current account deficit narrows.',
          'Capital inflows rise → supply of dollars increases → dollar depreciates → U.S. net exports rise.',
          'No international effect, because the Federal Reserve only controls domestic monetary conditions.',
        ],
        correctAnswer: 0,
        explanation: 'Higher U.S. rates offer better returns on dollar assets. Foreign investors convert their currencies to dollars (capital inflows), increasing demand for dollars and appreciating the dollar. A stronger dollar makes U.S. exports more expensive abroad and imports cheaper at home, reducing NX and widening the current account deficit. This is the standard open-economy monetary policy transmission chain tested on AP FRQs.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },
]
