import type { Lesson } from '@/lib/types'

export const moduleInfo = {
  id: 'i3-factor-markets',
  title: 'Factor Markets and Income Distribution',
  description: 'Understand how wages, rent, and interest are determined and why incomes are unequal.',
  tier: 'INTERMEDIATE' as const,
  track: 'INTERMEDIATE' as const,
  unit: 3,
  estimatedHours: 3,
  color: '#3b82f6',
  icon: 'TrendingUp',
}

export const lessons: Lesson[] = [
  // ── Lesson 1 ─────────────────────────────────────────────────────────────────
  {
    id: 'i3-l1',
    moduleId: 'i3-factor-markets',
    title: 'Labour Demand — Marginal Revenue Product',
    description:
      "Derive the firm's demand for labour from the MRP principle; show how wage changes affect employment.",
    order: 1,
    estimatedMinutes: 30,
    tags: ['labour-demand', 'MRP', 'factor-markets'],
    content: {
      isStub: false,
      prerequisiteRecap: `The previous module concluded by comparing all four market structures on allocative efficiency (P = MC), productive efficiency (min ATC), and dynamic efficiency. Perfect competition achieves both static criteria but earns zero profit; monopoly fails both static criteria but may fund R&D. Factor markets now apply the same efficiency logic to input markets — asking what determines how much labour, capital, and land firms demand, and how those factor prices are set.`,
      recallQuestions: [
        {
          id: 'i3-l1-recall-1',
          type: 'mcq' as const,
          question: 'Allocative efficiency is achieved when:',
          options: [
            'Price equals marginal cost, ensuring every unit whose value to consumers exceeds its production cost is produced.',
            'A firm produces at the minimum point of its average total cost curve.',
            'The firm earns zero economic profit in the long run.',
            'There is no deadweight loss from price discrimination.',
          ],
          correctAnswer: 0,
          explanation: 'Allocative efficiency (P = MC) means resources flow to their highest-valued use — no mutually beneficial transaction is missed. This is the benchmark against which market structures are judged, and which perfect competition achieves in long-run equilibrium.',
          marks: 1,
          difficulty: 'foundation' as const,
        },
      ],
      realWorldHook:
        'Amazon decides how many warehouse workers to hire during the holiday season not by gut feel, but by comparing the extra revenue each additional worker generates against the wage it must pay. When the marginal revenue generated by the last worker hired exactly equals the hourly wage, Amazon stops hiring — a textbook illustration of profit-maximising labour demand in action.',
      conceptualExplanation:
        'In product markets firms decide how much output to sell; in factor markets they decide how many inputs to hire. The key concept linking the two is the Marginal Revenue Product of Labour (MRP\u1d38). MRP\u1d38 is calculated as the Marginal Physical Product of Labour (MPP\u1d38) multiplied by the Marginal Revenue (MR) of the product being sold: MRP\u1d38 = MPP\u1d38 × MR. Because of diminishing marginal returns, each successive worker adds less to output than the previous one, so MRP\u1d38 falls as employment rises. This downward-sloping MRP\u1d38 curve is the firm\'s demand curve for labour.\n\nA profit-maximising firm will hire workers up to the point where MRP\u1d38 equals the wage rate (W). If MRP\u1d38 > W, hiring an extra worker adds more to revenue than to cost, so profit rises. If MRP\u1d38 < W, the last worker costs more than they contribute, so the firm should reduce employment. Equilibrium is therefore where MRP\u1d38 = W, which is why the MRP\u1d38 schedule is simultaneously the firm\'s demand curve for labour — at any given wage, the firm reads off the quantity of labour demanded from the MRP\u1d38 curve.\n\nShifts in the labour demand curve are caused by changes in the factors that determine MRP\u1d38. An increase in product price raises MR and therefore MRP\u1d38, shifting the curve right and increasing labour demand at every wage. Advances in technology that raise worker productivity (MPP\u1d38) have the same effect. Conversely, a fall in product demand, or a rise in the productivity of substitute inputs (e.g. automation), shifts the curve left. Understanding these shifters is essential for explaining why real wages have risen in high-skill sectors and stagnated in sectors exposed to technological displacement.',
      vocabulary: [
        {
          term: 'Marginal Revenue Product of Labour (MRP\u1d38)',
          definition:
            'The additional revenue a firm earns by hiring one more unit of labour, equal to MPP\u1d38 × MR.',
          example:
            'If a barista serves 20 extra coffees per hour (MPP\u1d38) and each coffee sells for £3 (MR = price in perfect competition), MRP\u1d38 = £60. The café will hire this barista only if the hourly wage is at or below £60.',
        },
        {
          term: 'Marginal Physical Product of Labour (MPP\u1d38)',
          definition: 'The extra output produced when one additional unit of labour is employed, all else equal.',
          example:
            'A fifth chef in a small kitchen adds 15 meals per shift to output; that is the fifth chef\'s MPP\u1d38. A sixth chef, cramped for space, may add only 10 meals — illustrating diminishing marginal returns.',
        },
        {
          term: 'Derived Demand',
          definition:
            'Demand for a factor of production that arises indirectly from the demand for the good or service the factor helps to produce.',
          example:
            'Demand for bricklayers is derived from demand for new housing. A housing-market boom directly increases the demand for bricklayers without any change in wages or bricklayer productivity.',
        },
      ],
      examinerTip:
        'Examiners frequently ask you to "derive" or "explain" the firm\'s demand curve for labour — always link MRP\u1d38 explicitly to both MPP\u1d38 and MR, and state the profit-maximising condition MRP\u1d38 = W. When asked why the labour demand curve slopes downward, cite diminishing marginal returns to labour (not diminishing marginal utility). For diagram questions, label the axes "Wage (W)" and "Quantity of Labour (L)", draw a downward-sloping MRP\u1d38 curve, and mark the equilibrium employment level at the intersection of MRP\u1d38 and the horizontal wage line.',
    },
    flashcards: [
      {
        id: 'i3-l1-fc1',
        front: 'What is the formula for the Marginal Revenue Product of Labour?',
        back: 'MRP\u1d38 = MPP\u1d38 × MR. It measures the extra revenue generated by hiring one more unit of labour.',
        hint: 'Think of it as two steps: extra output × revenue per unit of output.',
        tags: ['MRP', 'labour-demand', 'formula'],
      },
      {
        id: 'i3-l1-fc2',
        front: "What is a firm's profit-maximising hiring rule?",
        back: 'Hire labour up to the point where MRP\u1d38 = W (wage). Hiring beyond this makes the marginal worker more costly than their revenue contribution.',
        hint: 'It mirrors the output rule: produce where MR = MC.',
        tags: ['labour-demand', 'profit-maximisation'],
      },
      {
        id: 'i3-l1-fc3',
        front: 'Why does the labour demand curve slope downward?',
        back: 'Because of diminishing marginal returns: as more labour is added (with capital fixed), each extra worker adds less to output (MPP\u1d38 falls), so MRP\u1d38 falls.',
        hint: 'Diminishing returns to the variable factor.',
        tags: ['labour-demand', 'diminishing-returns'],
      },
      {
        id: 'i3-l1-fc4',
        front: 'Name two factors that shift the labour demand curve to the right.',
        back: '1. An increase in the price of the product (raises MR, so MRP\u1d38 rises at every employment level). 2. A rise in worker productivity / technological improvement (raises MPP\u1d38, so MRP\u1d38 rises).',
        hint: 'MRP\u1d38 = MPP\u1d38 × MR — anything that raises either component shifts demand right.',
        tags: ['labour-demand', 'demand-shifters'],
      },
    ],
    quiz: [
      {
        id: 'i3-l1-q1',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'A competitive firm sells its output at £10 per unit. A sixth worker increases total output from 80 to 88 units. What is the MRP\u1d38 of the sixth worker?',
        options: ['£8', '£80', '£88', '£800'],
        correctAnswer: 1,
        explanation:
          'MPP\u1d38 = 88 − 80 = 8 units. In perfect competition MR = price = £10. Therefore MRP\u1d38 = 8 × £10 = £80.',
      },
      {
        id: 'i3-l1-q2',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question: 'Which of the following will shift a firm\'s labour demand curve to the LEFT?',
        options: [
          'An increase in the price of the firm\'s product',
          'A fall in the productivity of workers',
          'A reduction in the wage rate',
          'An increase in consumer demand for the firm\'s output',
        ],
        correctAnswer: 1,
        explanation:
          'A fall in worker productivity lowers MPP\u1d38 and therefore MRP\u1d38 at every level of employment, shifting the entire labour demand (MRP\u1d38) curve left. A wage change causes a movement along the curve, not a shift.',
      },
      {
        id: 'i3-l1-q3',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question: 'Labour demand is described as "derived demand" because:',
        options: [
          'it is derived from the supply of capital in the economy',
          'it is derived from the demand for the goods and services labour helps to produce',
          'wages are derived from government minimum wage legislation',
          'it is derived from the marginal cost of production',
        ],
        correctAnswer: 1,
        explanation:
          'Derived demand means factor demand flows indirectly from product demand. Firms do not hire labour for its own sake; they hire it because consumers demand the goods labour produces. Hence labour demand is derived from product demand.',
      },
    ],
  },

  // ── Lesson 2 ─────────────────────────────────────────────────────────────────
  {
    id: 'i3-l2',
    moduleId: 'i3-factor-markets',
    title: 'Labour Supply and Wage Determination',
    description:
      'Explain individual and market labour supply, the backward-bending supply curve, and how wages are set.',
    order: 2,
    estimatedMinutes: 30,
    tags: ['labour-supply', 'wages', 'monopsony'],
    content: {
      isStub: false,
      prerequisiteRecap: `The previous lesson derived the firm's demand for labour from the Marginal Revenue Product (MRP_L = MPP_L × MR) and showed that the profit-maximising hiring rule is MRP_L = W, making the MRP_L curve the labour demand curve. Labour supply now completes the picture, allowing us to determine the equilibrium wage in both competitive and monopsonistic markets.`,
      recallQuestions: [
        {
          id: 'i3-l2-recall-1',
          type: 'mcq' as const,
          question: 'A competitive firm sells its output at £8 per unit. A seventh worker increases total output from 100 to 112 units. What is the MRP_L of the seventh worker?',
          options: [
            '£96',
            '£8',
            '£112',
            '£800',
          ],
          correctAnswer: 0,
          explanation: 'MPP_L = 112 − 100 = 12 units. In perfect competition MR = price = £8. Therefore MRP_L = 12 × £8 = £96. The firm will hire this worker only if the wage is at or below £96.',
          marks: 1,
          difficulty: 'foundation' as const,
        },
      ],
      realWorldHook:
        'During the COVID-19 pandemic, many hospitality and logistics workers who had been furloughed decided not to return to work even as wages rose sharply. Economists recognised this as a real-world manifestation of the backward-bending labour supply curve: once workers\' incomes were high enough (or their preferences changed), they chose leisure over additional hours — exactly what the income effect over the substitution effect predicts.',
      conceptualExplanation:
        'Individual labour supply reflects a worker\'s choice between income (earned through work) and leisure (time not worked). At low wages the substitution effect dominates: higher wages make leisure relatively more expensive, so the worker substitutes work for leisure and supplies more hours. However, as wages rise further the income effect begins to dominate: the worker is already earning a high income, so they "buy" more leisure by reducing hours worked. The result is the backward-bending individual supply curve, which slopes upward at low wages and bends back (slopes upward to the left) at high wages.\n\nThe market supply of labour is the horizontal summation of all individual supply curves within a market or occupation. It generally slopes upward because higher wages attract workers from other industries, bring discouraged workers back into the labour force, and encourage longer hours at the margin. Key determinants of market labour supply include the size and age structure of the population, participation rates (especially among women and older workers), immigration levels, skill levels and education, and non-wage factors such as working conditions and social status.\n\nWage determination varies by market structure. In a perfectly competitive labour market, many firms and many workers interact so that both are wage-takers; the equilibrium wage clears the market. A monopsonist — a single employer — faces the entire upward-sloping market supply curve and must raise wages to attract more workers. Because the wage must rise for all workers (not just the marginal one), the marginal cost of labour (MCL) lies above the supply curve. The monopsonist maximises profit by setting MRP\u1d38 = MCL, resulting in both lower wages and lower employment than a competitive market would produce.',
      vocabulary: [
        {
          term: 'Backward-Bending Labour Supply Curve',
          definition:
            'A labour supply curve that slopes upward at lower wages (substitution effect dominates) but bends back and slopes leftward at higher wages (income effect dominates), indicating fewer hours supplied as wages rise beyond a threshold.',
          example:
            'A freelance designer charges £40/hour and works 40 hours a week. When offered £100/hour she cuts back to 25 hours, maintaining similar income while gaining leisure time — the curve has bent backward.',
        },
        {
          term: 'Monopsony',
          definition:
            'A labour market with a single (or dominant) buyer of labour, giving that employer wage-setting power below the competitive equilibrium wage.',
          example:
            'A coal mine that is the sole employer in a remote town is a classic monopsonist: miners have no alternative employer nearby, so the firm can set wages below what a competitive market would pay.',
        },
        {
          term: 'Participation Rate',
          definition:
            'The proportion of a population of working age that is either employed or actively seeking employment.',
          example:
            'If a country has 50 million people of working age and 35 million are working or job-hunting, the participation rate is 70%. Policy changes such as subsidised childcare can raise participation by enabling more parents to enter the workforce.',
        },
      ],
      examinerTip:
        'For the backward-bending supply curve, always explain the income and substitution effects separately — examiners deduct marks for vague answers. Draw the curve clearly: label the "normal" upward-sloping section (substitution effect > income effect) and the backward-bending section (income effect > substitution effect). For monopsony questions, remember to draw both the supply curve (S = ACL) and the marginal cost of labour (MCL) above it, then identify the profit-maximising quantity (MRP\u1d38 = MCL) and the corresponding wage on the supply curve — not on the MRP\u1d38 curve.',
    },
    flashcards: [
      {
        id: 'i3-l2-fc1',
        front: 'Why does the individual labour supply curve eventually bend backward?',
        back: 'At high enough wages the income effect (desire for more leisure as real income rises) outweighs the substitution effect (incentive to work more because leisure is expensive). The worker chooses fewer hours despite higher pay.',
        hint: 'Income effect vs. substitution effect — which dominates at high wages?',
        tags: ['labour-supply', 'backward-bending', 'income-effect'],
      },
      {
        id: 'i3-l2-fc2',
        front: 'State THREE determinants of the market supply of labour.',
        back: '1. Population size and age structure. 2. Participation rate (proportion of working-age population active in the labour market). 3. Net immigration / emigration flows. (Also acceptable: education/skill levels, non-wage factors such as working conditions.)',
        hint: 'Think about who is available to work and what affects their willingness to enter the market.',
        tags: ['labour-supply', 'market-supply'],
      },
      {
        id: 'i3-l2-fc3',
        front: 'What is monopsony and what does it do to wages and employment?',
        back: 'Monopsony is a market with a single (dominant) buyer of labour. Because the employer must raise wages for all workers to attract one more, MCL > wage. Setting MRP\u1d38 = MCL gives LOWER employment and LOWER wages than a competitive market.',
        hint: 'Compare MCL with the supply curve position.',
        tags: ['monopsony', 'wages'],
      },
      {
        id: 'i3-l2-fc4',
        front: "In a competitive labour market, how is the equilibrium wage determined?",
        back: 'By the intersection of market labour demand (sum of firms\' MRP\u1d38 curves) and market labour supply. Both firms and workers are wage-takers; the equilibrium wage equates quantity of labour demanded with quantity supplied.',
        hint: 'Standard supply-demand equilibrium applied to the labour market.',
        tags: ['wages', 'competitive-market'],
      },
    ],
    quiz: [
      {
        id: 'i3-l2-q1',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'At high wage levels an individual worker reduces hours supplied. This is best explained by:',
        options: [
          'the substitution effect exceeding the income effect',
          'the income effect exceeding the substitution effect',
          'an increase in the marginal revenue product of labour',
          'a rise in the participation rate',
        ],
        correctAnswer: 1,
        explanation:
          'When wages are high, the worker already has substantial income. A further wage rise makes the worker feel wealthy enough to "buy" leisure, reducing hours supplied. This is the income effect dominating the substitution effect, producing the backward-bending portion of the supply curve.',
      },
      {
        id: 'i3-l2-q2',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'Compared with a competitive labour market, a monopsonist will set:',
        options: [
          'higher wages and higher employment',
          'higher wages and lower employment',
          'lower wages and higher employment',
          'lower wages and lower employment',
        ],
        correctAnswer: 3,
        explanation:
          'A monopsonist equates MRP\u1d38 with MCL (not the wage). Since MCL lies above the supply curve, the profit-maximising employment level is lower than in competition, and the wage — read from the supply curve — is also lower.',
      },
      {
        id: 'i3-l2-q3',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question: 'Which of the following would INCREASE the market supply of labour in the nursing profession?',
        options: [
          'A reduction in immigration of trained nurses',
          'An increase in the length and cost of nursing qualifications',
          'A government programme that subsidises nursing degrees',
          'A fall in the wage rate for nurses',
        ],
        correctAnswer: 2,
        explanation:
          'Subsidising nursing degrees lowers the cost of entering the profession, attracting more people to train as nurses and increasing market supply. The other options reduce supply (lower immigration, higher qualification costs) or represent a movement along the supply curve (lower wage).',
      },
    ],
  },

  // ── Lesson 3 ─────────────────────────────────────────────────────────────────
  {
    id: 'i3-l3',
    moduleId: 'i3-factor-markets',
    title: 'Trade Unions, Minimum Wages, and Market Power',
    description:
      'Analyse wage floors, bilateral monopoly, and conditions under which minimum wages may not reduce employment.',
    order: 3,
    estimatedMinutes: 25,
    tags: ['trade-unions', 'minimum-wage', 'bilateral-monopoly'],
    content: {
      isStub: false,
      prerequisiteRecap: `The previous lesson showed that individual labour supply eventually bends backward when the income effect outweighs the substitution effect, and that a monopsonist — the sole employer — sets wages below the competitive level by equating MRP_L with the marginal cost of labour (MCL), which lies above the supply curve. This lesson examines how trade unions and minimum wages interact with those market power dynamics.`,
      recallQuestions: [
        {
          id: 'i3-l3-recall-1',
          type: 'mcq' as const,
          question: 'Compared with a competitive labour market, a monopsonist will set:',
          options: [
            'Lower wages and lower employment.',
            'Higher wages and lower employment.',
            'Lower wages and higher employment.',
            'Higher wages and higher employment.',
          ],
          correctAnswer: 0,
          explanation: 'A monopsonist maximises profit by setting MRP_L = MCL, where MCL lies above the supply (ACL) curve. The profit-maximising employment level is below the competitive level, and the corresponding wage — read from the supply curve — is also below the competitive wage.',
          marks: 1,
          difficulty: 'foundation' as const,
        },
      ],
      realWorldHook:
        'The UK\'s National Living Wage was raised to £11.44 per hour in April 2024. Mainstream economic theory predicted higher unemployment, yet the Office for Budget Responsibility and independent researchers found only modest employment effects. Why? Because many UK labour markets — especially hospitality and retail — are dominated by a small number of large employers with monopsonistic wage-setting power. The minimum wage counteracts that power rather than simply creating a surplus of labour.',
      conceptualExplanation:
        'A trade union acts as a monopoly seller of labour: it can push wages above the competitive equilibrium by threatening strike action. In a competitive market this creates a wage floor above the market-clearing wage, and standard theory predicts a fall in employment as firms move up their MRP\u1d38 curves. The size of the employment loss depends on the wage elasticity of labour demand: the more elastic demand is, the greater the reduction in employment for a given wage rise. Unions therefore tend to be stronger in industries where demand for labour is inelastic — where there are few substitutes for union labour, where labour costs form a small share of total costs, or where product demand is itself inelastic.\n\nA minimum wage set above the equilibrium wage is also a wage floor. In a perfectly competitive labour market, basic analysis predicts unemployment equal to the gap between quantity supplied and quantity demanded at the new wage. However, this conclusion reverses when the employer has monopsony power. A monopsonist pays below the competitive wage; introducing a minimum wage at or below the competitive wage forces the monopsonist to pay more without reducing employment — it may actually increase both wages and employment simultaneously by eliminating the monopsonist\'s ability to exploit workers.\n\nBilateral monopoly arises when a monopsonist employer faces a monopoly union. The union wants the highest feasible wage (where MRP\u1d38 = labour supply) while the employer wants the lowest (where MRP\u1d38 = MCL). The final wage lies somewhere between these two extremes, determined by the relative bargaining power of each party — factors such as strike funds, profit margins, the cost of replacing workers, and public sympathy. Bilateral monopoly produces an indeterminate wage range, which is why collective bargaining outcomes vary widely across otherwise similar industries.',
      vocabulary: [
        {
          term: 'Wage Floor (Minimum Wage)',
          definition:
            'A legally imposed minimum price for labour, set above the free-market equilibrium wage, intended to guarantee a minimum income to workers.',
          example:
            'If the equilibrium wage for entry-level retail workers is £9/hour and the government sets a minimum wage of £11.44/hour, the wage floor is £2.44 above equilibrium.',
        },
        {
          term: 'Bilateral Monopoly',
          definition:
            'A market structure in which a single buyer (monopsonist employer) faces a single seller (monopoly union), so that the equilibrium wage is determined by bargaining rather than market forces alone.',
          example:
            'In some national railway systems a single state employer negotiates directly with a single rail workers\' union. Neither side can turn to alternative buyers or sellers, making the wage the result of relative bargaining strength.',
        },
        {
          term: 'Wage Elasticity of Labour Demand',
          definition:
            'The percentage change in quantity of labour demanded divided by the percentage change in the wage rate; it measures how responsive employment is to wage changes.',
          example:
            'If a 10% wage rise causes a 5% fall in employment, wage elasticity of labour demand = −0.5 (inelastic). Industries with inelastic labour demand — such as highly specialised surgery — can sustain wage increases with little employment loss.',
        },
      ],
      examinerTip:
        'A common exam error is to state that minimum wages always reduce employment — always qualify this: in a competitive market they do; in a monopsonistic market they can increase both wages and employment. Examiners reward nuanced, model-specific analysis. For bilateral monopoly, show two key wages on the diagram: the union\'s preferred wage (where MRP\u1d38 intersects S) and the employer\'s preferred wage (where MRP\u1d38 intersects MCL), and state the outcome is indeterminate between these bounds.',
    },
    flashcards: [
      {
        id: 'i3-l3-fc1',
        front: 'Under what condition might a minimum wage INCREASE employment rather than reduce it?',
        back: 'When the labour market is monopsonistic. A monopsonist pays below the competitive wage; a minimum wage set between the monopsony wage and the competitive wage forces the employer to pay more and can increase employment toward the competitive level.',
        hint: 'Think about what a monopsonist does to wages relative to the competitive outcome.',
        tags: ['minimum-wage', 'monopsony', 'employment'],
      },
      {
        id: 'i3-l3-fc2',
        front: 'What factors make labour demand more INELASTIC, strengthening a trade union\'s bargaining position?',
        back: '1. Few substitutes for labour in production. 2. Labour costs are a small share of total production costs. 3. Product demand is itself inelastic. 4. Difficulty replacing union workers in the short run.',
        hint: 'Hicks–Marshall laws of derived demand.',
        tags: ['trade-unions', 'labour-demand', 'elasticity'],
      },
      {
        id: 'i3-l3-fc3',
        front: 'Define bilateral monopoly and explain why the wage outcome is indeterminate.',
        back: 'Bilateral monopoly: a single employer (monopsonist) faces a single union (monopoly seller of labour). The union seeks the wage where MRP\u1d38 = S; the employer seeks the wage where MRP\u1d38 = MCL. The actual wage falls between these two points, determined solely by relative bargaining power — it cannot be pinned down by market forces alone.',
        hint: 'Two monopolies on opposite sides of the market.',
        tags: ['bilateral-monopoly', 'trade-unions', 'wages'],
      },
      {
        id: 'i3-l3-fc4',
        front: 'How does a trade union raise wages above the competitive level in a competitive labour market, and what is the predicted employment effect?',
        back: 'The union acts as a monopoly supplier of labour, restricting supply or threatening strikes to force a wage above equilibrium. At the higher wage, quantity of labour demanded falls (movement up the MRP\u1d38 curve), so employment falls — the extent depends on wage elasticity of labour demand.',
        hint: 'Union as monopoly seller → wage floor → employment trade-off.',
        tags: ['trade-unions', 'wages', 'employment'],
      },
    ],
    quiz: [
      {
        id: 'i3-l3-q1',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'In a perfectly competitive labour market, a minimum wage set ABOVE the equilibrium wage will most likely:',
        options: [
          'increase both wages and employment',
          'leave employment unchanged',
          'reduce employment by creating a surplus of labour',
          'eliminate the need for trade unions',
        ],
        correctAnswer: 2,
        explanation:
          'In perfect competition the minimum wage creates a gap between quantity of labour supplied (higher, because workers want to work at the new wage) and quantity demanded (lower, because firms hire fewer workers). The difference is unemployment — a labour surplus.',
      },
      {
        id: 'i3-l3-q2',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'In a bilateral monopoly, the final wage between employer and union is determined by:',
        options: [
          'the intersection of the MRP\u1d38 and MCL curves',
          'the intersection of the MRP\u1d38 and labour supply curves',
          'relative bargaining power of the union and the employer',
          'the government-set minimum wage',
        ],
        correctAnswer: 2,
        explanation:
          'Neither the union\'s preferred wage (MRP\u1d38 = S) nor the employer\'s preferred wage (MRP\u1d38 = MCL) prevails. The actual outcome is indeterminate within that range and depends on factors such as strike funds, profitability, and bargaining skill — i.e., relative bargaining power.',
      },
      {
        id: 'i3-l3-q3',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'A trade union is most likely to successfully raise wages with minimal employment loss when:',
        options: [
          'the demand for labour is highly elastic',
          'there are many close substitutes for union labour',
          'labour costs represent a large share of total production costs',
          'product demand for the industry\'s output is inelastic',
        ],
        correctAnswer: 3,
        explanation:
          'Inelastic product demand means consumers do not easily cut back purchases when prices rise, so firms can pass on higher labour costs without a large fall in output or employment. This makes labour demand more inelastic, allowing the union to win wage gains at little employment cost.',
      },
    ],
  },

  // ── Lesson 4 ─────────────────────────────────────────────────────────────────
  {
    id: 'i3-l4',
    moduleId: 'i3-factor-markets',
    title: 'Rent, Interest, and Profit',
    description:
      'Define economic rent (transfer earnings vs. surplus), the loanable funds market for interest rates, and economic profit.',
    order: 4,
    estimatedMinutes: 25,
    tags: ['economic-rent', 'interest-rate', 'profit'],
    content: {
      isStub: false,
      prerequisiteRecap: `The previous lesson analysed how trade unions act as monopoly sellers of labour and how minimum wages interact differently with competitive versus monopsonistic labour markets — a minimum wage can increase both wages and employment when it offsets monopsony power. This lesson extends factor market analysis beyond labour to land (economic rent), capital (the interest rate), and enterprise (economic profit).`,
      recallQuestions: [
        {
          id: 'i3-l4-recall-1',
          type: 'mcq' as const,
          question: 'In a perfectly competitive labour market, a minimum wage set ABOVE the equilibrium wage will most likely:',
          options: [
            'Reduce employment by creating a surplus of labour.',
            'Increase both wages and employment.',
            'Leave employment unchanged because firms cannot reduce hiring.',
            'Eliminate the need for trade unions in that market.',
          ],
          correctAnswer: 0,
          explanation: 'In a competitive market, a wage floor above equilibrium raises the quantity of labour supplied (workers want to work at the higher wage) but reduces the quantity demanded (firms hire fewer workers). The difference is unemployment — a labour surplus. This contrasts with a monopsonistic market where a minimum wage can raise employment.',
          marks: 1,
          difficulty: 'foundation' as const,
        },
      ],
      realWorldHook:
        'A Premier League footballer earns £200,000 per week but would still play for £50,000 per week (his transfer earnings — the best alternative use of his talent). The remaining £150,000 is pure economic rent: a surplus above what is needed to keep him in his current employment. This concept, originally applied to land by David Ricardo in 1817, now explains why highly talented individuals in scarce-supply professions command extraordinary incomes.',
      conceptualExplanation:
        'Economic rent is the payment to any factor of production above its transfer earnings — the minimum payment needed to keep a factor in its current use (i.e., its opportunity cost). For land with a perfectly inelastic supply, the entire payment is economic rent because land cannot be transferred to another use at any price. For labour, the share of earnings that is economic rent depends on supply elasticity: the more inelastic the supply, the greater the proportion of earnings that is rent. This is why athletes and pop stars — whose supply of talent is nearly perfectly inelastic — earn enormous rents, while unskilled workers in elastic-supply markets earn almost none.\n\nThe interest rate is the price of loanable funds, determined in the loanable funds market by the supply of saving and the demand for borrowing (investment). Households supply savings; firms and governments demand funds to finance investment projects. The equilibrium interest rate balances saving and investment. Key factors shifting the supply of loanable funds include household income levels, time preferences, and central bank policy; factors shifting demand include expected returns on investment and business confidence. Real interest rates (nominal rate minus inflation) are most relevant for economic decision-making, as they represent the true cost of borrowing in terms of purchasing power.\n\nEconomic profit is total revenue minus total economic cost (including all opportunity costs, explicit and implicit). Normal profit is the minimum return needed to keep a firm in an industry — it is included in economic cost, not economic profit. When economic profit is positive, resources are being used more valuably than in their next-best alternative; in competitive markets this attracts new entrants until profit is competed away. Persistent economic profit therefore signals barriers to entry, market power, or innovation rents enjoyed by first movers.',
      vocabulary: [
        {
          term: 'Economic Rent',
          definition:
            'The payment to a factor of production above its transfer earnings (opportunity cost); a surplus that does not need to be paid to keep the factor in its current use.',
          example:
            'A concert pianist who would keep playing for £30,000/year is paid £500,000/year. Her economic rent is £470,000 — a surplus arising from the near-perfectly inelastic supply of concert-grade pianists.',
        },
        {
          term: 'Loanable Funds Market',
          definition:
            'The market in which savers supply funds and borrowers demand them, with the real interest rate as the equilibrating price.',
          example:
            'When governments run large deficits they enter the loanable funds market as major borrowers, increasing demand for funds. If the supply of saving is unchanged, the real interest rate rises — this is the mechanism behind "crowding out" of private investment.',
        },
        {
          term: 'Normal Profit',
          definition:
            'The minimum level of profit required to keep a firm operating in an industry in the long run; treated as an implicit cost and included in total economic cost rather than economic profit.',
          example:
            'An entrepreneur could earn £60,000 as a salaried manager. If her business earns exactly £60,000 after paying all explicit costs, she earns normal profit (zero economic profit) and has no incentive to exit but also none to expand.',
        },
      ],
      examinerTip:
        'Be precise about the distinction between economic rent and transfer earnings — draw a supply and demand diagram for a factor market, and shade the area above the supply curve (rent) separately from the area below (transfer earnings). For interest rates, specify whether you mean nominal or real — exam questions about investment and saving decisions almost always require the real rate. On profit, always contrast economic profit with normal profit and accounting profit: stating "economic profit = TR − total economic cost (including all opportunity costs)" earns method marks.',
    },
    flashcards: [
      {
        id: 'i3-l4-fc1',
        front: 'What is the difference between economic rent and transfer earnings?',
        back: 'Transfer earnings = the minimum payment to keep a factor in its current use (its opportunity cost). Economic rent = any payment ABOVE transfer earnings. Together they sum to total factor income.',
        hint: 'Think of rent as the "surplus" above what is strictly necessary.',
        tags: ['economic-rent', 'transfer-earnings'],
      },
      {
        id: 'i3-l4-fc2',
        front: 'Why does land typically earn a large proportion of economic rent?',
        back: 'Land has a perfectly (or near-perfectly) inelastic supply — its quantity cannot be changed regardless of price. Because transfer earnings are zero (land has no alternative use in the aggregate), virtually all payments to land are economic rent.',
        hint: 'Perfectly inelastic supply → no transfer earnings.',
        tags: ['economic-rent', 'land', 'supply-elasticity'],
      },
      {
        id: 'i3-l4-fc3',
        front: 'In the loanable funds model, what determines the equilibrium real interest rate?',
        back: 'The intersection of the supply of loanable funds (from household saving) and the demand for loanable funds (from firms\' investment demand and government borrowing). A rise in investment demand or government borrowing raises the real interest rate; a rise in saving lowers it.',
        hint: 'Supply = saving; demand = investment + government borrowing.',
        tags: ['interest-rate', 'loanable-funds'],
      },
      {
        id: 'i3-l4-fc4',
        front: 'Distinguish economic profit from normal profit.',
        back: 'Normal profit is the minimum return to keep a firm in business — it equals the entrepreneur\'s opportunity cost and is included in economic costs. Economic profit = TR − total economic cost (including normal profit). Zero economic profit means the firm earns exactly normal profit.',
        hint: 'Normal profit is a cost; economic profit is the surplus above all costs including normal profit.',
        tags: ['profit', 'normal-profit', 'opportunity-cost'],
      },
    ],
    quiz: [
      {
        id: 'i3-l4-q1',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'A professional footballer earns £180,000 per week. His best alternative employment would pay £3,000 per week. His economic rent per week is:',
        options: ['£180,000', '£3,000', '£177,000', '£183,000'],
        correctAnswer: 2,
        explanation:
          'Transfer earnings = £3,000 (minimum needed to keep him playing football). Economic rent = total earnings − transfer earnings = £180,000 − £3,000 = £177,000.',
      },
      {
        id: 'i3-l4-q2',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'In the loanable funds market, an increase in household saving, all else equal, will:',
        options: [
          'raise the real interest rate',
          'lower the real interest rate',
          'raise the nominal interest rate only',
          'have no effect on the real interest rate',
        ],
        correctAnswer: 1,
        explanation:
          'Greater household saving increases the supply of loanable funds. With demand unchanged, the equilibrium real interest rate falls, making borrowing cheaper and stimulating investment.',
      },
      {
        id: 'i3-l4-q3',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question: 'A firm earns total revenue of £500,000. Explicit costs are £350,000 and implicit costs (including normal profit) are £100,000. The firm\'s economic profit is:',
        options: ['£150,000', '£50,000', '£450,000', '£100,000'],
        correctAnswer: 1,
        explanation:
          'Economic profit = TR − (explicit costs + implicit costs) = £500,000 − £350,000 − £100,000 = £50,000. The £150,000 accounting profit overstates economic profit by ignoring implicit costs.',
      },
    ],
  },

  // ── Lesson 5 ─────────────────────────────────────────────────────────────────
  {
    id: 'i3-l5',
    moduleId: 'i3-factor-markets',
    title: 'Income Inequality — Measuring and Explaining',
    description:
      'Construct and interpret the Lorenz curve and Gini coefficient; explain functional and personal income distribution.',
    order: 5,
    estimatedMinutes: 30,
    tags: ['Lorenz-curve', 'Gini', 'income-inequality'],
    content: {
      isStub: false,
      prerequisiteRecap: `The previous lesson distinguished economic rent (payment above transfer earnings — the factor's opportunity cost) from transfer earnings, and showed that land earns almost entirely economic rent because its supply is perfectly inelastic. Income inequality measures how the total reward to all factors is distributed across individuals — the Lorenz curve and Gini coefficient are the standard tools for this analysis.`,
      recallQuestions: [
        {
          id: 'i3-l5-recall-1',
          type: 'mcq' as const,
          question: 'A concert pianist earns £400,000 per year but would continue performing for £50,000 per year. What is her economic rent?',
          options: [
            '£350,000',
            '£400,000',
            '£50,000',
            '£450,000',
          ],
          correctAnswer: 0,
          explanation: 'Economic rent = total earnings − transfer earnings (opportunity cost) = £400,000 − £50,000 = £350,000. Transfer earnings are the minimum needed to keep her in her current occupation; everything above that is a surplus — economic rent.',
          marks: 1,
          difficulty: 'foundation' as const,
        },
      ],
      realWorldHook:
        'South Africa has one of the world\'s highest Gini coefficients — around 0.63 — meaning its income distribution is deeply unequal even by global standards. The bottom 20% of the population earns less than 3% of total national income, while the top 20% takes over 65%. By contrast, Denmark\'s Gini sits near 0.29. Understanding how these numbers are constructed — and what drives them — is the foundation for debating redistribution policy.',
      conceptualExplanation:
        'The Lorenz curve plots the cumulative share of total income (y-axis) against the cumulative share of the population ranked from poorest to richest (x-axis). If income were perfectly equally distributed, the curve would be the 45-degree line of perfect equality — the bottom 20% earns 20% of income, the bottom 40% earns 40%, and so on. In practice the curve bows below the diagonal: the greater the bow, the more unequal the distribution. The Gini coefficient quantifies this visually: it equals the area between the line of perfect equality and the Lorenz curve, divided by the total area under the line of equality. A Gini of 0 indicates perfect equality; a Gini of 1 indicates perfect inequality (one person earns everything).\n\nFunctional income distribution describes how national income is divided among the factors of production — wages (labour), rent (land), interest (capital), and profit (enterprise). In advanced economies, labour\'s share has historically been 60–75% of national income, though this share has been falling in many countries since the 1980s due to globalisation, technology, and the decline of trade unions. Personal income distribution describes how income is distributed among individuals or households regardless of its source. High personal inequality can co-exist with an apparently stable functional distribution if gains within each factor category are concentrated among a small number of recipients.\n\nThe determinants of income inequality are numerous and interacting. On the supply side, differences in education, skill, health, and inherited wealth create productivity gaps. On the demand side, skill-biased technological change raises the premium for high-skill workers while reducing demand for routine work. Institutional factors — minimum wage levels, union strength, tax-and-transfer systems — moderate or amplify these market forces. Globalisation can simultaneously raise wages in developing countries (reducing global inequality) while widening inequality within high-income nations as manufacturing employment contracts.',
      vocabulary: [
        {
          term: 'Lorenz Curve',
          definition:
            'A graphical representation of income (or wealth) distribution, plotting the cumulative income share of the bottom x% of the population; the further the curve bows below the 45-degree line of perfect equality, the greater the inequality.',
          example:
            'If the bottom 50% of households in a country receive 20% of total income, the point (0.5, 0.2) lies on the Lorenz curve. A perfectly equal distribution would place this point at (0.5, 0.5) on the diagonal.',
        },
        {
          term: 'Gini Coefficient',
          definition:
            'A summary measure of income inequality equal to the area between the Lorenz curve and the line of perfect equality, divided by the total area under the line of equality; ranges from 0 (perfect equality) to 1 (perfect inequality).',
          example:
            'Sweden\'s Gini of ~0.27 indicates a relatively equal distribution; the USA\'s ~0.41 indicates significantly higher inequality. A policy that raises the incomes of the poor faster than the rich will narrow the Gini.',
        },
        {
          term: 'Functional Income Distribution',
          definition:
            'The division of national income among the factors of production — wages to labour, rent to land, interest to capital, and profit to enterprise.',
          example:
            'If wages constitute 68% of GDP, rent 8%, interest 9%, and profit 15%, this is the economy\'s functional distribution. A rise in automation may shift the split toward profit and interest and away from wages.',
        },
      ],
      examinerTip:
        'In a Lorenz curve diagram, always label both axes correctly ("cumulative % of income" and "cumulative % of population") and mark the line of perfect equality explicitly. When explaining the Gini, define it as a ratio of areas — not just "a number between 0 and 1" — to show you understand its construction. For evaluation questions on inequality, distinguish causes (market forces vs. institutional factors) and distinguish between inequality of outcomes and inequality of opportunity; the latter is typically considered more policy-relevant in IB and AP contexts.',
    },
    flashcards: [
      {
        id: 'i3-l5-fc1',
        front: 'What does the Gini coefficient measure and what are its extreme values?',
        back: 'The Gini coefficient measures income (or wealth) inequality. It equals the area between the Lorenz curve and the line of perfect equality divided by the total area under the equality line. Gini = 0: perfect equality. Gini = 1: perfect inequality (one person earns all income).',
        hint: 'It is a ratio of two areas on the Lorenz curve diagram.',
        tags: ['Gini', 'income-inequality'],
      },
      {
        id: 'i3-l5-fc2',
        front: 'How is the Lorenz curve constructed and what does greater "bowing" indicate?',
        back: 'Rank the population from poorest to richest, then plot cumulative population share (x-axis) against cumulative income share (y-axis). Greater bowing below the 45-degree line of perfect equality indicates greater inequality — the bottom x% of the population earns a smaller share of income relative to their population share.',
        hint: 'Start at (0,0) and end at (100%,100%), always below or on the diagonal.',
        tags: ['Lorenz-curve', 'income-inequality'],
      },
      {
        id: 'i3-l5-fc3',
        front: 'Distinguish functional from personal income distribution.',
        back: 'Functional distribution: how national income is split among factors of production (wages, rent, interest, profit). Personal distribution: how income is distributed among individual people or households, regardless of its source. High personal inequality can occur even if the functional split is stable, if gains within each category are concentrated.',
        hint: 'Functional = by factor type; Personal = by individual.',
        tags: ['income-inequality', 'functional-distribution'],
      },
      {
        id: 'i3-l5-fc4',
        front: 'Give THREE reasons why income inequality may have increased in many developed economies since the 1980s.',
        back: '1. Skill-biased technological change — rising demand for high-skill workers raises their wages relative to low-skill workers. 2. Globalisation — manufacturing jobs (often middle-skill) moved to lower-wage economies, widening the domestic skill premium. 3. Decline of trade unions — reduced bargaining power for lower-income workers.',
        hint: 'Think technology, trade, and institutions.',
        tags: ['income-inequality', 'globalisation', 'technology'],
      },
    ],
    quiz: [
      {
        id: 'i3-l5-q1',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'Country A has a Gini coefficient of 0.25 and Country B has a Gini of 0.55. Which of the following conclusions is correct?',
        options: [
          'Country B has greater average income than Country A',
          'Country A has a more equal income distribution than Country B',
          'Country B has more people living in poverty than Country A',
          'Country A has a larger area under its Lorenz curve than Country B',
        ],
        correctAnswer: 1,
        explanation:
          'A lower Gini coefficient means the Lorenz curve is closer to the line of perfect equality, indicating a more equal distribution. Gini says nothing directly about average income levels, absolute poverty counts, or the area under the Lorenz curve (which is the same for all countries).',
      },
      {
        id: 'i3-l5-q2',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'On a Lorenz curve diagram, if the bottom 40% of the population earns 15% of total income, the corresponding point on the curve is:',
        options: ['(15, 40)', '(40, 15)', '(40, 40)', '(15, 15)'],
        correctAnswer: 1,
        explanation:
          'By convention, the x-axis shows the cumulative share of the population and the y-axis shows the cumulative share of income. The bottom 40% of the population (x = 40) earns 15% of income (y = 15), so the point is (40, 15).',
      },
      {
        id: 'i3-l5-q3',
        type: 'mcq',
        difficulty: 'standard',
        marks: 1,
        question:
          'Skill-biased technological change contributes to income inequality by:',
        options: [
          'reducing wages for both skilled and unskilled workers equally',
          'raising the relative demand for high-skill workers, widening the wage premium over low-skill workers',
          'eliminating the functional distribution of income',
          'shifting income from capital to labour across the economy',
        ],
        correctAnswer: 1,
        explanation:
          'Skill-biased technological change increases the marginal productivity — and therefore the MRP\u1d38 — of high-skill workers more than low-skill workers. This widens the wage gap between the two groups, increasing personal income inequality even if overall productivity and GDP are rising.',
      },
    ],
  },
]
