import type { CurriculumModule, Lesson } from '@/lib/types'

export const moduleInfo: Omit<CurriculumModule, 'lessons'> = {
  id: 'ib7-dev-a',
  title: 'IB Development A — Economic Development',
  description: 'Development economics concepts: measurement, barriers, aid, trade, and FDI for IB Paper 1 and 2.',
  tier: 'IB' as const,
  track: 'IB_SL' as const,
  unit: 7,
  estimatedHours: 4,
  color: '#8b5cf6',
  icon: 'BookOpen',
}

export const lessons: Lesson[] = [
  {
    id: 'ib7-l1',
    moduleId: 'ib7-dev-a',
    title: 'Economic Development vs. Growth',
    description: 'Understand the distinction between economic growth and development, and how composite indicators like the HDI capture multidimensional wellbeing.',
    order: 1,
    estimatedMinutes: 40,
    tags: ['development', 'HDI', 'poverty', 'measurement', 'IB', 'SL', 'HL'],
    content: {
      conceptualExplanation: `Economic growth refers to a quantitative increase in a country's real GDP or GDP per capita over time. It is a necessary but not sufficient condition for development. Economic development, by contrast, is a broader, qualitative process involving improvements in living standards, reduction of poverty, greater equality, and expanded human capabilities. A country can experience rapid GDP growth while millions remain trapped in poverty — a phenomenon observed in resource-rich states where gains accrue narrowly to elites or the state apparatus.\n\nThe Human Development Index (HDI), published annually by the UNDP, was designed to move "beyond GDP" by combining three dimensions: a long and healthy life (measured by life expectancy at birth), access to knowledge (measured by mean years of schooling and expected years of schooling), and a decent standard of living (measured by GNI per capita in PPP terms). Each dimension is indexed between 0 and 1, and the HDI is the geometric mean of the three indices. Countries are ranked Very High, High, Medium, or Low human development, with Norway and Switzerland consistently near the top and Niger and South Sudan near the bottom.\n\nBeyond the HDI, development economists use several complementary measures. The Multidimensional Poverty Index (MPI) identifies deprivations across health, education, and living standards simultaneously — a person is "multidimensionally poor" if they are deprived in at least one-third of weighted indicators. The Happiness Index (World Happiness Report) measures subjective wellbeing using Gallup poll data and correlates it with GDP, social support, healthy life expectancy, freedom, generosity, and corruption. The Millennium Development Goals (MDGs, 2000–2015) set eight targets including halving extreme poverty and achieving universal primary education; their successor, the Sustainable Development Goals (SDGs, 2015–2030), broadened scope to 17 goals covering inequality, climate action, and institutions. Together, these frameworks acknowledge that development is inherently multidimensional.`,
      prerequisiteRecap: `IB international economics examined the terms of trade and showed that commodity-dependent countries can face long-run deterioration in the purchasing power of their exports; development economics now broadens the lens from trade prices to the full range of living-standard dimensions that GDP per capita fails to capture — health, education, and equality.`,
      recallQuestions: [
        {
          id: 'ib7-l1-recall-1',
          type: 'mcq' as const,
          question: 'The Prebisch-Singer hypothesis is most relevant to which development challenge?',
          options: [
            'It suggests that commodity-exporting countries face long-run terms of trade deterioration, making it harder to finance development by exporting primary products',
            'It shows that rich countries benefit from comparative advantage in all goods, preventing developing countries from competing in any sector',
            'It argues that income inequality within developing countries rises as they open to international trade',
            'It predicts that commodity exporters will always run current account surpluses due to inelastic global demand',
          ],
          correctAnswer: 0,
          explanation: 'The Prebisch-Singer hypothesis (from IB6) argued that primary commodity prices fall relative to manufactured goods over time because of low income elasticity of demand and asymmetric distribution of productivity gains. This makes commodity-dependent developing countries earn less and less purchasing power per unit exported — a structural barrier to development that GDP growth alone may not overcome.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `Costa Rica regularly outranks the United States on the Happy Planet Index despite having a GDP per capita roughly one-fifth as large. Costa Rica abolished its military in 1948 and redirected spending to education and healthcare. By 2023, Costa Rica's life expectancy (80.3 years) exceeded the US average, and it generates over 99% of its electricity from renewables. This real-world case challenges students to question whether GDP per capita is an adequate proxy for human wellbeing — and why HDI and happiness indices can produce strikingly different country rankings.`,
      interactiveElement: `Create a comparison table with 5 countries across GDP per capita (PPP), life expectancy at birth, mean years of schooling, and HDI score. Suggested countries: Norway, China, Brazil, India, Niger. Notice how HDI and GDP rank differently for some countries — why might China score relatively higher on HDI than its GDP rank suggests, while resource-rich Gulf states score lower on HDI relative to GDP? Reflect on what each measure captures and what it misses.`,
      vocabulary: [
        {
          term: 'Human Development Index (HDI)',
          definition: 'A composite statistic of life expectancy, education, and per capita income used to rank countries on human development.',
          example: 'Norway consistently ranks first on the HDI despite not having the highest GDP per capita, reflecting its strong education and health outcomes.',
        },
        {
          term: 'Multidimensional Poverty Index (MPI)',
          definition: 'A measure of acute poverty that captures simultaneous deprivations across health, education, and living standards at the household level.',
          example: 'A household in sub-Saharan Africa may not be income-poor by the $2.15/day threshold yet still be MPI-poor due to lack of clean water, malnutrition, and no schooling.',
        },
        {
          term: 'Sustainable Development Goals (SDGs)',
          definition: 'Seventeen global goals adopted by the United Nations in 2015 to be achieved by 2030, covering poverty, health, education, gender equality, climate action, and more.',
          example: 'SDG 1 targets the eradication of extreme poverty; SDG 13 calls for urgent action to combat climate change — illustrating that development and sustainability are intertwined.',
        },
      ],
      deeperDive: `The debate between GDP-centric and multidimensional approaches to measuring development has profound policy implications. Countries that optimise for GDP growth may invest heavily in export industries while underinvesting in primary healthcare or rural education. Amartya Sen's "capabilities approach," which underpins the HDI framework, argues that development should be evaluated by the actual freedoms and capabilities people enjoy — not just income. This means access to healthcare, political participation, freedom from discrimination, and ability to live a dignified life are constitutive of development, not merely instrumental to it.\n\nCritics of composite indices like the HDI point out methodological limitations: the geometric mean can mask severe deprivation in one dimension if another dimension scores very high; data quality varies enormously across countries; and the choice of indicators reflects the values of their designers. The Inequality-Adjusted HDI (IHDI) addresses distributional concerns by discounting each dimension's average value by the degree of inequality within it. For countries with high internal inequality — such as South Africa — the gap between HDI and IHDI is large and policy-relevant, signalling that aggregate gains conceal divergent outcomes for different social groups.`,
      commonMisconceptions: [
        'Economic growth automatically leads to economic development — in reality, growth without equitable distribution or investment in health and education can leave large segments of the population worse off.',
        'A high HDI score means a country has no significant poverty — countries like China or Brazil have high or very high HDI yet contain hundreds of millions of multidimensionally poor people due to internal inequality.',
        'GDP per capita and HDI always rank countries in the same order — in fact, countries like Cuba rank far higher on HDI relative to GDP (due to universal healthcare and education), while oil-rich states sometimes rank lower on HDI relative to GDP.',
      ],
      examinerTip: `IB Paper 1 essays on development measurement require you to distinguish clearly between growth (GDP/GNI) and development (HDI, MPI, SDGs). Always define both terms in your introduction. When evaluating indicators, use the "strengths and limitations" structure: HDI is broader than GDP but still excludes inequality, sustainability, and subjective wellbeing. For a Paper 1 Part (b) essay (15 marks), integrate real-world examples — naming specific countries with HDI ranks and explaining anomalies scores big marks with examiners.`,
      didYouKnow: `The HDI was developed by Pakistani economist Mahbub ul Haq and Indian Nobel laureate Amartya Sen in 1990. Its creation was deliberately provocative — ul Haq wanted a single number "as vulgar as GNP" but capturing human progress, to challenge economists' fixation on income alone.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ib7-l1-fc1',
        front: 'What are the three dimensions of the Human Development Index (HDI)?',
        back: 'A long and healthy life (life expectancy), access to knowledge (mean and expected years of schooling), and a decent standard of living (GNI per capita in PPP). The HDI is the geometric mean of the three dimension indices.',
        tags: ['HDI', 'development', 'measurement', 'IB'],
      },
      {
        id: 'ib7-l1-fc2',
        front: 'What is the key difference between economic growth and economic development?',
        back: 'Economic growth is a quantitative rise in real GDP/GNI per capita. Economic development is a broader qualitative process encompassing poverty reduction, improved living standards, greater equality, and expanded human capabilities. Growth is necessary but not sufficient for development.',
        tags: ['development', 'growth', 'IB', 'SL'],
      },
      {
        id: 'ib7-l1-fc3',
        front: 'What does the Multidimensional Poverty Index (MPI) measure, and how does it differ from income poverty?',
        back: 'The MPI measures simultaneous deprivations across health (nutrition, child mortality), education (years of schooling, attendance), and living standards (cooking fuel, sanitation, water, electricity, housing, assets). A person is MPI-poor if deprived in at least one-third of weighted indicators, even if they are above the income poverty line.',
        tags: ['MPI', 'poverty', 'development', 'IB'],
      },
    ],
    quiz: [
      {
        id: 'ib7-l1-q1',
        type: 'mcq',
        question: 'Which of the following best explains why GDP per capita is considered an inadequate measure of economic development on its own?',
        options: [
          'It ignores income distribution, health outcomes, and educational attainment, which are central to human wellbeing.',
          'It is measured in nominal terms and therefore overstates real living standards.',
          'It only measures goods and services produced by domestic residents, excluding foreign income.',
          'It fails to account for the trade balance and current account position of a country.',
        ],
        correctAnswer: 0,
        explanation: 'GDP per capita measures average income but ignores how income is distributed and says nothing about health, education, or freedom. The HDI and MPI were created precisely to capture these missing dimensions of development.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l1-q2',
        type: 'mcq',
        question: 'The geometric mean is used to calculate the HDI rather than the arithmetic mean because:',
        options: [
          'It penalises unequal achievement across dimensions, so a very low score in one area cannot be fully offset by high scores in others.',
          'It weights the income dimension more heavily than health and education.',
          'It eliminates the need to convert national currencies into purchasing power parity terms.',
          'It is simpler to compute and communicate to policymakers than an arithmetic average.',
        ],
        correctAnswer: 0,
        explanation: 'The geometric mean reflects the idea that the three dimensions are not perfectly substitutable. Poor performance in one dimension (e.g., life expectancy) cannot be fully compensated by excellence in another (e.g., income), making the overall index sensitive to low values in any single dimension.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l1-q3',
        type: 'mcq',
        question: 'Which statement about the Sustainable Development Goals (SDGs) is most accurate in an IB Economics context?',
        options: [
          'The SDGs recognise that development is multidimensional, linking economic growth, social equity, and environmental sustainability.',
          'The SDGs replaced the HDI as the primary measure of development used by the UNDP.',
          'The SDGs focus exclusively on eliminating income poverty in low-income countries by 2030.',
          'The SDGs are legally binding on all UN member states and enforced by the IMF.',
        ],
        correctAnswer: 0,
        explanation: 'The 17 SDGs adopted in 2015 cover poverty, health, education, gender equality, clean energy, climate action, and strong institutions — explicitly acknowledging that development encompasses economic, social, and environmental dimensions. They are aspirational targets, not legally binding obligations.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },
  {
    id: 'ib7-l2',
    moduleId: 'ib7-dev-a',
    title: 'Barriers to Development',
    description: 'Examine the structural, institutional, and geographic factors that trap countries in low-development equilibria and prevent escape from poverty.',
    order: 2,
    estimatedMinutes: 40,
    tags: ['barriers', 'poverty trap', 'corruption', 'infrastructure', 'institutions', 'IB', 'SL', 'HL'],
    content: {
      conceptualExplanation: `Development economics identifies a cluster of interrelated barriers that can trap low-income countries in persistent underdevelopment. The poverty trap — sometimes called a "low-level equilibrium trap" — occurs when poverty itself prevents the accumulation of physical or human capital needed to escape poverty. Households too poor to afford adequate nutrition, healthcare, or schooling raise children who are also poor, perpetuating the cycle across generations. At the national level, low income means low savings, which means low investment, which means low productivity growth — a vicious circle first formalised by Ragnar Nurkse and later extended by Jeffrey Sachs in his "Big Push" theory, which argued that coordinated, large-scale external investment can break the cycle.\n\nInfrastructure deficits compound the poverty trap. Without reliable roads, ports, electricity grids, and digital connectivity, productivity remains low, markets remain fragmented, and both domestic entrepreneurs and foreign investors are deterred. Sub-Saharan Africa's infrastructure gap costs the region an estimated 2 percentage points of GDP growth annually, according to the World Bank. Institutional weakness — encompassing weak rule of law, insecure property rights, opaque and unpredictable regulatory environments, and ineffective public administration — further deters investment. Without enforceable contracts and secure property rights, businesses cannot raise capital, lenders cannot recover debts, and entrepreneurs face expropriation risk that suppresses innovation.\n\nCorruption is both a symptom and a cause of institutional weakness. When public officials extract rents from businesses, foreign investors, and aid flows, public goods are underprovided, infrastructure projects are overpriced, and tax revenue is diverted. Transparency International's Corruption Perceptions Index shows a strong positive correlation between high perceived corruption and low HDI scores. Geography presents a further structural barrier: landlocked countries face higher transport costs and are disadvantaged in global trade; tropical climates correlate with higher disease burden (malaria, dengue, bilharzia) that reduces labour productivity; and natural resource dependence can produce the "resource curse," where commodity revenues generate Dutch disease, conflict, and poor governance.`,
      prerequisiteRecap: `The previous lesson showed that economic development is multidimensional — measured by HDI, MPI, and the SDGs rather than GDP alone — and that growth can occur without development if gains are inequitably distributed; barriers to development now explain why many countries are trapped in low-HDI equilibria despite decades of GDP growth.`,
      recallQuestions: [
        {
          id: 'ib7-l2-recall-1',
          type: 'mcq' as const,
          question: 'Why is GDP per capita considered an inadequate measure of economic development on its own?',
          options: [
            'It ignores income distribution, health outcomes, and educational attainment — all central dimensions of development captured by the HDI and MPI',
            'It measures output in nominal rather than real terms, systematically overstating living standards in high-inflation economies',
            'It excludes the informal sector in developing countries, causing it to understate actual economic activity',
            'It is measured in US dollars, making cross-country comparison unreliable due to exchange rate volatility',
          ],
          correctAnswer: 0,
          explanation: 'GDP per capita measures average income but says nothing about how that income is distributed, or about the quality of health, education, and freedom that people enjoy. A country with high and rising GDP per capita can simultaneously have poor HDI performance if gains accrue to a narrow elite and public investment in health and education is neglected.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `The Democratic Republic of Congo (DRC) illustrates how multiple barriers compound one another. The DRC holds vast deposits of cobalt (essential for electric vehicle batteries), coltan, gold, and diamonds — yet ranks among the world's lowest countries on the HDI. Decades of conflict, predatory governance under Mobutu Sese Seko, institutional collapse, and geographic vastness (the country is the size of Western Europe) have prevented resource wealth from translating into development. Cobalt revenues are captured by armed groups and corrupt intermediaries rather than funding schools or hospitals, illustrating the resource curse and institutional failure simultaneously.`,
      interactiveElement: `Draw a "barriers web" diagram: place "Poverty Trap" in the centre and draw arrows connecting it to six surrounding barriers — Infrastructure Deficit, Weak Institutions, Corruption, Geography/Disease Burden, Commodity Dependence, and Capital Flight. For each link, write one sentence explaining the causal mechanism. Then identify which two barriers you believe are most fundamental and justify your reasoning. This exercise helps IB students organise multi-cause arguments for Paper 1 essays.`,
      vocabulary: [
        {
          term: 'Poverty Trap',
          definition: 'A self-reinforcing cycle in which poverty prevents the investment in human and physical capital necessary to escape poverty, maintaining a low-level development equilibrium.',
          example: 'A subsistence farmer in Malawi cannot afford fertiliser or improved seeds, resulting in low yields and no surplus to invest — perpetuating low productivity and poverty.',
        },
        {
          term: 'Resource Curse (Dutch Disease)',
          definition: 'The paradox whereby countries with abundant natural resources experience slower economic growth and worse development outcomes than resource-poor countries, often due to currency appreciation that harms manufacturing exports, volatile commodity revenues, and governance failures.',
          example: 'Nigeria\'s oil wealth has been associated with deindustrialisation, corruption, and violent conflict in the Niger Delta rather than sustained human development.',
        },
        {
          term: 'Institutional Weakness',
          definition: 'The absence of effective, accountable, and transparent public institutions — including rule of law, property rights, and competent public administration — that are prerequisites for sustainable development.',
          example: 'In countries with weak property rights, smallholder farmers cannot use their land as collateral for loans, limiting investment in productivity-enhancing inputs.',
        },
      ],
      deeperDive: `Economists debate whether geography or institutions are the primary determinant of development outcomes. Jeffrey Sachs argues that tropical geography — through disease burden, soil quality, and landlockedness — directly constrains development and that institutional quality is itself partly caused by geography. Daron Acemoglu, James Robinson, and Simon Johnson counter with their "reversal of fortune" finding: formerly prosperous colonial regions with dense indigenous populations became relatively poor after European colonisation because colonisers installed extractive institutions, while sparsely populated regions received settler institutions that protected property rights and became prosperous. Their conclusion — that institutions are the fundamental cause of long-run growth — has been influential but contested, as it does not easily account for rapid institutional change or the success of city-states like Singapore.\n\nCapital flight is a further barrier that receives less attention in textbooks. When domestic institutions are weak and political risk is high, domestic elites and businesses transfer savings abroad to safer financial systems. The African Development Bank estimates that Africa lost $1.3 trillion in illicit financial flows between 1980 and 2009 — more than it received in foreign aid and FDI combined. This reversal of the expected capital flow (from rich to poor countries) implies that developing countries are effectively lending to developed ones, a profound paradox that Dani Rodrik and others argue cannot be resolved through aid alone but requires deep institutional reform and international cooperation on tax havens.`,
      commonMisconceptions: [
        'Poor countries are poor simply because they lack natural resources — in fact, many resource-rich countries (DRC, Nigeria, Venezuela) have poor development outcomes, while resource-scarce countries (South Korea, Singapore, Botswana) have achieved strong development.',
        'Corruption is a cultural trait rather than a structural problem — in reality, corruption is strongly linked to low accountability, weak rule of law, and monopolistic rents, all of which can be altered through institutional reform.',
        'Geography is destiny — while geographic factors create challenges, institutions and policy choices mediate their impact. Botswana and Zimbabwe share similar climates and geographies but have had dramatically different development trajectories due to institutional differences.',
      ],
      examinerTip: `IB Paper 1 questions on barriers to development often ask you to "evaluate the view that institutional factors are the most significant barrier to development." Structure your essay by explaining institutional barriers thoroughly (definition, mechanisms, evidence), then challenge with alternative barriers (geography, infrastructure, poverty traps), and conclude with a nuanced judgment. Avoid listing barriers without explaining causal mechanisms — examiners reward analysis of how barriers interact, not just enumeration.`,
      didYouKnow: `Economists Daron Acemoglu and James Robinson, whose "Why Nations Fail" (2012) argued that inclusive institutions are the root cause of development, won the Nobel Memorial Prize in Economics in 2024 — validating the institutions-first view of development economics.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ib7-l2-fc1',
        front: 'Explain the poverty trap mechanism and why it is self-reinforcing.',
        back: 'Low income → low savings → low investment in human/physical capital → low productivity → low income. Poverty prevents households and nations from accumulating the capital needed to escape poverty, creating a vicious cycle. External intervention (Big Push) or targeted transfers (conditional cash transfers) may be needed to break the trap.',
        tags: ['poverty trap', 'development', 'IB', 'SL'],
      },
      {
        id: 'ib7-l2-fc2',
        front: 'What is the "resource curse" and what mechanisms explain it?',
        back: 'The resource curse is the paradox that natural resource abundance often correlates with weaker economic growth and development. Mechanisms include: (1) Dutch disease — resource exports appreciate the exchange rate, making non-resource exports uncompetitive; (2) volatile commodity revenues destabilise government budgets; (3) resource rents reduce the need for broad-based taxation, weakening the accountability link between citizens and the state.',
        tags: ['resource curse', 'Dutch disease', 'IB', 'HL'],
      },
      {
        id: 'ib7-l2-fc3',
        front: 'Why do institutional economists argue that institutions, not geography, are the primary cause of development differences?',
        back: 'Acemoglu, Robinson, and Johnson\'s "reversal of fortune" study showed that previously prosperous regions became poor after colonisation when extractive institutions were imposed, while less populated regions received settler institutions protecting property rights and later prospered. This suggests institutions — not geographic factors — determine long-run outcomes, since geography did not change but development rankings reversed.',
        tags: ['institutions', 'Acemoglu', 'IB', 'HL'],
      },
    ],
    quiz: [
      {
        id: 'ib7-l2-q1',
        type: 'mcq',
        question: 'Which of the following best describes the mechanism of the "poverty trap" at the national level?',
        options: [
          'Low national income leads to low savings and investment, which results in low productivity growth, perpetuating low income in a vicious cycle.',
          'High population growth in poor countries reduces GDP per capita regardless of the level of investment or institutional quality.',
          'Rich countries attract all foreign investment, leaving poor countries unable to access capital markets.',
          'Trade protectionism by developed countries prevents poor countries from exporting their way out of poverty.',
        ],
        correctAnswer: 0,
        explanation: 'The poverty trap operates through the savings-investment-productivity nexus: low income → low savings → insufficient investment → low productivity growth → low income. Breaking this cycle may require external capital injections (aid, FDI) or domestic reforms that raise savings rates.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l2-q2',
        type: 'mcq',
        question: 'Dutch disease refers to:',
        options: [
          'The process by which resource export revenues appreciate the real exchange rate, making non-resource manufacturing and agricultural exports uncompetitive.',
          'The spread of infectious disease from colonial powers to indigenous populations, reducing labour supply and development potential.',
          'The tendency for countries with high trade surpluses to experience inflationary pressures that erode real wages.',
          'The macroeconomic instability caused by excessive reliance on foreign aid inflows rather than domestic tax revenue.',
        ],
        correctAnswer: 0,
        explanation: 'Dutch disease was named after the Netherlands\' experience following North Sea gas discoveries in the 1960s. Resource export revenues strengthen the currency, raising the cost of domestically produced tradeable goods, which crowds out manufacturing and agriculture — sectors that often provide broader-based employment and learning-by-doing spillovers.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l2-q3',
        type: 'mcq',
        question: 'Acemoglu and Robinson\'s "reversal of fortune" finding supports which view of barriers to development?',
        options: [
          'Institutions are the fundamental cause of development differences, since colonial institutional choices — not geographic conditions — explain why previously prosperous regions became poor.',
          'Geography is the primary barrier to development, since tropical climate and landlockedness were decisive in colonial settlement patterns.',
          'Foreign aid is the most effective way to overcome development barriers, as it finances the infrastructure needed for institutional reform.',
          'Trade liberalisation is the most important policy for overcoming development barriers in formerly colonised countries.',
        ],
        correctAnswer: 0,
        explanation: 'Acemoglu, Johnson, and Robinson\'s reversal of fortune showed that the richest pre-colonial societies became the poorest post-colonially, because colonisers imposed extractive institutions in already-populated places. Geography did not change — institutions did. This supports the view that institutions, not geography, are the root cause of development divergence.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },
  {
    id: 'ib7-l3',
    moduleId: 'ib7-dev-a',
    title: 'International Trade & Development',
    description: 'Analyse how trade shapes development outcomes for LEDCs, including comparative advantage, commodity dependence, trade dependency, and fair trade initiatives.',
    order: 3,
    estimatedMinutes: 38,
    tags: ['trade', 'comparative advantage', 'LEDCs', 'fair trade', 'commodity dependence', 'IB', 'SL', 'HL'],
    content: {
      conceptualExplanation: `Classical trade theory, anchored in Ricardo's principle of comparative advantage, predicts mutual gains from trade: countries should specialise in goods for which they have the lowest opportunity cost and exchange them for goods produced more efficiently elsewhere. For Less Economically Developed Countries (LEDCs), the theory suggests benefits from exporting primary commodities or labour-intensive manufactures in which they hold comparative advantage. Empirically, export-led growth has been a powerful development engine — South Korea, Taiwan, China, and Vietnam all grew rapidly by integrating into global supply chains. However, critics argue the theory assumes away crucial dynamic factors: learning-by-doing, economies of scale, and the ability to upgrade technological capacity, all of which require deliberate industrial policy rather than pure specialisation.\n\nMany LEDCs face commodity dependence, where export revenues are concentrated in a small number of primary commodities (agricultural products, minerals, or fossil fuels) whose world prices are volatile and subject to long-run deterioration relative to manufactured goods. The Prebisch-Singer hypothesis (1950) argued that the terms of trade for primary commodity exporters systematically decline over time relative to manufactured goods, because demand for commodities grows more slowly than demand for manufactures as incomes rise (Engel's Law), and because productivity gains in manufacturing are captured by workers in rich countries through higher wages rather than lower prices, while gains in commodity production are passed on as lower prices. This "immiserising growth" scenario means that exporting more commodities may generate less and less purchasing power over time.\n\nTrade dependency theory, associated with André Gunder Frank and the dependency school, argues that integration into the global trading system on unequal terms perpetuates underdevelopment by locking LEDCs into roles as raw material suppliers and consumers of manufactured imports. While mainstream economists dismiss strong dependency theory as empirically unsupported, more nuanced versions highlight how unequal market power, intellectual property rules in WTO agreements, and agricultural subsidies in rich countries (which depress world prices for crops like cotton and sugar) disadvantage developing country exporters. Fair trade initiatives — such as the Fairtrade Foundation's certification scheme — attempt to address this by guaranteeing minimum prices to certified producers, providing a social premium for community investment, and promoting better labour standards.`,
      prerequisiteRecap: `The previous lesson identified institutional weakness, the poverty trap, and the resource curse as key barriers to development; international trade now offers a potential escape route through comparative advantage and export-led growth, but also poses risks of commodity dependence and deteriorating terms of trade for LEDCs that remain locked in primary-product specialisation.`,
      recallQuestions: [
        {
          id: 'ib7-l3-recall-1',
          type: 'mcq' as const,
          question: 'The "resource curse" describes the paradox in which natural resource wealth correlates with worse development outcomes. One key mechanism is Dutch disease, which refers to:',
          options: [
            'Resource export revenues appreciating the real exchange rate, making non-resource manufacturing and agricultural exports uncompetitive and undermining industrial diversification',
            'The spread of infectious disease in resource-extraction regions that reduces labour productivity and deters foreign investment',
            'Commodity price volatility that destabilises government revenue and prevents long-term development planning',
            'Corruption in resource revenue management that diverts funds from public health and education',
          ],
          correctAnswer: 0,
          explanation: 'Dutch disease is the exchange rate channel of the resource curse: large commodity export revenues flow into the economy and strengthen the currency, raising the cost of domestically produced tradeable goods. Manufacturing and agriculture — sectors with broader employment and productivity spillovers — become uncompetitive, reducing economic diversification and long-run development potential.',
          marks: 1,
          difficulty: 'standard' as const,
        },
      ],
      realWorldHook: `Ghana's cocoa sector illustrates trade dependency in action. Ghana is the world's second-largest cocoa producer, yet earns most export revenue from raw cocoa beans rather than processed chocolate. Chocolate manufacturing, branding, and retailing — the value-added stages — are dominated by Swiss, US, and European firms. When world cocoa prices collapsed in the early 2000s, Ghana's export revenues fell sharply, exposing the vulnerability of commodity dependence. Fairtrade-certified Ghanaian cocoa cooperatives receive a guaranteed floor price and a social premium, which local cooperatives invest in schools, health clinics, and drinking water. However, Fairtrade cocoa represents only a small fraction of Ghana's cocoa exports, limiting its macro impact.`,
      interactiveElement: `Draw a "value chain comparison" diagram for cocoa from Ghana to a Swiss chocolate bar. Estimate and label the approximate share of the final retail price (CHF 5) captured at each stage: cocoa farming (~5%), processing/grinding (~10%), manufacturing (~20%), marketing/branding (~30%), retail (~35%). Compare this with the Fairtrade model, which raises the farm-gate share slightly and adds a social premium. Discuss: what would it take for Ghana to capture a larger share of value? What barriers prevent it from processing more cocoa domestically?`,
      vocabulary: [
        {
          term: 'Prebisch-Singer Hypothesis',
          definition: 'The theory that the terms of trade for primary commodity exporters systematically deteriorate over time relative to manufactured goods, because income elasticity of demand for commodities is lower and productivity gains are distributed differently.',
          example: 'A coffee-exporting country may need to export twice as many bags of coffee in 2025 to import the same quantity of machinery it could buy in 1975, because coffee prices have fallen relative to machinery prices.',
        },
        {
          term: 'Comparative Advantage',
          definition: 'A country has a comparative advantage in producing a good if it can produce it at a lower opportunity cost than other countries, even if it is absolutely less efficient at producing everything.',
          example: 'Bangladesh has a comparative advantage in garment manufacturing — despite lower absolute productivity than Germany, its low opportunity cost (low wages relative to productivity) makes it the world\'s second-largest garment exporter.',
        },
        {
          term: 'Fair Trade',
          definition: 'A trading movement that aims to improve the lives of producers in developing countries by guaranteeing minimum prices, providing social premiums, and promoting environmental and labour standards.',
          example: 'Fairtrade-certified coffee farmers in Ethiopia receive a guaranteed floor price of $1.80 per pound plus a $0.20 social premium, regardless of world market prices, providing income stability.',
        },
      ],
      deeperDive: `The debate between free trade and strategic trade policy (infant industry protection) is central to development economics. Mainstream institutions like the IMF and WTO generally advocate trade liberalisation, arguing that openness raises productivity through competition, technology transfer, and access to global markets. However, the historical record is more nuanced: virtually every current high-income country — including the UK, US, Germany, Japan, South Korea, and China — used active industrial policy, tariff protection, and subsidies during their developmental stages. Economist Ha-Joon Chang's "kicking away the ladder" argument holds that rich countries developed behind protectionist walls and then, once developed, advocated free trade for others — effectively "kicking away" the policy ladder they had climbed.\n\nFor IB students, it is important to evaluate both the gains and risks of trade integration for LEDCs. Gains include market access, FDI attraction, technology transfer, economies of scale, and employment creation. Risks include deindustrialisation if infant industries cannot compete, commodity dependence, vulnerability to external shocks, and deteriorating terms of trade. The empirical evidence on trade and development is mixed: East Asian export-oriented economies prospered, but Latin American and African countries that liberalised rapidly in the 1980s–90s under structural adjustment often experienced growth slowdowns and rising inequality. The key variable appears to be whether countries liberalise in a sequenced, strategic manner — maintaining capacity to support infant industries and manage capital flows — rather than adopting blanket liberalisation.`,
      commonMisconceptions: [
        'Comparative advantage always benefits developing countries — in practice, if a country\'s comparative advantage lies only in low-wage labour or depletable resources, specialisation can lock it into a low-value, low-productivity export structure that limits long-run development.',
        'Fairtrade solves commodity dependence — Fairtrade improves conditions for certified producers but does not address the structural problem of export concentration. A country still earns most revenue from a single commodity, leaving it vulnerable to price shocks.',
        'Free trade is always superior to protection for developing countries — historical evidence shows that successful developers (South Korea, China, Taiwan) used strategic trade and industrial policies extensively before liberalising, suggesting that sequencing and institutional capacity matter more than blanket policy prescriptions.',
      ],
      examinerTip: `IB Paper 1 trade and development questions often present a scenario of a commodity-dependent LEDC and ask you to evaluate trade-based strategies for development. Always distinguish between static gains from comparative advantage and dynamic arguments (learning-by-doing, infant industries, terms of trade). Use specific evidence: the Prebisch-Singer hypothesis, real-world fair trade examples, and the East Asian model. Avoid one-sided answers — a balanced evaluation of free trade vs. managed trade, with a justified conclusion, is what earns top band marks.`,
      didYouKnow: `In 2022, Côte d'Ivoire and Ghana — together producing roughly 60% of the world's cocoa — threatened to withhold cocoa from the market unless major chocolate companies paid a "Living Income Differential" premium of $400 per tonne. This coordinated action, reminiscent of OPEC, achieved partial success, illustrating that commodity exporters can exercise market power under certain conditions.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ib7-l3-fc1',
        front: 'State and explain the Prebisch-Singer hypothesis.',
        back: 'The Prebisch-Singer hypothesis (1950) argues that the terms of trade for primary commodity exporters deteriorate over time relative to manufactured goods. Reasons: (1) income elasticity of demand for commodities < 1 (Engel\'s Law); (2) productivity gains in commodity production are passed on as lower prices while gains in manufacturing raise wages. Result: LEDCs must export increasing quantities of primary goods to import the same quantity of manufactures.',
        tags: ['Prebisch-Singer', 'terms of trade', 'IB', 'HL'],
      },
      {
        id: 'ib7-l3-fc2',
        front: 'What is the "kicking away the ladder" argument, and who made it?',
        back: 'Economist Ha-Joon Chang argued that today\'s rich countries developed using tariffs, subsidies, and industrial policy — then, once developed, advocated free trade for developing countries through institutions like the WTO and IMF, effectively "kicking away" the policy ladder they had climbed. This challenges the universal prescriptions of free trade liberalisation for LEDCs.',
        tags: ['Ha-Joon Chang', 'trade policy', 'IB', 'HL'],
      },
      {
        id: 'ib7-l3-fc3',
        front: 'How does fair trade attempt to address the problem of commodity dependence, and what are its limitations?',
        back: 'Fair trade guarantees certified producers a minimum floor price and a social premium, providing income stability and funding community investment. Limitations: (1) covers only a small fraction of world commodity trade; (2) does not reduce the underlying commodity dependence or diversify exports; (3) can exclude the poorest non-certified farmers; (4) evidence on long-run income gains is mixed.',
        tags: ['fair trade', 'commodity dependence', 'IB', 'SL'],
      },
    ],
    quiz: [
      {
        id: 'ib7-l3-q1',
        type: 'mcq',
        question: 'The Prebisch-Singer hypothesis predicts which of the following outcomes for primary commodity exporters?',
        options: [
          'A long-run deterioration in their terms of trade relative to manufactured goods, requiring ever-greater export volumes to purchase the same quantity of imports.',
          'A long-run improvement in terms of trade as rising global demand for commodities increases their relative price.',
          'Terms of trade stability as commodity prices and manufactured goods prices rise at the same rate over time.',
          'Complete elimination of comparative advantage in primary commodities once productivity levels converge with developed countries.',
        ],
        correctAnswer: 0,
        explanation: 'The Prebisch-Singer hypothesis argues that income elasticity of demand for primary commodities is less than one, and that productivity gains in commodities are passed on as lower prices while gains in manufacturing raise wages in rich countries. Together, these forces cause the terms of trade for commodity exporters to deteriorate over time.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l3-q2',
        type: 'mcq',
        question: 'Which of the following is the most significant limitation of the Fairtrade certification scheme as a development strategy?',
        options: [
          'It benefits certified producers but does not address the structural problem of commodity export dependence, leaving countries vulnerable to price shocks.',
          'It raises the price of commodities so high that demand in developed countries collapses, reducing total export revenues.',
          'It is administered by developing country governments, creating opportunities for corruption and rent-seeking.',
          'It requires developing countries to maintain tariffs on manufactured imports, limiting their access to global markets.',
        ],
        correctAnswer: 0,
        explanation: 'Fair trade improves conditions for certified producers by guaranteeing minimum prices, but it does not change the fact that affected countries still depend on a narrow range of primary commodities for export revenue. This concentration leaves them exposed to commodity price volatility and long-run terms of trade deterioration.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l3-q3',
        type: 'mcq',
        question: 'Ha-Joon Chang\'s "kicking away the ladder" argument is best understood as a critique of:',
        options: [
          'The prescription of free trade liberalisation for developing countries by institutions like the WTO and IMF, given that today\'s rich countries developed behind protectionist walls.',
          'The use of foreign aid as a substitute for trade in promoting economic development in low-income countries.',
          'The comparative advantage theory, which Chang argues benefits only developed countries with diversified industrial bases.',
          'The structural adjustment programmes of the 1980s that increased government spending in developing countries.',
        ],
        correctAnswer: 0,
        explanation: 'Chang argues that developed countries used tariffs, subsidies, and industrial policies during their development phase — then promoted free trade for developing countries once developed, denying them the same policy tools. This makes universal free trade prescriptions a form of "ladder kicking."',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },
  {
    id: 'ib7-l4',
    moduleId: 'ib7-dev-a',
    title: 'Aid, Debt & Financial Flows',
    description: 'Evaluate the role of foreign aid, debt relief, and remittances in financing development, including the HIPC initiative and critiques of aid dependency.',
    order: 4,
    estimatedMinutes: 38,
    tags: ['aid', 'debt relief', 'HIPC', 'remittances', 'development finance', 'IB', 'SL', 'HL'],
    content: {
      conceptualExplanation: `Official Development Assistance (ODA) — commonly called "foreign aid" — encompasses grants and concessional loans provided by governments and multilateral institutions (World Bank, regional development banks) to lower-income countries. Aid is classified by purpose: bilateral aid flows directly from one government to another; multilateral aid flows through international organisations; tied aid requires recipients to purchase goods and services from the donor country; and project aid targets specific infrastructure or social sector investments. Humanitarian aid addresses emergency needs following disasters or conflicts, while development aid targets long-run structural improvements. The UN target for ODA is 0.7% of donor countries' GNI — a goal met consistently only by Nordic countries, Luxembourg, and the UK (until 2021).\n\nDebt has been a binding constraint on development for many low-income countries. During the 1970s–80s, many developing countries borrowed heavily at low real interest rates. When US interest rates surged in the early 1980s (Volcker shock), debt service costs exploded, triggering the Latin American debt crisis and requiring structural adjustment programmes that imposed austerity and liberalisation in exchange for IMF and World Bank bailouts. Sub-Saharan African countries accumulated similarly unsustainable debt. In response, the Heavily Indebted Poor Countries (HIPC) Initiative, launched in 1996 by the IMF and World Bank, provided debt cancellation to qualifying countries that met conditions including sound macroeconomic management and preparation of a Poverty Reduction Strategy Paper. By 2020, 36 countries had received $76 billion in debt relief under HIPC and the Multilateral Debt Relief Initiative (MDRI), freeing resources for health and education spending.\n\nRemittances — money sent home by migrants working abroad — have become the largest financial flow to many developing countries, surpassing both ODA and FDI. In 2023, global remittances to low- and middle-income countries reached $669 billion (World Bank). For countries like Tajikistan (52% of GDP), Tonga (44%), and El Salvador (27%), remittances are a macroeconomic lifeline, providing income for households, supporting consumption, and partially funding investment. Unlike aid, remittances flow directly to households, bypass bureaucratic intermediaries, and tend to be countercyclical — rising during crises when diaspora communities support struggling relatives. However, high remittance transfer costs (averaging 6–7% globally) reduce their development impact, and "brain drain" — the emigration of skilled workers who then remit — can deprive origin countries of human capital.`,
      realWorldHook: `Following the 2010 earthquake in Haiti, the country received over $9 billion in pledged international aid, making it one of the largest recipient countries relative to GDP in history. Yet a decade later, Haiti remained the poorest country in the Western Hemisphere. Much aid was channelled through international NGOs rather than the Haitian government, limiting local capacity building. A significant portion funded foreign contractors and consultants, with limited local procurement. The cholera outbreak introduced by UN peacekeepers added a health catastrophe. The Haitian case has become a reference point in debates about aid effectiveness, the importance of recipient ownership, and the governance conditions for aid to succeed.`,
      interactiveElement: `Create a comparison table with 4 development finance flows — Official Development Assistance, Remittances, Foreign Direct Investment, and Portfolio Investment — and for each row complete the following columns: definition, approximate scale ($ billion globally, 2023), main advantages for LEDCs, main risks or criticisms. Use this table to answer: which flow would you prioritise for a low-income country seeking stable, long-term development finance, and why? This exercise directly prepares you for IB Paper 1 evaluation questions on aid and development finance.`,
      vocabulary: [
        {
          term: 'Official Development Assistance (ODA)',
          definition: 'Grants and concessional loans provided by OECD Development Assistance Committee governments and multilateral institutions to promote the economic development and welfare of developing countries.',
          example: 'Sweden consistently meets the 0.7% GNI ODA target, directing funds to health, education, and governance programmes in sub-Saharan Africa and South Asia.',
        },
        {
          term: 'HIPC Initiative',
          definition: 'The Heavily Indebted Poor Countries Initiative, launched in 1996 by the IMF and World Bank, provides debt cancellation to qualifying low-income countries that demonstrate sound macroeconomic management and commitment to poverty reduction.',
          example: 'Tanzania received debt relief under HIPC that freed approximately $3 billion in resources, enabling the government to abolish primary school fees — boosting enrolment by 50% within three years.',
        },
        {
          term: 'Remittances',
          definition: 'Transfers of money by migrants working abroad to their home countries, representing a major source of household income and foreign exchange for many developing economies.',
          example: 'In 2023, Mexico received $63 billion in remittances — primarily from Mexican workers in the United States — surpassing both oil exports and FDI as a source of foreign exchange.',
        },
      ],
      deeperDive: `The academic debate on aid effectiveness has intensified since Dambisa Moyo's "Dead Aid" (2009) argued that decades of aid to Africa had entrenched corruption, suppressed entrepreneurship, undermined domestic industry (through food aid competing with local farmers), and created a "culture of aid dependency" that released governments from the accountability pressures of taxation. Moyo advocated replacing aid with trade access and private capital markets. Jeffrey Sachs, in contrast, argues in "The End of Poverty" that aid delivered at sufficient scale through coordinated "big push" investments in health, education, and infrastructure can break the poverty trap — citing the success of the Millennium Villages Project and dramatic reductions in malaria mortality following bed net distribution programmes.\n\nRandomised controlled trials (RCTs) by Abhijit Banerjee, Esther Duflo, and Michael Kremer — 2019 Nobel laureates — provide a more granular picture. Their research shows that small-scale, targeted interventions (deworming school children, direct cash transfers, microcredit) can have high benefit-cost ratios, while large-scale budget support to governments with poor governance structures often fails. The meta-lesson is that aid effectiveness depends critically on the type of aid, the governance environment, recipient ownership, and alignment with domestic priorities — not on the volume of aid alone. Conditional cash transfer programmes (Bolsa Família in Brazil, Oportunidades in Mexico) that link transfers to school attendance and health check-ups have demonstrated strong development outcomes, suggesting that direct household transfers with behavioural incentives can outperform traditional project aid.`,
      commonMisconceptions: [
        'All foreign aid is beneficial and more aid always leads to better development outcomes — in reality, aid effectiveness depends on governance quality, recipient ownership, aid type, and whether it funds recurrent expenditure (creating dependency) vs. investment.',
        'Remittances are a short-term household consumption fund with no development impact — evidence shows remittances fund education, healthcare, small business investment, and housing, and are more stable and directly targeted than most aid flows.',
        'Debt relief is a "free gift" with no conditionality — HIPC debt relief required countries to demonstrate sound macroeconomic management, produce Poverty Reduction Strategy Papers, and meet performance benchmarks, creating a strong conditionality framework similar to IMF programme conditions.',
      ],
      examinerTip: `IB Paper 2 data response questions frequently present data on aid flows, debt ratios, or remittances for a specific country and ask you to discuss the role of one financial flow in development. Always link the flow to specific development outcomes (health, education, investment), evaluate its limitations (dependency, brain drain, conditionality), and use the data provided. For a Paper 1 essay evaluating aid as a development strategy, structure your argument as: explain why aid is needed (poverty trap, public goods failures) → analyse effectiveness evidence (RCTs, HIPC outcomes) → evaluate limitations (dependency, governance, tied aid) → conclude with conditions under which aid works.`,
      didYouKnow: `The world's largest single remittance corridor is the United States to Mexico. In 2023, Mexican migrants in the US sent home $63 billion — a figure that exceeded Mexico's entire oil export revenues. High-frequency data show that remittances to Mexico actually increased during the 2020 COVID-19 recession, as migrants worked extra hours to support families, demonstrating the countercyclical nature of remittances.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ib7-l4-fc1',
        front: 'What is the HIPC Initiative and what conditions must countries meet to qualify?',
        back: 'The Heavily Indebted Poor Countries (HIPC) Initiative (1996, IMF/World Bank) provides debt cancellation to qualifying low-income countries. Conditions include: demonstrating sound macroeconomic management under an IMF programme, preparing a Poverty Reduction Strategy Paper (PRSP) with civil society, and meeting a "decision point" and "completion point" performance benchmark. 36 countries received $76 billion in relief by 2020.',
        tags: ['HIPC', 'debt relief', 'IB', 'SL'],
      },
      {
        id: 'ib7-l4-fc2',
        front: 'Evaluate two advantages and two disadvantages of remittances as a source of development finance.',
        back: 'Advantages: (1) flow directly to households, bypassing governance failures and bureaucratic intermediaries; (2) countercyclical — rise during recessions, providing a stabilising buffer. Disadvantages: (1) brain drain — emigration of skilled workers deprives origin countries of human capital; (2) high transfer costs (average 6–7%) reduce the net benefit reaching recipients; also may reduce labour supply incentives if households become reliant on inflows.',
        tags: ['remittances', 'development finance', 'IB', 'HL'],
      },
      {
        id: 'ib7-l4-fc3',
        front: 'Distinguish between "tied aid" and "untied aid" and explain why tied aid is often criticised.',
        back: 'Tied aid requires the recipient country to spend the aid on goods and services from the donor country. Untied aid allows recipients to procure from the most competitive source. Tied aid is criticised because: (1) it often means purchasing overpriced donor-country goods; (2) it restricts recipient ownership and policy space; (3) the OECD estimates tied aid is 15–30% less efficient than untied aid because of procurement restrictions.',
        tags: ['tied aid', 'ODA', 'IB', 'SL'],
      },
    ],
    quiz: [
      {
        id: 'ib7-l4-q1',
        type: 'mcq',
        question: 'Dambisa Moyo\'s critique of foreign aid argues that long-term aid to Africa has primarily:',
        options: [
          'Created aid dependency, undermined domestic entrepreneurship, entrenched corruption, and suppressed local industry by competing with domestic production.',
          'Funded successful infrastructure projects that have significantly raised GDP per capita across recipient countries.',
          'Reduced income inequality by directing resources to the poorest households through conditional cash transfer programmes.',
          'Strengthened institutional capacity by requiring recipient governments to improve tax collection and public financial management.',
        ],
        correctAnswer: 0,
        explanation: 'Moyo\'s "Dead Aid" (2009) argues that aid created a "culture of dependency," entrenched corruption by providing governments with revenues outside the taxation-accountability nexus, and competed with local producers (especially food aid). She advocates trade access and private capital as superior alternatives.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l4-q2',
        type: 'mcq',
        question: 'Which of the following is the most accurate description of why remittances are considered countercyclical?',
        options: [
          'Remittances tend to increase during economic downturns in the origin country, as diaspora workers send more money home to support struggling families.',
          'Remittances automatically adjust to inflation in the recipient country, maintaining their real purchasing power over time.',
          'Remittance flows increase during booms in the destination country, as migrants earn higher wages and remit a larger share.',
          'Remittances are denominated in US dollars, which appreciates during global recessions, increasing their local currency value.',
        ],
        correctAnswer: 0,
        explanation: 'Remittances are countercyclical with respect to the origin country\'s economic cycle: when origin countries face shocks (recession, natural disaster), diaspora workers increase remittance flows to support families. This was observed during the 2008–09 financial crisis and during the COVID-19 pandemic for many developing countries.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l4-q3',
        type: 'mcq',
        question: 'The research of Banerjee, Duflo, and Kremer (2019 Nobel laureates) on aid effectiveness most strongly supports which conclusion?',
        options: [
          'Small-scale, targeted interventions evaluated through randomised controlled trials can be highly effective, but large-scale budget support to poorly governed states often fails.',
          'All forms of foreign aid are ineffective and should be replaced with private sector investment and trade liberalisation.',
          'Aid effectiveness depends entirely on the volume of aid — countries receiving more than 10% of GNI in aid consistently outperform those receiving less.',
          'Multilateral aid channelled through the World Bank is always more effective than bilateral aid between governments.',
        ],
        correctAnswer: 0,
        explanation: 'Banerjee, Duflo, and Kremer\'s RCT-based research shows that specific, well-designed interventions (deworming, cash transfers, vaccination campaigns) can have high impact at relatively low cost. However, their work also cautions against large-scale budget support in poorly governed contexts, emphasising that context, design, and governance quality determine aid effectiveness.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },
  {
    id: 'ib7-l5',
    moduleId: 'ib7-dev-a',
    title: 'Foreign Direct Investment & MNCs',
    description: 'Assess the role of multinational corporations and FDI in development, analysing benefits, transfer pricing, tax havens, and the race to the bottom.',
    order: 5,
    estimatedMinutes: 35,
    tags: ['FDI', 'MNCs', 'transfer pricing', 'tax havens', 'race to the bottom', 'IB', 'SL', 'HL'],
    content: {
      conceptualExplanation: `Foreign Direct Investment (FDI) involves an entity resident in one economy making a lasting investment in — and exercising managerial control over — an enterprise in another economy (typically defined as acquiring at least 10% of voting shares). FDI from Multinational Corporations (MNCs) represents a major source of capital, technology, and employment for developing countries. The potential benefits are substantial: FDI can supplement domestic savings and fill the savings-investment gap; MNCs transfer technology, management practices, and global market access; FDI creates employment and can generate backward linkages with domestic suppliers; and MNC operations generate tax revenue for host government budgets. Export-processing zones (EPZs) and special economic zones (SEZs) have been used by countries like China, Bangladesh, and Mauritius to attract FDI by offering streamlined regulations, infrastructure, and tax incentives in designated areas.\n\nHowever, the development impact of FDI and MNCs is deeply contested. MNCs may use transfer pricing — the setting of artificial prices for transactions between related entities within the same corporate group across different jurisdictions — to shift profits from high-tax developing countries to low-tax jurisdictions (tax havens), eroding the host country's corporate tax base. The OECD/G20 Base Erosion and Profit Shifting (BEPS) project was launched in 2013 to address this; the 2021 agreement on a global minimum corporate tax rate of 15% (Pillar Two) aims to limit the incentive to shift profits to low-tax jurisdictions. Repatriation of profits by MNCs means that a significant share of value created in the host country flows back to the home country, limiting the development multiplier. Enclave economies — where MNC operations have few links to the domestic economy, importing inputs and repatriating profits — generate little spillover.\n\nThe "race to the bottom" in labour and environmental standards describes the competitive dynamic in which countries and localities reduce standards to attract FDI, creating a global downward pressure on workers' rights and environmental protection. If Bangladesh reduces factory safety standards or weakens minimum wage laws to attract garment MNCs, other competing countries may follow, resulting in a global deterioration of standards that benefits corporations at the expense of workers and communities. Critics point to disasters like the 2013 Rana Plaza factory collapse in Bangladesh — killing 1,134 workers in a garment facility supplying global brands — as evidence that race-to-the-bottom dynamics have real human costs. Advocates of FDI counter that MNCs often pay above-market wages and provide better working conditions than domestic alternatives, and that the correlation between FDI and higher wages in developing countries is positive in most empirical studies.`,
      realWorldHook: `Ireland's economic model offers a case study in FDI-driven development — but also its limits. By maintaining a 12.5% corporate tax rate, Ireland attracted the European headquarters of tech giants (Google, Apple, Facebook) and pharmaceutical multinationals. FDI transformed Ireland from one of Europe's poorest countries in the 1980s to one of its wealthiest by the 2010s. However, Apple's Irish tax arrangements — challenged by the European Commission as illegal state aid — revealed how transfer pricing and special tax rulings can mean that large MNCs pay effective corporate tax rates of near zero. Ireland's GDP is famously distorted by MNC profit-shifting, prompting the Central Statistical Office to create "Modified Gross National Income" (GNI*) as a more accurate measure of Irish residents' actual income.`,
      interactiveElement: `Draw a cost-benefit matrix for FDI in a developing country. Create two columns (Benefits and Costs) and populate each with at least four entries across three rows: Economic impacts, Social/Labour impacts, and Environmental impacts. Examples: Economic Benefits — capital inflows, technology transfer; Economic Costs — profit repatriation, transfer pricing, tax base erosion. After completing the matrix, assign each entry a rating from 1 (minor) to 3 (major) based on your assessment of magnitude. Calculate a "net score" for each row. Does the overall matrix support or challenge the view that FDI is beneficial for development?`,
      vocabulary: [
        {
          term: 'Transfer Pricing',
          definition: 'The setting of prices for transactions between related entities (subsidiaries, divisions) within the same multinational corporate group, which can be manipulated to shift taxable profits to low-tax jurisdictions.',
          example: 'An MNC produces goods in a high-tax country at cost and "sells" them at a very low price to its subsidiary in a tax haven, which then sells them at full market price to customers — shifting the taxable profit to the low-tax jurisdiction.',
        },
        {
          term: 'Race to the Bottom',
          definition: 'The competitive dynamic in which countries or jurisdictions reduce labour, environmental, or tax standards to attract FDI, creating downward pressure on standards globally.',
          example: 'When several Southeast Asian countries compete for garment factory FDI by weakening minimum wage laws, each individual country\'s "rational" competitive response leads to collectively worse outcomes for workers across the region.',
        },
        {
          term: 'Enclave Economy',
          definition: 'An MNC operation that has few linkages to the domestic economy — importing most inputs, repatriating profits, and employing limited local management — thereby generating minimal development spillovers for the host country.',
          example: 'An oil extraction MNC in a developing country that imports all equipment, employs expatriate engineers, and repatriates profits creates an enclave with negligible local supply chain development or technology transfer.',
        },
      ],
      deeperDive: `The empirical literature on FDI and development is nuanced. A meta-analysis of over 100 studies by Görg and Greenaway (2004) found that FDI spillovers to domestic firms are not automatic — they depend on the absorptive capacity of domestic firms (their ability to learn from and compete with MNCs), the degree of backward linkages, and the policy environment. Countries that combined FDI attraction with active industrial policy to develop domestic suppliers — like South Korea in the 1970s or China's joint venture requirements — achieved stronger technology transfer than countries that offered investment incentives without linkage conditions. This suggests that "passive FDI" strategies (simply offering tax holidays and deregulated EPZs) generate less development than "active FDI" strategies that condition incentives on technology transfer, local content, and training requirements.\n\nThe 2021 global minimum corporate tax agreement represents a significant attempt to address the tax competition dynamic. The OECD/G20 framework (Pillar Two) sets a 15% global minimum effective corporate tax rate for large multinationals (revenues exceeding €750 million), with an "income inclusion rule" allowing parent country taxation if the subsidiary is taxed below 15% in the host country. Critics argue 15% is too low (most OECD countries have statutory rates of 20–30%) and that carve-outs for substance and transitional rules will limit revenue gains. Developing countries, represented through the G24, pushed for a higher rate and a larger share of taxing rights — issues that the UN Tax Committee has continued to pursue. The agreement, while imperfect, signals a potential end to the most egregious race to the bottom on corporate taxation.`,
      commonMisconceptions: [
        'FDI is always beneficial for host developing countries — in reality, the development impact depends on the type of FDI (extractive vs. manufacturing vs. services), the degree of domestic linkages, profit repatriation, transfer pricing, and the policy conditions negotiated by the host government.',
        'MNCs always pay lower wages than domestic firms — empirical evidence generally shows that foreign-owned firms pay a wage premium of 10–30% over comparable domestic firms in developing countries, partly because they employ more skilled workers and operate at larger scale.',
        'A global minimum corporate tax of 15% will eliminate profit shifting — the 15% minimum is below statutory rates in most OECD countries, and substantive carve-outs mean the effective impact on profit shifting to the most egregious havens will be limited without further reform.',
      ],
      examinerTip: `IB Paper 1 essays on MNCs and development require balanced evaluation. Present the case for FDI (capital, technology, employment, exports) before critically analysing costs (profit repatriation, transfer pricing, race to the bottom, enclave economies). Use Ireland, Bangladesh, or China as real-world examples. For a top-band (13–15 marks) response, your conclusion must synthesise conditions under which FDI is likely to be development-enhancing vs. harmful — not simply list pros and cons. The examiner rubric explicitly rewards nuanced, evidence-based judgment over comprehensive but undifferentiated lists.`,
      didYouKnow: `The 2021 OECD/G20 global minimum corporate tax deal was signed by 136 countries representing over 90% of global GDP — the largest coordinated overhaul of international corporate tax rules in history. If fully implemented, the OECD estimates it will generate $150 billion in additional global tax revenues annually, much of which could fund development in lower-income countries.`,
      isStub: false,
    },
    flashcards: [
      {
        id: 'ib7-l5-fc1',
        front: 'Explain transfer pricing and how it enables MNCs to reduce their tax burden in developing host countries.',
        back: 'Transfer pricing involves setting the price of transactions between related subsidiaries within an MNC group. By artificially pricing intra-group transactions (e.g., intellectual property licences, management fees, goods), MNCs can shift taxable profits from high-tax developing host countries to low-tax jurisdictions (tax havens). This reduces the host country\'s corporate tax revenue without affecting the MNC\'s global commercial performance.',
        tags: ['transfer pricing', 'MNCs', 'tax', 'IB', 'HL'],
      },
      {
        id: 'ib7-l5-fc2',
        front: 'What is the "race to the bottom" in the context of FDI and developing countries?',
        back: 'The race to the bottom describes how countries compete to attract FDI by reducing corporate tax rates, relaxing labour standards (minimum wages, union rights, safety regulations), or weakening environmental protections. While any individual country\'s action may attract FDI, the collective outcome is a global deterioration of standards — transferring benefits from workers and communities to multinational shareholders.',
        tags: ['race to the bottom', 'FDI', 'IB', 'SL'],
      },
      {
        id: 'ib7-l5-fc3',
        front: 'Under what conditions is FDI most likely to generate significant development spillovers for a host developing country?',
        back: 'FDI spillovers are stronger when: (1) domestic firms have sufficient absorptive capacity to learn from and compete with MNCs; (2) host governments require local content, technology transfer, or joint venture arrangements; (3) MNCs develop backward linkages with domestic suppliers; (4) the host country invests in education and training to enable local skill development. Passive FDI attraction (tax holidays without linkage conditions) generates fewer spillovers than active industrial policy.',
        tags: ['FDI', 'spillovers', 'development', 'IB', 'HL'],
      },
    ],
    quiz: [
      {
        id: 'ib7-l5-q1',
        type: 'mcq',
        question: 'An MNC uses transfer pricing to sell a product manufactured in Country A (40% corporate tax rate) to its subsidiary in Country B (2% corporate tax rate) at below-market prices. The subsidiary then sells at full market price to final customers. The primary effect is:',
        options: [
          'Profits are shifted from Country A to Country B, reducing the MNC\'s total tax liability and depriving Country A of corporate tax revenue.',
          'Country A gains additional export revenue from the artificially low intra-group sales price.',
          'The final price to consumers in Country B\'s market falls, benefiting local households.',
          'Country B\'s trade balance improves as the subsidiary reports higher import values.',
        ],
        correctAnswer: 0,
        explanation: 'By under-pricing the transaction from the high-tax to the low-tax jurisdiction, the MNC reports low profit in Country A (where it is taxed at 40%) and high profit in Country B (taxed at 2%), minimising global tax liability. Country A loses corporate tax revenue that could fund public services.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l5-q2',
        type: 'mcq',
        question: 'The "race to the bottom" in corporate taxation is most directly addressed by which policy initiative?',
        options: [
          'The OECD/G20 global minimum corporate tax rate of 15% under Pillar Two of the BEPS framework.',
          'The IMF\'s structural adjustment conditionality requiring developing countries to reduce budget deficits.',
          'The WTO\'s trade dispute resolution mechanism, which prohibits export subsidies to MNCs.',
          'The World Bank\'s Doing Business index, which ranks countries on the ease of establishing foreign investments.',
        ],
        correctAnswer: 0,
        explanation: 'The Pillar Two global minimum corporate tax (15%) agreed by 136 countries in 2021 directly targets the race to the bottom on corporate taxation by setting a floor below which MNC subsidiaries cannot be taxed without triggering taxation by the parent country, reducing the incentive for tax competition.',
        marks: 1,
        difficulty: 'higher',
      },
      {
        id: 'ib7-l5-q3',
        type: 'mcq',
        question: 'Research on FDI spillovers to domestic firms in developing countries most consistently finds that:',
        options: [
          'Spillovers are not automatic and depend on domestic firms\' absorptive capacity, backward linkages, and the policy conditions attached to FDI.',
          'FDI always reduces domestic firm productivity by crowding out domestic investment and skilled workers.',
          'Spillovers are largest in extractive industry FDI, where technology transfer from mining MNCs is most significant.',
          'FDI spillovers occur equally regardless of host country institutional quality or the sector of investment.',
        ],
        correctAnswer: 0,
        explanation: 'The academic literature (e.g., Görg and Greenaway, 2004) finds that FDI spillovers are conditional on absorptive capacity of domestic firms, backward supply chain linkages, and active industrial policies requiring technology transfer or local content. Passive FDI attraction in EPZs without linkage conditions tends to generate enclave economies with limited spillovers.',
        marks: 1,
        difficulty: 'higher',
      },
    ],
  },
]
